export type StrengthsLibrarySeed = {
  theme_name: string;
  domain: string;
  leadership_advantages: string;
  possible_blind_spots: string;
  development_uses: string;
  coaching_questions: string[];
};

export type DevelopmentProjectSeed = {
  title: string;
  description: string;
  difficulty: "foundational" | "intermediate" | "advanced";
  duration_days: number;
  applicable_roles: string[];
  competencies_developed: string[];
  strengths_leveraged: string[];
  expected_outcomes: string[];
  mentor_questions: string[];
  evidence_of_success: string[];
};

export const strengthsLibrary: StrengthsLibrarySeed[] = [
  {
    theme_name: "Achiever",
    domain: "Executing",
    leadership_advantages: "Brings stamina, pace, and a bias toward finishing meaningful work.",
    possible_blind_spots: "Can over-index on productivity and unintentionally rush others.",
    development_uses: "Use Achiever to create visible follow-through on leadership goals and project milestones.",
    coaching_questions: ["What progress matters most this week?", "How will you pace yourself without burning out the team?"],
  },
  {
    theme_name: "Activator",
    domain: "Influencing",
    leadership_advantages: "Turns ideas into motion and helps teams move past hesitation.",
    possible_blind_spots: "May start too quickly before alignment or operational detail is in place.",
    development_uses: "Use Activator to begin needed conversations and pilot small leadership experiments.",
    coaching_questions: ["Where is quick action useful?", "What needs one more round of input before launch?"],
  },
  {
    theme_name: "Adaptability",
    domain: "Relationship Building",
    leadership_advantages: "Stays calm in change and meets people where they are in the moment.",
    possible_blind_spots: "May under-plan or avoid setting firmer direction when the team needs it.",
    development_uses: "Use Adaptability to lead through uncertainty while practicing clearer prioritization.",
    coaching_questions: ["How are you helping others stay steady?", "Where does flexibility need to become a decision?"],
  },
  {
    theme_name: "Analytical",
    domain: "Strategic Thinking",
    leadership_advantages: "Separates signal from noise and strengthens decisions with evidence.",
    possible_blind_spots: "Can overanalyze and delay action or miss emotional context.",
    development_uses: "Use Analytical to frame clean problem statements and measurable improvement plans.",
    coaching_questions: ["What evidence matters most?", "How will you communicate the human side of the analysis?"],
  },
  {
    theme_name: "Arranger",
    domain: "Executing",
    leadership_advantages: "Orchestrates people, resources, and moving parts fluidly.",
    possible_blind_spots: "May take on too much coordination personally.",
    development_uses: "Use Arranger to redesign workflows and clarify owners across cross-functional work.",
    coaching_questions: ["What combination of people and resources unlocks this work?", "What can you delegate sooner?"],
  },
  {
    theme_name: "Belief",
    domain: "Executing",
    leadership_advantages: "Creates integrity, consistency, and conviction around purpose.",
    possible_blind_spots: "Can become rigid when others approach the same outcome differently.",
    development_uses: "Use Belief to anchor difficult decisions in values and mission.",
    coaching_questions: ["Which value needs to stay non-negotiable?", "Where can principle and flexibility coexist?"],
  },
  {
    theme_name: "Command",
    domain: "Influencing",
    leadership_advantages: "Names hard truths directly and gives teams confidence in tense moments.",
    possible_blind_spots: "Can sound overly forceful if not paired with listening.",
    development_uses: "Use Command to lead difficult conversations and raise concerns early.",
    coaching_questions: ["What conversation are others avoiding?", "How will you stay direct without closing people down?"],
  },
  {
    theme_name: "Communication",
    domain: "Influencing",
    leadership_advantages: "Turns complexity into stories that people can follow and repeat.",
    possible_blind_spots: "May overtalk or prefer presentation over precision.",
    development_uses: "Use Communication to translate strategy, quality goals, and change work into understandable messages.",
    coaching_questions: ["What is the clearest story here?", "How do you know people actually understood the message?"],
  },
  {
    theme_name: "Competition",
    domain: "Influencing",
    leadership_advantages: "Raises standards and pushes for visible performance improvement.",
    possible_blind_spots: "Can create unnecessary comparison or win-lose dynamics.",
    development_uses: "Use Competition to sharpen measurable targets while protecting collaboration.",
    coaching_questions: ["What standard are you trying to raise?", "How will the team experience that pressure?"],
  },
  {
    theme_name: "Connectedness",
    domain: "Relationship Building",
    leadership_advantages: "Helps teams see how people, mission, and outcomes fit together.",
    possible_blind_spots: "May struggle to make harder tradeoffs when all perspectives feel important.",
    development_uses: "Use Connectedness to build alignment across departments and stakeholders.",
    coaching_questions: ["What larger purpose can you name here?", "Where does alignment still need a decision?"],
  },
  {
    theme_name: "Consistency",
    domain: "Executing",
    leadership_advantages: "Builds fairness, dependable standards, and repeatable processes.",
    possible_blind_spots: "Can over-standardize when nuance matters.",
    development_uses: "Use Consistency to create fair leader routines, escalation paths, and accountability practices.",
    coaching_questions: ["What process should become more consistent?", "Where do exceptions need room to exist?"],
  },
  {
    theme_name: "Context",
    domain: "Strategic Thinking",
    leadership_advantages: "Learns from history and patterns to improve present decisions.",
    possible_blind_spots: "Can spend too long looking backward before committing forward.",
    development_uses: "Use Context to understand why an organizational issue persists before redesigning it.",
    coaching_questions: ["What does history teach here?", "When do you have enough context to move?"],
  },
  {
    theme_name: "Deliberative",
    domain: "Executing",
    leadership_advantages: "Sees risk early and protects teams from preventable mistakes.",
    possible_blind_spots: "May appear hesitant or overly cautious during change.",
    development_uses: "Use Deliberative to strengthen readiness reviews, policy updates, and risk mitigation plans.",
    coaching_questions: ["What risk is easiest to miss?", "How will you prevent caution from becoming delay?"],
  },
  {
    theme_name: "Developer",
    domain: "Relationship Building",
    leadership_advantages: "Notices growth in others and invests in long-term capability.",
    possible_blind_spots: "May hold onto coaching when stronger accountability is needed.",
    development_uses: "Use Developer to build leader pipelines, mentoring cadences, and stretch assignments.",
    coaching_questions: ["Where do you see real growth potential?", "What accountability needs to accompany support?"],
  },
  {
    theme_name: "Discipline",
    domain: "Executing",
    leadership_advantages: "Creates structure, order, and clean follow-through.",
    possible_blind_spots: "Can become uncomfortable when plans change or ambiguity is high.",
    development_uses: "Use Discipline to establish checklists, meeting rhythm, and operational reliability.",
    coaching_questions: ["What routine will stabilize this work?", "Where does the plan need more flexibility?"],
  },
  {
    theme_name: "Empathy",
    domain: "Relationship Building",
    leadership_advantages: "Reads emotional undercurrents and builds trust quickly.",
    possible_blind_spots: "Can absorb others' stress or avoid sharper feedback.",
    development_uses: "Use Empathy to tailor coaching, strengthen rounding, and support difficult conversations well.",
    coaching_questions: ["What is this person feeling that is not being said?", "How will you stay compassionate and clear?"],
  },
  {
    theme_name: "Focus",
    domain: "Executing",
    leadership_advantages: "Keeps priorities visible and reduces drift.",
    possible_blind_spots: "May dismiss worthwhile side paths or move past reflection too fast.",
    development_uses: "Use Focus to keep development goals tied to role-critical outcomes.",
    coaching_questions: ["What matters most right now?", "What are you intentionally not doing?"],
  },
  {
    theme_name: "Futuristic",
    domain: "Strategic Thinking",
    leadership_advantages: "Sees what could be next and energizes people around possibility.",
    possible_blind_spots: "May under-translate big vision into present-day steps.",
    development_uses: "Use Futuristic to connect near-term stretch assignments to long-term leadership readiness.",
    coaching_questions: ["What future are you painting?", "What immediate step makes that future credible?"],
  },
  {
    theme_name: "Harmony",
    domain: "Relationship Building",
    leadership_advantages: "Builds cooperation and lowers unnecessary friction.",
    possible_blind_spots: "May avoid productive tension or postpone hard decisions.",
    development_uses: "Use Harmony to align teams while practicing more direct accountability when needed.",
    coaching_questions: ["What common ground is available?", "What conflict is still necessary to address?"],
  },
  {
    theme_name: "Ideation",
    domain: "Strategic Thinking",
    leadership_advantages: "Generates fresh angles, creative options, and connections others miss.",
    possible_blind_spots: "Can flood the room with possibilities without narrowing them.",
    development_uses: "Use Ideation to reframe stuck operational problems and design stronger projects.",
    coaching_questions: ["What new angle opens this up?", "Which idea deserves real follow-through?"],
  },
  {
    theme_name: "Includer",
    domain: "Relationship Building",
    leadership_advantages: "Expands participation and notices who may be left out.",
    possible_blind_spots: "May spend too little time differentiating performance or readiness.",
    development_uses: "Use Includer to strengthen engagement and cross-functional trust in project work.",
    coaching_questions: ["Who still needs a voice here?", "Where do fairness and performance need to be balanced?"],
  },
  {
    theme_name: "Individualization",
    domain: "Relationship Building",
    leadership_advantages: "Sees unique wiring in people and adapts leadership accordingly.",
    possible_blind_spots: "May create uneven experiences if tailoring becomes inconsistent.",
    development_uses: "Use Individualization to match stretch work, coaching, and communication to each person.",
    coaching_questions: ["What does this person uniquely need?", "How will you keep the approach fair and transparent?"],
  },
  {
    theme_name: "Input",
    domain: "Strategic Thinking",
    leadership_advantages: "Collects useful knowledge, examples, and resources that enrich decisions.",
    possible_blind_spots: "Can keep gathering information after enough is already available.",
    development_uses: "Use Input to build practical toolkits, examples, and evidence for leadership development.",
    coaching_questions: ["What resource would strengthen this work?", "When is the collection phase done?"],
  },
  {
    theme_name: "Intellection",
    domain: "Strategic Thinking",
    leadership_advantages: "Brings reflection, depth, and thoughtful synthesis to leadership work.",
    possible_blind_spots: "May stay internal too long or delay visible action.",
    development_uses: "Use Intellection to sharpen self-awareness, decision quality, and reflective debriefing.",
    coaching_questions: ["What have you learned from this experience?", "What thought now needs an action?"],
  },
  {
    theme_name: "Learner",
    domain: "Strategic Thinking",
    leadership_advantages: "Accelerates growth, curiosity, and adaptation in new territory.",
    possible_blind_spots: "May enjoy learning more than application or closure.",
    development_uses: "Use Learner to approach weak competencies as buildable skills with practice loops.",
    coaching_questions: ["What are you learning fastest right now?", "How will you prove that learning in behavior?"],
  },
  {
    theme_name: "Maximizer",
    domain: "Influencing",
    leadership_advantages: "Pushes good work toward excellence and sharper impact.",
    possible_blind_spots: "May over-polish or lose patience with average performance.",
    development_uses: "Use Maximizer to raise leadership standards while coaching others toward them.",
    coaching_questions: ["What would make this excellent?", "Where is good enough actually enough?"],
  },
  {
    theme_name: "Positivity",
    domain: "Relationship Building",
    leadership_advantages: "Lifts morale, creates hope, and helps teams recover energy.",
    possible_blind_spots: "May underplay risk or skip over harder emotion too quickly.",
    development_uses: "Use Positivity to keep development work energizing without softening accountability.",
    coaching_questions: ["How are you bringing hope into this work?", "What hard truth still needs to be named?"],
  },
  {
    theme_name: "Relator",
    domain: "Relationship Building",
    leadership_advantages: "Builds deep trust and dependable partnership with key people.",
    possible_blind_spots: "May concentrate influence in known relationships and move slowly with new people.",
    development_uses: "Use Relator to deepen mentoring, staff trust, and cross-functional credibility.",
    coaching_questions: ["Which relationships most need investment?", "Who beyond your trusted circle should you engage?"],
  },
  {
    theme_name: "Responsibility",
    domain: "Executing",
    leadership_advantages: "Owns commitments fully and follows through with integrity.",
    possible_blind_spots: "Can overcommit or carry work others should own.",
    development_uses: "Use Responsibility to build reliability, trust, and clean project ownership.",
    coaching_questions: ["What promise matters most here?", "What should stay yours and what should be shared?"],
  },
  {
    theme_name: "Restorative",
    domain: "Executing",
    leadership_advantages: "Enjoys solving problems and stabilizing broken systems.",
    possible_blind_spots: "May focus so much on fixing that celebration and future vision get lost.",
    development_uses: "Use Restorative to diagnose breakdowns and lead targeted operational redesign.",
    coaching_questions: ["What problem most needs fixing?", "How will you keep the team from living only in problems?"],
  },
  {
    theme_name: "Self-Assurance",
    domain: "Influencing",
    leadership_advantages: "Projects confidence and stays steady under pressure.",
    possible_blind_spots: "Can appear overly certain or less receptive to input.",
    development_uses: "Use Self-Assurance to lead visibly in ambiguity while inviting challenge from others.",
    coaching_questions: ["Where does your confidence help the team?", "How will you make room for dissenting input?"],
  },
  {
    theme_name: "Significance",
    domain: "Influencing",
    leadership_advantages: "Wants meaningful impact and often raises the ambition of the work.",
    possible_blind_spots: "May overfocus on visibility, status, or symbolic wins.",
    development_uses: "Use Significance to connect leadership growth to larger mission and influence.",
    coaching_questions: ["What important impact are you aiming for?", "How will you keep service ahead of spotlight?"],
  },
  {
    theme_name: "Strategic",
    domain: "Strategic Thinking",
    leadership_advantages: "Sees patterns quickly and identifies viable paths forward.",
    possible_blind_spots: "May leap ahead mentally before others understand the logic.",
    development_uses: "Use Strategic to map options, tradeoffs, and next-best actions for complex leadership gaps.",
    coaching_questions: ["What paths are available?", "How will you bring others along with your thinking?"],
  },
  {
    theme_name: "Woo",
    domain: "Influencing",
    leadership_advantages: "Builds quick connections and opens doors with new people.",
    possible_blind_spots: "May prioritize breadth of contact over depth of follow-through.",
    development_uses: "Use Woo to expand influence, stakeholder access, and visibility for projects.",
    coaching_questions: ["Who do you need to win over next?", "How will you convert a first impression into trust?"],
  },
];

export const developmentProjects: DevelopmentProjectSeed[] = [
  {
    title: "Lead Structured Employee Rounding",
    description: "Lead structured employee rounding across three departments and report themes, actions, and follow-up outcomes to senior leadership.",
    difficulty: "intermediate",
    duration_days: 60,
    applicable_roles: ["VP Patient Care Services / CNO", "HR Director", "Operations Director"],
    competencies_developed: ["Relational Leader First", "Executive Presence", "Accountability"],
    strengths_leveraged: ["Developer", "Positivity", "Individualization", "Relator", "Empathy"],
    expected_outcomes: ["Visible staff engagement trends", "Clear action log", "Senior leader update"],
    mentor_questions: ["What themes are surfacing repeatedly?", "How are you showing staff that action followed listening?"],
    evidence_of_success: ["Rounding completed", "Themes summarized", "Department leaders confirm follow-through"],
  },
  {
    title: "Executive Safety Huddle Cadence",
    description: "Design and run a daily executive safety huddle for thirty days with escalation rules and accountability owners.",
    difficulty: "foundational",
    duration_days: 30,
    applicable_roles: ["VP Patient Care Services / CNO", "Operations Director"],
    competencies_developed: ["Survey/Quality Readiness", "Accountability", "Executive Presence"],
    strengths_leveraged: ["Discipline", "Responsibility", "Focus", "Command"],
    expected_outcomes: ["Standard daily huddle", "Escalation tracker", "Reduced unresolved issues"],
    mentor_questions: ["What issues keep recurring?", "How are you tightening ownership each day?"],
    evidence_of_success: ["Huddle agenda used consistently", "Owners named", "Issues closed faster"],
  },
  {
    title: "Board Quality Story Pack",
    description: "Build a concise monthly board quality story that connects key metrics, patient impact, and leadership action.",
    difficulty: "advanced",
    duration_days: 45,
    applicable_roles: ["VP Patient Care Services / CNO", "Operations Director"],
    competencies_developed: ["Strategic Thinking", "Executive Presence", "Survey/Quality Readiness"],
    strengths_leveraged: ["Analytical", "Communication", "Futuristic"],
    expected_outcomes: ["Board-ready narrative", "Simplified quality visuals", "Clear leadership recommendations"],
    mentor_questions: ["Which metrics actually matter to the board?", "What leadership action are you advocating?"],
    evidence_of_success: ["Board packet delivered", "Executive feedback positive", "Recommendations acted on"],
  },
  {
    title: "Staffing Escalation Redesign",
    description: "Map the current staffing escalation process and implement a revised workflow with triggers, roles, and communication steps.",
    difficulty: "advanced",
    duration_days: 90,
    applicable_roles: ["VP Patient Care Services / CNO", "Operations Director"],
    competencies_developed: ["Strategic Thinking", "Accountability", "Survey/Quality Readiness"],
    strengths_leveraged: ["Arranger", "Restorative", "Analytical"],
    expected_outcomes: ["Redesigned workflow", "Owner clarity", "Less confusion in urgent staffing situations"],
    mentor_questions: ["Where does the process currently break?", "How will you test the redesign under pressure?"],
    evidence_of_success: ["Workflow documented", "Leaders trained", "Escalation time improved"],
  },
  {
    title: "Manager Difficult Conversation Lab",
    description: "Create and facilitate a coaching lab for frontline managers on documentation, corrective action, and fair follow-through.",
    difficulty: "intermediate",
    duration_days: 60,
    applicable_roles: ["HR Director", "VP Patient Care Services / CNO"],
    competencies_developed: ["Accountability", "Executive Presence"],
    strengths_leveraged: ["Empathy", "Consistency", "Responsibility", "Developer"],
    expected_outcomes: ["Manager practice sessions", "Better documentation", "Clearer coaching process"],
    mentor_questions: ["What behaviors are managers avoiding?", "How are you balancing empathy with consequence?"],
    evidence_of_success: ["Managers trained", "Documentation quality improved", "Follow-through observed"],
  },
  {
    title: "Survey Tracer Sprint",
    description: "Lead a two-week mock tracer sprint across nursing, pharmacy, and ancillary departments with corrective action follow-up.",
    difficulty: "advanced",
    duration_days: 14,
    applicable_roles: ["VP Patient Care Services / CNO", "Operations Director"],
    competencies_developed: ["Survey/Quality Readiness", "Accountability"],
    strengths_leveraged: ["Deliberative", "Focus", "Restorative"],
    expected_outcomes: ["Tracer findings", "Corrective actions", "Readiness dashboard"],
    mentor_questions: ["What risks surprised you?", "Which fixes need leadership attention versus local ownership?"],
    evidence_of_success: ["Tracer completed", "Action plans assigned", "Readiness score improves"],
  },
  {
    title: "Clinic Access Improvement Project",
    description: "Lead a provider access improvement project involving clinic managers, providers, scheduling, and patient experience data.",
    difficulty: "advanced",
    duration_days: 90,
    applicable_roles: ["Director of Clinics", "Operations Director"],
    competencies_developed: ["Strategic Thinking", "Relational Leader First", "Accountability"],
    strengths_leveraged: ["Relator", "Communication", "Arranger", "Harmony"],
    expected_outcomes: ["Access bottlenecks identified", "Pilot changes launched", "Provider engagement increased"],
    mentor_questions: ["Who most influences the flow problem?", "How are you handling competing stakeholder priorities?"],
    evidence_of_success: ["Access metric improves", "Providers participate", "Changes sustained for 30 days"],
  },
  {
    title: "Monthly Financial Story for Leaders",
    description: "Build a simplified monthly financial story for department leaders that explains volume, margin, labor, and cash impact.",
    difficulty: "intermediate",
    duration_days: 60,
    applicable_roles: ["CFO", "Operations Director"],
    competencies_developed: ["Strategic Thinking", "Executive Presence"],
    strengths_leveraged: ["Analytical", "Responsibility", "Focus", "Learner"],
    expected_outcomes: ["Finance message simplified", "Operational leaders better informed", "More action on variance trends"],
    mentor_questions: ["What do leaders misunderstand most today?", "How will you turn numbers into decisions?"],
    evidence_of_success: ["Story deck used", "Leader questions improve", "Variance actions documented"],
  },
  {
    title: "Cross-Functional Throughput Redesign",
    description: "Lead a cross-functional redesign of one high-friction patient throughput process with clear owners and timelines.",
    difficulty: "advanced",
    duration_days: 75,
    applicable_roles: ["Operations Director", "VP Patient Care Services / CNO"],
    competencies_developed: ["Strategic Thinking", "Accountability", "Relational Leader First"],
    strengths_leveraged: ["Arranger", "Strategic", "Restorative"],
    expected_outcomes: ["Workflow map", "Redesigned process", "Shared ownership across functions"],
    mentor_questions: ["Where does the patient experience suffer most?", "Which handoff needs the clearest redesign?"],
    evidence_of_success: ["Process map updated", "Cycle time improves", "Teams adopt new standard work"],
  },
  {
    title: "Physician Partnership Rounds",
    description: "Launch recurring partnership rounds with physicians and clinical leaders to surface friction, trust gaps, and joint actions.",
    difficulty: "intermediate",
    duration_days: 45,
    applicable_roles: ["Director of Clinics", "VP Patient Care Services / CNO"],
    competencies_developed: ["Relational Leader First", "Executive Presence"],
    strengths_leveraged: ["Relator", "Connectedness", "Communication"],
    expected_outcomes: ["Shared issue list", "Trust-building conversations", "Joint action commitments"],
    mentor_questions: ["What patterns are physicians naming?", "How are you showing reliability between meetings?"],
    evidence_of_success: ["Rounds completed", "Issues logged", "Follow-up commitments honored"],
  },
  {
    title: "Leader Standard Work Design",
    description: "Define and test leader standard work for one senior role, including rounding, huddles, metrics, and follow-up cadence.",
    difficulty: "foundational",
    duration_days: 30,
    applicable_roles: ["VP Patient Care Services / CNO", "Operations Director", "HR Director"],
    competencies_developed: ["Accountability", "Executive Presence"],
    strengths_leveraged: ["Discipline", "Responsibility", "Consistency"],
    expected_outcomes: ["Leader routine clarified", "More consistent visibility", "Higher follow-through"],
    mentor_questions: ["Which leader behaviors need to become reliable?", "What should happen daily versus weekly?"],
    evidence_of_success: ["Standard work documented", "Cadence followed", "Team notices consistency"],
  },
  {
    title: "Budget Variance Review Cadence",
    description: "Establish a monthly variance review process with department leaders that moves from explanation to ownership.",
    difficulty: "intermediate",
    duration_days: 60,
    applicable_roles: ["CFO", "Operations Director"],
    competencies_developed: ["Accountability", "Executive Presence", "Strategic Thinking"],
    strengths_leveraged: ["Analytical", "Command", "Communication"],
    expected_outcomes: ["Clear variance process", "Action-focused reviews", "Improved accountability on spend"],
    mentor_questions: ["What excuses keep surfacing?", "How will you coach leaders into ownership rather than defense?"],
    evidence_of_success: ["Monthly reviews held", "Action items documented", "Variance trend improves"],
  },
  {
    title: "Retention Interview Program",
    description: "Stand up a retention interview process for high-value roles and synthesize themes for action.",
    difficulty: "foundational",
    duration_days: 45,
    applicable_roles: ["HR Director", "VP Patient Care Services / CNO"],
    competencies_developed: ["Relational Leader First", "Strategic Thinking"],
    strengths_leveraged: ["Empathy", "Developer", "Individualization"],
    expected_outcomes: ["Interview guide", "Retention themes", "Practical action recommendations"],
    mentor_questions: ["What would make strong people stay longer?", "How will you separate anecdote from theme?"],
    evidence_of_success: ["Interviews completed", "Themes summarized", "Actions approved by leaders"],
  },
  {
    title: "Downtime Incident Debrief",
    description: "Lead an interdisciplinary debrief after a downtime or disruption and convert lessons into readiness improvements.",
    difficulty: "intermediate",
    duration_days: 21,
    applicable_roles: ["Operations Director", "VP Patient Care Services / CNO"],
    competencies_developed: ["Survey/Quality Readiness", "Accountability", "Executive Presence"],
    strengths_leveraged: ["Restorative", "Deliberative", "Connectedness"],
    expected_outcomes: ["Incident analysis", "Corrective action plan", "Improved preparedness"],
    mentor_questions: ["What did the event reveal about system weakness?", "Which fix matters most before the next disruption?"],
    evidence_of_success: ["Debrief documented", "Actions assigned", "Readiness drill improved"],
  },
  {
    title: "Policy Cleanup Sprint",
    description: "Review one policy area with leaders and frontline staff, simplify what is unclear, and close outdated gaps.",
    difficulty: "foundational",
    duration_days: 30,
    applicable_roles: ["HR Director", "VP Patient Care Services / CNO", "Operations Director"],
    competencies_developed: ["Survey/Quality Readiness", "Accountability"],
    strengths_leveraged: ["Consistency", "Discipline", "Deliberative"],
    expected_outcomes: ["Cleaner policy language", "Gap list closed", "Better operational clarity"],
    mentor_questions: ["Where is policy confusing actual practice?", "What needs clearer ownership after revision?"],
    evidence_of_success: ["Policies revised", "Approvals completed", "Leaders confirm usability"],
  },
  {
    title: "Strategic Planning Retreat Segment",
    description: "Own and facilitate one segment of the annual strategic planning retreat with data, options, and recommendation framing.",
    difficulty: "advanced",
    duration_days: 45,
    applicable_roles: ["CFO", "Operations Director", "VP Patient Care Services / CNO"],
    competencies_developed: ["Strategic Thinking", "Executive Presence"],
    strengths_leveraged: ["Futuristic", "Strategic", "Communication"],
    expected_outcomes: ["Planning segment delivered", "Decision options clarified", "Leadership confidence increased"],
    mentor_questions: ["What decision quality do leaders need from your segment?", "How will you move from information to recommendation?"],
    evidence_of_success: ["Segment facilitated", "Feedback strong", "Recommendations carried forward"],
  },
  {
    title: "Service Recovery Review",
    description: "Review escalated service recovery cases, identify themes, and coach leaders on a stronger recovery response model.",
    difficulty: "intermediate",
    duration_days: 45,
    applicable_roles: ["VP Patient Care Services / CNO", "Director of Clinics"],
    competencies_developed: ["Relational Leader First", "Executive Presence", "Accountability"],
    strengths_leveraged: ["Empathy", "Communication", "Responsibility"],
    expected_outcomes: ["Service recovery themes", "Leader coaching points", "Improved response consistency"],
    mentor_questions: ["What do harmed experiences have in common?", "How are you coaching leaders to respond differently?"],
    evidence_of_success: ["Cases reviewed", "Coaching delivered", "Follow-up satisfaction improves"],
  },
  {
    title: "Span-of-Control Redesign",
    description: "Assess one part of the leadership structure and recommend a clearer span-of-control model with transition steps.",
    difficulty: "advanced",
    duration_days: 75,
    applicable_roles: ["HR Director", "Operations Director"],
    competencies_developed: ["Strategic Thinking", "Executive Presence", "Accountability"],
    strengths_leveraged: ["Analytical", "Arranger", "Strategic"],
    expected_outcomes: ["Structural options", "Transition recommendation", "Better decision quality for role design"],
    mentor_questions: ["Where is the current structure creating avoidable strain?", "What tradeoffs come with each option?"],
    evidence_of_success: ["Analysis completed", "Recommendation made", "Leadership team reviews decision"],
  },
  {
    title: "Succession Shadowing Plan",
    description: "Create a structured shadowing plan for a high-potential leader that includes observation, reflection, and applied stretch work.",
    difficulty: "foundational",
    duration_days: 60,
    applicable_roles: ["HR Director", "VP Patient Care Services / CNO"],
    competencies_developed: ["Relational Leader First", "Strategic Thinking"],
    strengths_leveraged: ["Developer", "Learner", "Individualization"],
    expected_outcomes: ["Shadow plan", "Reflection prompts", "Applied growth actions"],
    mentor_questions: ["What experiences will accelerate growth most?", "How will observation turn into behavior change?"],
    evidence_of_success: ["Shadowing completed", "Reflection captured", "Stretch actions taken"],
  },
  {
    title: "Community Partnership Initiative",
    description: "Lead one organization-community partnership initiative and coordinate internal and external stakeholders to execution.",
    difficulty: "advanced",
    duration_days: 90,
    applicable_roles: ["Operations Director", "VP Patient Care Services / CNO", "HR Director"],
    competencies_developed: ["Executive Presence", "Relational Leader First", "Strategic Thinking"],
    strengths_leveraged: ["Woo", "Communication", "Connectedness"],
    expected_outcomes: ["Partnership plan", "External alignment", "Visible mission impact"],
    mentor_questions: ["What matters most to the community partner?", "How are you representing the organization’s mission externally?"],
    evidence_of_success: ["Partnership launched", "Stakeholders engaged", "Mutual outcomes documented"],
  },
  {
    title: "Discharge Bottleneck Deep Dive",
    description: "Investigate one discharge bottleneck, convene stakeholders, and implement a small-cycle improvement test.",
    difficulty: "intermediate",
    duration_days: 45,
    applicable_roles: ["VP Patient Care Services / CNO", "Operations Director"],
    competencies_developed: ["Strategic Thinking", "Accountability"],
    strengths_leveraged: ["Analytical", "Restorative", "Focus"],
    expected_outcomes: ["Root-cause findings", "Pilot intervention", "Improved discharge flow"],
    mentor_questions: ["What evidence best explains the bottleneck?", "What is the smallest meaningful test you can run?"],
    evidence_of_success: ["Root causes documented", "Pilot completed", "Flow metric shifts positively"],
  },
  {
    title: "Manager Accountability Cadence",
    description: "Implement a recurring manager accountability check-in process tied to goals, follow-through, and barriers.",
    difficulty: "foundational",
    duration_days: 30,
    applicable_roles: ["HR Director", "VP Patient Care Services / CNO", "Operations Director"],
    competencies_developed: ["Accountability", "Executive Presence"],
    strengths_leveraged: ["Responsibility", "Consistency", "Command"],
    expected_outcomes: ["Regular check-ins", "Clear goals", "Improved closure on commitments"],
    mentor_questions: ["Where are managers drifting?", "How will you keep the cadence supportive and firm?"],
    evidence_of_success: ["Cadence launched", "Goals tracked", "Managers show stronger follow-through"],
  },
  {
    title: "Patient Experience Improvement Team",
    description: "Facilitate a multidisciplinary team to address one recurring patient experience issue with data and frontline input.",
    difficulty: "intermediate",
    duration_days: 60,
    applicable_roles: ["VP Patient Care Services / CNO", "Director of Clinics"],
    competencies_developed: ["Relational Leader First", "Strategic Thinking", "Accountability"],
    strengths_leveraged: ["Empathy", "Communication", "Includer"],
    expected_outcomes: ["Priority issue selected", "Improvement actions launched", "Team ownership created"],
    mentor_questions: ["What does the patient voice clearly tell you?", "How are you involving the people closest to the work?"],
    evidence_of_success: ["Team meets regularly", "Actions completed", "Experience metric improves"],
  },
  {
    title: "Cross-Campus Leader Rounds",
    description: "Coordinate leadership rounds across multiple sites and standardize the capture of themes, barriers, and commitments.",
    difficulty: "intermediate",
    duration_days: 45,
    applicable_roles: ["Operations Director", "VP Patient Care Services / CNO"],
    competencies_developed: ["Executive Presence", "Relational Leader First", "Accountability"],
    strengths_leveraged: ["Arranger", "Positivity", "Communication"],
    expected_outcomes: ["Cross-site visibility", "Shared issue patterns", "Leadership commitments logged"],
    mentor_questions: ["What differences between sites matter most?", "How are you closing the loop visibly?"],
    evidence_of_success: ["Rounds occur at all sites", "Themes consolidated", "Leaders act on findings"],
  },
  {
    title: "Multidisciplinary Quality Dashboard",
    description: "Build a practical dashboard that integrates quality, labor, patient experience, and operational indicators for leaders.",
    difficulty: "advanced",
    duration_days: 75,
    applicable_roles: ["CFO", "Operations Director", "VP Patient Care Services / CNO"],
    competencies_developed: ["Strategic Thinking", "Executive Presence", "Survey/Quality Readiness"],
    strengths_leveraged: ["Analytical", "Strategic", "Maximizer"],
    expected_outcomes: ["Integrated dashboard", "Shared metric definitions", "Faster executive review"],
    mentor_questions: ["Which measures truly influence action?", "What should the dashboard help leaders decide?"],
    evidence_of_success: ["Dashboard published", "Leaders use it", "Meetings shift toward action"],
  },
];

export const demoRole = {
  title: "VP Patient Care Services / CNO",
  department: "Nursing Administration",
  description:
    "Senior nursing and patient care leader responsible for organization-wide care quality, leader development, workforce readiness, and executive collaboration.",
  competencies: [
    {
      name: "Relational Leader First",
      definition: "Builds trust, visibility, and credibility with staff, providers, and peers before leading through change.",
      weight: 1.4,
      target_score: 4.5,
      behavioral_indicators: [
        "Rounds consistently with staff and leaders",
        "Responds to concerns with follow-through",
        "Builds trust across departments",
      ],
      red_flags: [
        "Leads from distance",
        "Fails to close loops after listening",
      ],
    },
    {
      name: "Executive Presence",
      definition: "Communicates with confidence, clarity, and steadiness in front of senior leaders and teams.",
      weight: 1.15,
      target_score: 4.25,
      behavioral_indicators: [
        "Frames issues clearly",
        "Stays composed under pressure",
        "Represents nursing credibly to executives",
      ],
      red_flags: ["Gets reactive in tense settings", "Over-explains without recommendation"],
    },
    {
      name: "Accountability",
      definition: "Sets expectations, follows through, and addresses underperformance directly and fairly.",
      weight: 1.25,
      target_score: 4.3,
      behavioral_indicators: [
        "Names clear owners and due dates",
        "Addresses hard issues directly",
        "Tracks closure on commitments",
      ],
      red_flags: ["Avoids difficult conversations", "Lets commitments drift"],
    },
    {
      name: "Strategic Thinking",
      definition: "Connects operations, people, and quality outcomes into a forward-looking leadership plan.",
      weight: 1.3,
      target_score: 4.2,
      behavioral_indicators: [
        "Connects data to action",
        "Anticipates downstream impact",
        "Prioritizes role-critical work",
      ],
      red_flags: ["Stays tactical only", "Struggles to connect patterns"],
    },
    {
      name: "Survey/Quality Readiness",
      definition: "Leads quality readiness with disciplined systems, visible standards, and rapid follow-through.",
      weight: 1.2,
      target_score: 4.35,
      behavioral_indicators: [
        "Uses tracers and audits well",
        "Translates findings into actions",
        "Builds readiness habits with leaders",
      ],
      red_flags: ["Treats readiness as episodic", "Findings repeat without ownership"],
    },
  ],
};

export const demoInterviewQuestions = [
  {
    competency_name: "Relational Leader First",
    question: "Tell us about a time you rebuilt trust with a staff group that felt unheard or disconnected.",
    scoring_rubric: {
      validates: "Trust building and visible follow-through",
      strong_answer_indicators: ["Names specific listening actions", "Shows follow-up", "Explains outcome"],
      weak_answer_indicators: ["Stays generic", "Shows no follow-through", "Blames staff"],
    },
  },
  {
    competency_name: "Relational Leader First",
    question: "Describe how you have built credibility with leaders outside your own department.",
    scoring_rubric: {
      validates: "Cross-functional relationship building",
      strong_answer_indicators: ["Gives examples across departments", "Shows partnership", "Explains trust gained"],
      weak_answer_indicators: ["Only references own team", "No evidence of influence across functions"],
    },
  },
  {
    competency_name: "Executive Presence",
    question: "Describe a time you had to present a difficult issue to senior leadership and recommend a path forward.",
    scoring_rubric: {
      validates: "Clarity, confidence, and recommendation framing",
      strong_answer_indicators: ["Frames issue clearly", "Uses evidence", "Makes a recommendation"],
      weak_answer_indicators: ["Rambling explanation", "No recommendation", "Reactive tone"],
    },
  },
  {
    competency_name: "Executive Presence",
    question: "Tell us about a moment when you had to stay composed while others were under pressure or frustrated.",
    scoring_rubric: {
      validates: "Composure and leadership steadiness",
      strong_answer_indicators: ["Shows calm", "Helps others stabilize", "Moves toward action"],
      weak_answer_indicators: ["Escalates tension", "Avoids action"],
    },
  },
  {
    competency_name: "Accountability",
    question: "Share a time when you had to hold a respected leader accountable for missing an important expectation.",
    scoring_rubric: {
      validates: "Direct accountability and fairness",
      strong_answer_indicators: ["Uses direct conversation", "Clarifies expectations", "Follows through"],
      weak_answer_indicators: ["Avoids issue", "Uses vague expectations", "No closure"],
    },
  },
  {
    competency_name: "Accountability",
    question: "Describe a time when you inherited a project with unclear ownership and had to regain control.",
    scoring_rubric: {
      validates: "Ownership and follow-through",
      strong_answer_indicators: ["Clarifies owners", "Sets cadence", "Drives closure"],
      weak_answer_indicators: ["Leaves ambiguity in place", "No monitoring process"],
    },
  },
  {
    competency_name: "Strategic Thinking",
    question: "Tell us about a time you connected operational data to a larger leadership decision.",
    scoring_rubric: {
      validates: "Pattern recognition and strategic framing",
      strong_answer_indicators: ["Uses data clearly", "Connects to bigger decision", "Shows impact"],
      weak_answer_indicators: ["Reports data only", "No strategic connection"],
    },
  },
  {
    competency_name: "Strategic Thinking",
    question: "Describe a situation where you had to choose among several good options with competing tradeoffs.",
    scoring_rubric: {
      validates: "Prioritization and decision quality",
      strong_answer_indicators: ["Names tradeoffs", "Explains reasoning", "Shows outcome"],
      weak_answer_indicators: ["No clear criteria", "Decision feels arbitrary"],
    },
  },
  {
    competency_name: "Survey/Quality Readiness",
    question: "Walk us through a time you prepared an area for survey, tracer, or regulatory review.",
    scoring_rubric: {
      validates: "Quality readiness systems and follow-through",
      strong_answer_indicators: ["Uses structured readiness methods", "Creates action plans", "Monitors closure"],
      weak_answer_indicators: ["Describes last-minute scramble", "No sustained process"],
    },
  },
  {
    competency_name: "Survey/Quality Readiness",
    question: "Describe how you responded when a quality or readiness issue repeated after it was supposedly fixed.",
    scoring_rubric: {
      validates: "Root-cause thinking and accountability",
      strong_answer_indicators: ["Reassesses root cause", "Changes system", "Names accountability"],
      weak_answer_indicators: ["Blames staff only", "No system correction"],
    },
  },
];

export const demoCandidateRanking = [
  "Developer",
  "Positivity",
  "Individualization",
  "Relator",
  "Empathy",
  "Responsibility",
  "Arranger",
  "Communication",
  "Learner",
  "Connectedness",
  "Adaptability",
  "Achiever",
  "Harmony",
  "Input",
  "Strategic",
  "Discipline",
  "Focus",
  "Includer",
  "Analytical",
  "Belief",
  "Restorative",
  "Futuristic",
  "Consistency",
  "Intellection",
  "Woo",
  "Ideation",
  "Deliberative",
  "Command",
  "Significance",
  "Self-Assurance",
  "Activator",
  "Competition",
  "Context",
  "Maximizer",
];

export const demoInterviewScores = [
  {
    competency_name: "Relational Leader First",
    score_numeric: 4.4,
    evidence_notes: "Demonstrated strong staff connection, visible rounding habits, and specific examples of rebuilding trust.",
    concern_notes: "Needs more cross-entity exposure beyond current service line.",
  },
  {
    competency_name: "Executive Presence",
    score_numeric: 3.8,
    evidence_notes: "Communicates clearly and warmly, especially in one-on-one settings.",
    concern_notes: "Needs sharper recommendation framing in executive-level conversations.",
  },
  {
    competency_name: "Accountability",
    score_numeric: 3.6,
    evidence_notes: "Owns commitments and is reliable with follow-up.",
    concern_notes: "Shows hesitation in harder performance-management conversations.",
  },
  {
    competency_name: "Strategic Thinking",
    score_numeric: 3.5,
    evidence_notes: "Sees people and culture patterns well and learns quickly.",
    concern_notes: "Needs stronger habit of connecting operational data to longer-range decisions.",
  },
  {
    competency_name: "Survey/Quality Readiness",
    score_numeric: 3.7,
    evidence_notes: "Understands frontline quality behaviors and patient care expectations.",
    concern_notes: "Would benefit from more disciplined systems-level readiness leadership.",
  },
];
