const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
function setup({email='owner@example.invalid',role='hospital_admin',old=false,sandbox=false}={}){
 const calls=[]; const affiliate={id:'11111111-1111-4111-8111-111111111111',name:'Partner',is_sandbox:sandbox,payout_email:'owner@example.invalid',payout_country:'US'};
 const account={account_id:null,requested_at:new Date(Date.now()-(old?25*3600000:0)).toISOString()};
 const admin={from(table){const q={select:()=>q,eq:()=>q,limit:()=>q,update:v=>{calls.push({update:v});return q;},upsert:()=>q,maybeSingle:async()=>({data:table==='affiliates'?affiliate:account}),single:async()=>({data:table==='affiliates'?affiliate:account})};return q;}};
 class ApiRouteError extends Error{constructor(m,s){super(m);this.status=s;}}
 const stripe={accounts:{create:async(params,options)=>{calls.push({create:params,key:options.idempotencyKey});return{id:'acct_test'};}},accountLinks:{create:async params=>{calls.push({link:params});return{url:'https://connect.stripe.com/setup/test'};}}};
 const imports={'next/server':{NextResponse:{json:body=>({status:200,body})}},'@/lib/supabase/server':{createSupabaseServerClient:async()=>({auth:{getUser:async()=>({data:{user:email?{email,email_confirmed_at:'2026-01-01'}:null}})}})},'@/lib/supabase/admin':{createSupabaseAdminClient:()=>admin},'@/lib/api-route':{ApiRouteError,createApiErrorResponse:e=>({status:e.status||500}),requireApiWorkspaceProfile:async()=>({profile:{role}})},'@/lib/stripe-billing':{getStripe:()=>stripe,getStripeBillingReturnUrl:p=>'https://example.invalid'+p},'@/lib/affiliate-stripe':{getAffiliateStripe:mode=>{calls.push({sandbox:mode});return stripe;}},'@/lib/affiliate-sandbox':{reconcileSandboxAffiliate:async()=>0},'@/lib/affiliate-commerce':{recordAffiliateInvoice:async()=>{}}};
 const mod={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync('src/app/api/affiliates/connect/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>imports[n]||require(n),mod,mod.exports);
 return{calls,run:()=>mod.exports.POST({json:async()=>({affiliateId:affiliate.id,action:'onboard'})})};
}
process.env.STRIPE_SECRET_KEY='sk_test_placeholder';
test('only verified designated contact may create a connected account',async()=>{for(const options of [{email:null},{email:'other@example.invalid'},{email:'admin@example.invalid',role:'system_admin'}]){const t=setup(options);assert.ok([401,403].includes((await t.run()).status));assert.equal(t.calls.some(c=>c.create),false);}});
test('owner onboarding uses stable idempotency and fixed return paths',async()=>{const t=setup();assert.equal((await t.run()).status,200);const create=t.calls.find(c=>c.create);assert.equal(create.create.email,'owner@example.invalid');assert.match(create.key,/affiliate-connect-.*-true/);assert.equal(t.calls.find(c=>c.link).link.account,'acct_test');});
test('uncertain account creation older than Stripe idempotency window cannot retry',async()=>{const t=setup({old:true});assert.equal((await t.run()).status,409);assert.equal(t.calls.some(c=>c.create),false);});

test('sandbox onboarding requires a platform admin and explicitly chooses test mode',async()=>{const denied=setup({sandbox:true});assert.equal((await denied.run()).status,403);assert.equal(denied.calls.some(c=>c.create),false);const allowed=setup({sandbox:true,role:'system_admin',email:'admin@example.invalid'});assert.equal((await allowed.run()).status,200);assert.equal(allowed.calls.find(c=>'sandbox' in c).sandbox,true);assert.equal(allowed.calls.find(c=>c.create).create.email,undefined);assert.match(allowed.calls.find(c=>c.create).key,/-false$/);});
