'use client';
import { useState } from 'react';
import type { DevelopmentData } from '@/lib/development-intelligence';
export function DevelopmentMap({ data }: {
    data: DevelopmentData;
}) {
    const [method, setMethod] = useState('all');
    const needs = data.needs ?? [], plans = data.plans ?? [], evidence = data.evidence ?? [];
    return <section className="rounded-3xl border border-teal-100 bg-teal-50/50 p-6"><h2 className="text-xl font-semibold text-teal-950">Development ecosystem</h2><p className="mt-2">{String(data.candidate?.target_role ?? 'Target role not selected')} → Competencies → Development → Evidence → Human review</p><label className="mt-5 block text-sm font-medium">Explore a development method<select className="ml-3 rounded-xl border bg-white p-2" value={method} onChange={e => setMethod(e.target.value)}>{['all', 'coaching', 'mentoring', 'project', 'training', 'experience', 'assessment', 'self_development'].map(m => <option key={m}>{m}</option>)}</select></label><div className="mt-5 grid gap-4 md:grid-cols-2">{needs.filter(n => method === 'all' || plans.some(p => p.development_need_id === n.id && p.method === method) || Array.isArray(n.recommended_response) && n.recommended_response.includes(method)).map(n => <details key={n.id} className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-semibold text-teal-900">{String(n.title)} <span className="ml-2 text-xs font-normal">{String(n.status)}</span></summary><p className="mt-3 text-sm">{String(n.description)}</p><h3 className="mt-4 font-medium">Linked development activities</h3>{plans.filter(p => p.development_need_id === n.id).map(p => <p key={p.id} className="mt-2 rounded-lg bg-slate-50 p-2 text-sm">{String(p.method)} → {String(p.title)} · {String(p.status)}</p>)}<h3 className="mt-4 font-medium">Evidence</h3>{evidence.filter(e => e.development_need_id === n.id).map(e => <p key={e.id} className="mt-2 text-sm">{String(e.evidence_date)} · {String(e.title)} · {String(e.visibility).replaceAll('_', ' ')}</p>)}{!evidence.some(e => e.development_need_id === n.id) && <p className="mt-2 text-sm text-slate-500">No evidence recorded for this need.</p>}<p className="mt-4 text-xs text-slate-500">Evidence informs a human readiness review. Development activity does not automatically change readiness.</p></details>)}</div>{!needs.length && <p className="mt-5 text-slate-500">Review available assessments to identify development needs.</p>}</section>;
}
