import Link from 'next/link';
import { randomUUID } from 'node:crypto';
import { coachingContext, rpc } from '@/lib/coaching/server';
import { competencyRows, recommendedMethods, text, methods, type DevelopmentData, type DevelopmentRow } from '@/lib/development-intelligence';
import { Panel, Field, Select } from '@/components/coaching/ui';
import { CoachingForm } from '@/components/coaching/form';
import { DevelopmentForm } from './form';
import { DevelopmentMap } from './map';
const options = (rows: DevelopmentRow[], label = 'title') => rows.map(r => ({ value: r.id, label: text(r, label) || r.id }));
const list = (data: DevelopmentData, key: keyof DevelopmentData) => Array.isArray(data[key]) ? data[key] as DevelopmentRow[] : [];
function EvidenceChoices({ evidence }: {
    evidence: DevelopmentRow[];
}) { return <fieldset className="grid gap-2"><legend className="mb-2 font-medium">Supporting evidence</legend>{evidence.map(e => <label key={e.id} className="text-sm"><input type="checkbox" name="evidence_ids" value={e.id} className="mr-2"/>{text(e, 'title')} · {text(e, 'verification_status').replaceAll('_', ' ')}</label>)}</fieldset>; }
export async function DevelopmentWorkspace({ candidate, view = 'priorities', competency }: {
    candidate: string;
    view?: string;
    competency?: string;
}) { return <main className="app-page"><div className="mx-auto flex max-w-[1380px] flex-col gap-6 px-5 py-10 sm:px-10"><header><p className="text-sm font-semibold uppercase tracking-widest text-teal-700">Leader Continuity</p><h1 className="mt-2 text-3xl font-semibold text-teal-950">Development Intelligence</h1></header>{await DevelopmentBody({ candidate, view, competency })}</div></main>; }
export async function DevelopmentBody({ candidate, engagement, view = 'priorities', competency }: {
    candidate?: string;
    engagement?: string;
    view?: string;
    competency?: string;
}) {
    const ctx = await coachingContext();
    const d = await rpc<DevelopmentData>(ctx.db, 'development_intelligence_read', { candidate: candidate ?? null, engagement: engagement ?? null });
    const cid = d.candidate!.id;
    const hidden = { candidate_id: cid, ...(engagement ? { engagement_id: engagement } : {}) };
    const needs = list(d, 'needs'), sources = list(d, 'sources'), evidence = list(d, 'evidence').filter(e => !competency || e.competency_id === competency);
    const team = d.admin || d.self || d.mentor;
    const selected = competencyRows(sources);
    const readiness = d.current_readiness;
    const grants = engagement && ctx.user.id ? (await ctx.db.from('coaching_data_permissions').select('id,data_id,data_type,revoked_at').eq('engagement_id', engagement)).data ?? [] : [];
    const available = engagement && d.self ? await rpc<DevelopmentRow[]>(ctx.db, 'coaching_development', { eid: engagement, available: true }) : [];
    return <><Panel title={text(d.candidate!, 'name')}><p className="text-lg text-teal-900">Target role: {text(d.candidate!, 'target_role') || 'Not selected or not shared'}</p><p className="mt-2 text-sm text-slate-600">System suggestions support development. Authorized human leaders retain readiness and succession decisions.</p><nav className="mt-5 flex flex-wrap gap-4 text-sm font-semibold">{team && [['development-intelligence', 'Development priorities'], ['development', 'My development'], ['readiness-review', 'Readiness review']].map(([route, label]) => <Link className="text-teal-800 underline" key={route} href={`/candidates/${cid}/${route}`}>{label}</Link>)}{engagement && <Link className="text-teal-800 underline" href={`/coaching/clients/${engagement}`}>Coaching engagement</Link>}<Link className="text-teal-800 underline" href="/coaching/marketplace">Explore coaches</Link></nav></Panel>
 {engagement && d.self && <Panel title="Information Shared With My Coach"><p className="mb-4">Select individual records. Development Data Access consent is also required. Revoking either consent or a record stops access; it does not automatically publish evidence.</p><div className="grid gap-3 md:grid-cols-2">{available.map((s, i) => { const p = grants.find(p => p.data_id === s.id && p.data_type === s.data_type && !p.revoked_at); return <div key={`${s.id}-${s.data_type}-${i}`} className="rounded-xl border p-4"><p className="font-medium">{text(s, 'title')}</p><p className="mb-3 text-xs uppercase text-slate-500">{text(s, 'data_type').replaceAll('_', ' ')} · {p ? 'Selected for coach' : 'Not shared'}</p><CoachingForm operation="data_permission" hidden={{ engagement_id: engagement, ...(p ? { id: p.id, revoke: 'true' } : { data_id: s.id, data_type: text(s, 'data_type') }) }} button={p ? 'Stop sharing' : 'Share with coach'}/></div>; })}</div></Panel>}
 {view === 'portfolio' && <DevelopmentMap data={d}/>}
 {view === 'readiness' ? <><Panel title="Readiness evidence review"><p className="text-sm font-semibold uppercase text-teal-700">System recommendation</p><p className="mt-2 text-lg">{d.system_recommendation}</p><p className="mt-3">Evidence confidence: <strong>{d.evidence_confidence}</strong></p><p className="mt-2 text-sm text-slate-500">This configurable indicator describes evidence coverage, not candidate quality or the probability of success.</p><p className="mt-5">Latest human record: {readiness ? `${String(readiness.match_status).replaceAll('_', ' ')} · Role-goal score ${readiness.readiness_score ?? 'not recorded'} / 100` : 'No human readiness record'}</p></Panel>{d.admin && <Panel title="Human review"><p className="mb-4">Uses Leader Continuity’s existing role-match status and 0–100 role-goal score. This does not select a promotion or alter assessment results.</p><DevelopmentForm operation="readiness" hidden={hidden} button="Record human review"><Select name="match_status" label="Existing role-match decision" options={['match', 'not_yet', 'not_recommended']} empty="Select your decision"/><Field name="readiness_score" label="Recorded role-goal score (0–100; optional)" type="number" value={readiness?.readiness_score as number | undefined}/><Field name="reason" label="Reason for change or retaining current readiness" type="textarea" required/><EvidenceChoices evidence={evidence.filter(e => e.visibility === 'readiness_review')}/></DevelopmentForm></Panel>}<Panel title="Readiness history">{list(d, 'readiness_history').map(h => <article key={h.id} className="mb-4 border-b pb-4"><p>{text(h, 'changed_at').slice(0, 10)} · {text(h, 'previous_readiness') || 'Not recorded'} → {text(h, 'new_readiness') || 'Not recorded'}</p><p className="mt-2">{text(h, 'reason')}</p></article>)}</Panel></> : view !== 'evidence' && <><Panel title="Development priorities">{d.admin && <DevelopmentForm operation="analyze" hidden={hidden} button="Identify needs from existing assessments"/>}<p className="my-4 text-sm text-slate-600">Scores use the latest dated completed panel, mentor-reviewed development score, or released 360 aggregate. Strengths preferences are not treated as observed performance. No score is invented for missing data.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Competency', 'Current', 'Target', 'Gap', 'Evidence condition'].map(h => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{selected.map(s => <tr key={s.id} className="border-t"><td className="p-3"><Link className="text-teal-800 underline" href={`/candidates/${cid}/competencies/${s.id}/evidence`}>{text(s, 'title')}</Link></td><td className="p-3">{s.current ?? 'Not assessed'}</td><td className="p-3">{s.target ?? 'Not recorded'}</td><td className="p-3">{s.gap ?? '—'}</td><td className="p-3">{s.status}</td></tr>)}</tbody></table></div>{!selected.length && <p>No competencies are selected or shared.</p>}</Panel>
 {needs.map(n => <Panel key={n.id} title={text(n, 'title')}><p className="text-sm font-medium uppercase text-teal-700">{text(n, 'priority')} priority · {text(n, 'status')} · {n.baseline_level == null ? 'Baseline not established' : `Baseline ${n.baseline_level} / 5`}</p><p className="my-3">{text(n, 'description')}</p><details className="mb-5"><summary className="cursor-pointer font-medium text-teal-800">Why? View authorized evidence sources</summary>{sources.filter(s => s.id === n.source_id || s.id === n.competency_id).map((s, i) => <p key={i} className="mt-2 text-sm">{text(s, 'data_type')} · {text(s, 'title')} · {text(s, 'description')}</p>)}</details>{list(d, 'recommendations').filter(r => r.development_need_id === n.id).map(r => { const rec = r.recommendation_data as Record<string, unknown>; const recommended = recommendedMethods(r); return <div className="my-4 rounded-2xl bg-teal-50 p-4" key={r.id}><p className="text-xs font-semibold uppercase text-teal-700">System recommendation · {text(r, 'model_version')} · {text(r, 'status')}</p><h3 className="mt-2 text-lg font-semibold">{recommended.includes('coaching') ? 'Professional Coaching Recommended' : 'Suggested development approach'}</h3><p className="mt-2">{recommended.join(' + ') || 'Review evidence before choosing a method'}</p><p className="mt-2">{text(r, 'rationale')}</p><p className="mt-2">Suggested focus: {String((r.reviewed_data as Record<string, unknown>)?.focus ?? rec.focus)}</p>{recommended.includes('coaching') && <p className="mt-2 text-sm">Suggested 3–6 months · 6–12 sessions. Confirm scope with the organization and coach.</p>}{team && <details className="mt-4"><summary className="mb-3 cursor-pointer font-medium">Review or modify recommendation</summary><DevelopmentForm operation="recommendation" hidden={{ id: r.id }}><Select name="status" options={['accepted', 'modified', 'dismissed', 'completed']}/><Field name="focus" type="textarea" label="Modified focus (required when modifying)"/></DevelopmentForm></details>}</div>; })}<div className="mt-4 flex flex-wrap gap-4">{Array.isArray(n.recommended_response) && n.recommended_response.includes('coaching') && (d.coaching_active && d.admin ? <DevelopmentForm operation="coaching_request" hidden={{ ...hidden, development_need_id: n.id }} button="Find a Coach for This Development Need"/> : <p className="text-sm">{d.coaching_active ? 'Your organization administrator can start a coaching request.' : 'Activate Professional Coaching to receive coach matches and begin an engagement.'} <Link className="text-teal-800 underline" href="/coaching/marketplace">Explore coaches</Link></p>)}</div>{team && <details className="mt-4"><summary className="mb-3 cursor-pointer">Update need status</summary><DevelopmentForm operation="need_status" hidden={{ ...hidden, development_need_id: n.id }}><Select name="status" options={['identified', 'accepted', 'active', 'resolved', 'dismissed']}/></DevelopmentForm></details>}</Panel>)}</>}
 {view === 'evidence' || view === 'readiness' ? null : team && <Panel title="Identify a development need"><DevelopmentForm operation="need" hidden={{ ...hidden, request_key: randomUUID() }}><Select name="competency_id" options={options(sources.filter(s => s.data_type === 'competencies'))} empty="General development need"/><Field name="title" required/><Field name="description" label="Observed need and source explanation" type="textarea" required/><Select name="source_type" options={['leader_input', 'self_assessment', 'mentor_observation', 'other']}/><Field name="need_type" label="Need type (matches configured method rules)" value="competency_gap" required/><Select name="gap_severity" options={['minor', 'moderate', 'significant', 'critical']} empty="Not assessed"/><Select name="priority" options={['low', 'moderate', 'high', 'urgent']} value="moderate"/><Field name="baseline_level" label="Observed baseline (1–5; leave blank if unavailable)" type="number"/><Field name="target_level" label="Target (1–5; optional)" type="number"/></DevelopmentForm></Panel>}
 {view !== 'readiness' && view !== 'evidence' && team && <Panel title="Build development plan"><p className="mb-4">Connect existing projects, training and mentoring. This creates a plan step referencing those records, not a duplicate activity.</p><DevelopmentForm operation="plan" hidden={hidden}><Select name="development_need_id" options={options(needs)}/><Select name="method" options={methods}/><Field name="title" label="Goal" required/><Field name="activity" label="Development activity" type="textarea" required/><Select name="owner_user_id" label="Plan owner" options={options(list(d, "owners"), "name")} empty="Assign later"/><Field name="target_date" type="date"/><Field name="review_date" type="date"/><Field name="evidence_required" type="textarea" required/>{[['development_plan', 'development_record_id', 'Existing development record'], ['project', 'project_assignment_id', 'Existing project assignment'], ['training', 'training_selection_id', 'Existing training selection'], ['mentor_plan', 'mentor_assignment_id', 'Existing mentor assignment']].map(([kind, name, label]) => <Select key={name} name={name} label={label} options={options(sources.filter(s => s.data_type === kind))} empty="No linked record"/>)}</DevelopmentForm><div className="mt-5">{list(d, 'plans').map(p => <div className="mb-4 border-t pt-4" key={p.id}><p className="font-medium">{text(p, 'title')} · {text(p, 'method')} · {text(p, 'status')}</p><p className="my-2">{text(p, 'activity')}</p><p className="mb-3 text-sm">Evidence required: {text(p, 'evidence_required')} · Review: {text(p, 'review_date') || 'Not scheduled'}</p><DevelopmentForm operation="plan_status" hidden={{ ...hidden, id: p.id }}><Select name="status" options={['planned', 'active', 'completed', 'cancelled']} value={text(p, 'status')}/></DevelopmentForm></div>)}</div></Panel>}
 {engagement && d.participant && <><Panel title="Coaching focus areas"><DevelopmentForm operation="focus" hidden={hidden}><Select name="development_need_id" options={options(needs)}/><Field name="title" required/><Field name="description" type="textarea"/></DevelopmentForm>{list(d, 'focus').map(f => <p key={f.id} className="mt-4">{text(f, 'title')} · {f.baseline_level == null ? 'Baseline not established' : `Baseline ${f.baseline_level}`} → {String(f.target_level ?? 'Target not established')}</p>)}</Panel>{ctx.coach && <Panel title="Connect a coaching goal"><DevelopmentForm operation="link_goal" hidden={hidden}><Select name="focus_area_id" options={options(list(d, 'focus'))}/><Select name="goal_id" options={options(list(d, 'goals'))}/></DevelopmentForm></Panel>}</>}
 <Panel title={competency ? 'Competency evidence timeline' : 'Development evidence'}><p className="mb-4 text-sm">Private to me · Shared with coach · Shared with organization · Used for readiness review. Only records you may access appear here.</p>{evidence.map(ev => <article key={ev.id} className="mb-5 rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{text(ev, 'title')}</h3><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{text(ev, 'visibility').replaceAll('_', ' ')}</span></div><p className="mt-2 text-xs uppercase text-slate-500">{text(ev, 'evidence_date')} · {text(ev, 'verification_status').replaceAll('_', ' ')} · Weight {text(ev, 'evidence_weight')} ({text(ev, 'scoring_version')})</p><p className="my-3 whitespace-pre-wrap">{text(ev, 'description')}</p>{(ev.source_user_id === ctx.user.id && !ev.coaching_engagement_id || d.self && ev.coaching_engagement_id) && <details className="mt-3"><summary className="mb-3 cursor-pointer">Change evidence sharing</summary><DevelopmentForm operation="evidence_share" hidden={{ id: ev.id }} button="Apply sharing choice"><Select name="visibility" options={ev.coaching_engagement_id ? ['coach_client', 'organization', 'readiness_review'] : ['private', 'organization', 'readiness_review']} value={text(ev, 'visibility')}/></DevelopmentForm></details>}{(d.admin || d.mentor || ctx.coach) && ev.source_user_id !== ctx.user.id && <div className="mt-3"><DevelopmentForm operation="evidence_verify" hidden={{ id: ev.id }} button="Confirm this evidence"/></div>}</article>)}{!evidence.length && <p className="text-slate-500">No authorized evidence recorded.</p>}</Panel>
 {view !== 'readiness' && (team || d.participant) && <Panel title={engagement ? 'Share Development Milestone' : 'Record development evidence'}><p className="mb-4">Create a separate factual record. Coaching notes are never imported. {engagement ? 'This starts shared only between coach and client. The client must approve organization/readiness sharing.' : 'New evidence starts private to you.'}</p><DevelopmentForm operation="evidence" hidden={{ ...hidden, request_key: randomUUID() }}><Select name="development_need_id" options={options(needs)} empty="No linked need"/><Select name="competency_id" options={options(sources.filter(s => s.data_type === 'competencies'))} empty="No linked competency"/>{engagement && <Select name="coaching_goal_id" options={options(list(d, 'goals'))} empty="No linked goal"/>}<Select name="evidence_type" options={engagement && ctx.coach ? ['coach_shared_milestone', 'behavior_demonstrated', 'presentation_delivered', 'other'] : ['presentation_delivered', 'project_completed', 'training_completed', 'manager_observation', 'mentor_observation', 'assignment_completed', 'certification', 'document', 'other']}/><Field name="title" required/><Field name="description" label="Observed evidence; exclude confidential discussions" type="textarea" required/><Field name="evidence_date" type="date" required/>{[["project", "project_assignment_id"], ["training", "training_selection_id"], ["mentor_plan", "mentor_assignment_id"], ["development_plan", "development_record_id"]].map(([kind, name]) => <Select key={name} name={name} options={options(sources.filter(s => s.data_type === kind))} empty="No linked activity"/>)}</DevelopmentForm></Panel>}
 {view !== 'readiness' && view !== 'evidence' && <><Panel title="Development progress review"><p className="mb-4 text-sm">Coaching reviews start shared with coach and client. Reviews outside coaching are shared with the candidate’s authorized development team.</p><DevelopmentForm operation="progress" hidden={hidden}><Select name="development_need_id" options={options(needs)}/><Select name="review_type" options={['30_day', '60_day', '90_day', 'midpoint', 'closeout', 'custom']}/><Field name="current_level" label="Observed current level (1–5; optional)" type="number"/><Select name="progress_status" options={['not_started', 'early_progress', 'progressing', 'significant_progress', 'target_achieved', 'needs_attention', 'insufficient_evidence']}/><Field name="evidence_summary" type="textarea" required/><EvidenceChoices evidence={evidence}/></DevelopmentForm>{list(d, 'reviews').map(r => <div className="mt-4" key={r.id}><p>{text(r, 'reviewed_at').slice(0, 10)} · {text(r, 'progress_status').replaceAll('_', ' ')} · {text(r, 'evidence_summary')}</p>{d.self && engagement && r.engagement_id === engagement && <DevelopmentForm operation="progress_share" hidden={{ ...hidden, id: r.id }} button="Apply review sharing"><Select name="visibility" options={['coach_client', 'organization', 'readiness_review']} value={text(r, 'visibility')}/></DevelopmentForm>}</div>)}</Panel>{engagement && d.participant && <Panel title="Coaching outcome measurement"><DevelopmentForm operation="outcome" hidden={hidden}><Select name="development_need_id" options={options(needs)} empty="No linked need"/><Select name="measure_type" options={['competency_rating', '360_rating', 'goal_completion', 'project_completion', 'behavior_frequency', 'stakeholder_feedback', 'self_assessment', 'manager_assessment', 'custom']}/><Field name="baseline_value" label="Baseline (blank if not established)"/><Field name="target_value"/><Field name="final_value"/><Field name="baseline_text"/><Field name="target_text"/><Field name="final_text"/><Field name="measurement_source" required/><Select name="evidence_id" options={options(evidence)} empty="No supporting evidence"/></DevelopmentForm>{list(d, 'outcomes').map(o => <div key={o.id} className="mt-4"><p>{text(o, 'measure_type')} · Baseline {String(o.baseline_value ?? 'not established')} → {String(o.final_value ?? 'not recorded')} · {text(o, 'measurement_source')}</p>{d.self && <DevelopmentForm operation="outcome_share" hidden={{ ...hidden, id: o.id }} button="Apply outcome sharing"><Select name="visibility" options={['coach_client', 'organization', 'readiness_review']} value={text(o, 'visibility')}/></DevelopmentForm>}</div>)}</Panel>}</>}
 </>;
}
