'use client';

import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useState,type ReactNode} from 'react';
import {Panel} from '@/components/coaching/ui';
import {previewHref,roleLabels,rolePages,sampleIdentity,type PreviewRole} from '@/lib/platform-preview/model';

const buttonClass='interactive-contrast rounded-full bg-teal-950 px-4 py-2 text-sm font-semibold text-white hover:bg-teal-800';
const inputClass='w-full rounded-xl border border-slate-300 bg-white p-3 text-sm';
const initialActions=[{title:'Lead a cross-functional planning conversation',due:'Before your next session',done:false},{title:'Ask two colleagues for feedback on delegation',due:'This week',done:false},{title:'Record a reflection on the last team meeting',due:'Before your mentor review',done:true}];
function Badge({children}:{children:ReactNode}){return <span className="inline-block rounded-full bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-800">{children}</span>;}
function Table({head,rows}:{head:string[];rows:ReactNode[][]}){return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{head.map(h=><th key={h} className="border-b border-slate-200 p-3 font-semibold text-slate-600">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-b border-slate-100 last:border-0">{row.map((cell,j)=><td className="p-3 align-top" key={j}>{cell}</td>)}</tr>)}</tbody></table></div>;}
function Metrics({items}:{items:[string,string][]}){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{items.map(([label,value])=><Panel key={label}><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-3xl font-semibold text-teal-950">{value}</p></Panel>)}</div>;}

export function PreviewWorkspace({role,section,company,person}:{role:PreviewRole;section:string;company:string;person:string}){
 const query=useSearchParams();
 const identity=sampleIdentity(role,company,person),org=identity.company;
 const leader=identity.leader,coach=org.coach,mentor=org.mentor;
 const page=rolePages[role].find(p=>p.id===section)!;
 const href=(id:string)=>previewHref(role,id,{company,person,returnTo:query.get('returnTo')});
 const [actions,setActions]=useState(initialActions);
 const [notice,setNotice]=useState('');
 const [detail,setDetail]=useState<string|null>(null);
 const [goal,setGoal]=useState('Delegate decisions with clear ownership and follow-up.');
 const [notes,setNotes]=useState<{text:string;visibility:string}[]>([]);
 const [sharing,setSharing]=useState({goals:true,development:true,organization:false});
 const [requestStatus,setRequestStatus]=useState('Awaiting your review');
 const [sessionStatus,setSessionStatus]=useState('Scheduled');
 const save=(message:string)=>setNotice(`${message} in this sample workspace. Nothing was sent or saved to live records.`);
 const learningActions=<div className="grid gap-3">{actions.map((action,index)=><label key={action.title} className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4"><input type="checkbox" checked={action.done} onChange={()=>{setActions(actions.map((a,i)=>i===index?{...a,done:!a.done}:a));save('Action updated');}} className="mt-1 h-4 w-4"/><span><span className={`block font-medium ${action.done?'text-slate-500 line-through':'text-teal-950'}`}>{action.title}</span><span className="mt-1 block text-xs text-slate-500">{action.due}</span></span></label>)}</div>;
 const engagement=<Panel title={role==='company-admin'?'Leadership coaching engagement':'Coaching engagement'}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-teal-950">Leadership confidence & delegation</h3><p className="mt-2 text-sm text-slate-600">{leader} · Coach: {coach} · {org.shortName}</p></div><Badge>Active · Session 3 of 6</Badge></div><div className="mt-5 grid gap-4 sm:grid-cols-3">{[['Development focus','Delegation and leadership communication'],['Agreed outcome','Clearer decision ownership within the team'],['Shared progress','On track']].map(([label,value])=><div key={label}><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-sm">{value}</p></div>)}</div></Panel>;
 const noteForm=<form className="grid gap-3" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);setNotes([...notes,{text:String(data.get('note')),visibility:String(data.get('visibility')??'Shared with coach')}]);e.currentTarget.reset();save('Note added');}}><label className="grid gap-1 text-sm font-medium">{role==='coach'?'Coaching note':'Your preparation or reflection'}<textarea name="note" required rows={4} className={inputClass} placeholder="Try an example note…"/></label>{role==='coach'&&<label className="grid gap-1 text-sm font-medium">Visibility<select className={inputClass} name="visibility"><option>Coach private</option><option>Shared with client</option></select></label>}<button className={`${buttonClass} justify-self-start`}>Add sample note</button></form>;
 let content:ReactNode;
 switch(section){
 case 'home': {
  const metrics:[string,string][]=role==='company-admin'?[['Leaders in development','2'],['Active mentors','1'],['Active coaching engagements','1'],['Development actions complete','6 / 9']]:role==='coach'?[['Active clients','1'],['Upcoming sessions','2'],['Coaching hours this month','6'],['Actions to review','2']]:role==='mentor'?[['Assigned candidates','1'],['Upcoming conversations','1'],['Evidence awaiting review','2'],['Development actions','3']]:[['Development goals','3'],['Actions completed',`${actions.filter(a=>a.done).length} / 3`],['Next conversation','This week'],['Current focus','Delegation']];
  content=<><Metrics items={metrics}/><div className="grid gap-5 lg:grid-cols-[1.3fr_1fr]"><Panel title={role==='company-admin'?'Company priorities':'Your next steps'}>{role==='company-admin'?<div className="grid gap-3">{[['roles','Review priority role expectations'],['candidates','Review leader development plans'],['requests','Follow the open coaching request'],['billing','Review the next coaching installment']].map(([id,title])=><Link className="rounded-xl border border-slate-200 p-4 font-medium text-teal-950 hover:bg-teal-50" key={id} href={href(id)}>{title} →</Link>)}</div>:learningActions}</Panel><Panel title="Coming up"><p className="text-lg font-semibold">{role==='mentor'||role==='candidate'?'Mentoring conversation':'Leadership coaching session'}</p><p className="mt-2 text-sm text-slate-600">{role==='mentor'||role==='candidate'?mentor:coach} · {leader}</p><p className="mt-4">Thursday · 10:00–11:00 a.m. Mountain Time</p><p className="mt-2 text-sm text-slate-600">Review delegation practice and agree on one next experiment.</p><Link href={href(role==='candidate'||role==='mentor'?'mentoring':role==='company-admin'?'engagements':'sessions')} className="mt-5 inline-block font-semibold text-teal-800 underline">Open workspace</Link></Panel></div><Panel title="Explore this perspective"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rolePages[role].filter(p=>p.id!=='home').map(p=><Link key={p.id} href={href(p.id)} className="rounded-xl border border-slate-200 p-4 hover:bg-teal-50"><p className="font-semibold text-teal-950">{p.label} →</p><p className="mt-2 text-sm text-slate-600">{p.description}</p></Link>)}</div></Panel></>;
  break;
 }
 case 'profile':content=role==='coach'?<><Panel title={coach}><Badge>Approved sample coach</Badge><p className="mt-4 text-lg">Executive transitions, delegation, and leadership communication</p><p className="mt-3 text-slate-600">PCC · Virtual coaching · Mountain Time · English</p><p className="mt-4">I help leaders build confidence, practice new approaches, and turn reflection into action.</p></Panel><Panel title="Marketplace readiness"><Table head={['Requirement','Status']} rows={[["Profile and specialties",'Complete'],['Credential verification','Verified sample credential'],['Availability','Published'],['Agreement','Accepted']]}/></Panel></>:<><Panel title={leader}><Badge>Candidate</Badge><dl className="mt-5 grid gap-4 sm:grid-cols-2">{[['Company',org.shortName],['Target role',org.role],['Mentor',mentor],['Development focus','Leadership communication and delegation']].map(([label,value])=><div key={label}><dt className="text-sm text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl></Panel><Panel title="Role competencies"><Table head={['Competency','Current development priority','Next experience']} rows={[["Leadership communication",'Priority focus','Facilitate a team decision'],['Delegation','Building experience','Delegate a planning workstream'],['Cross-functional collaboration','Ongoing practice','Lead a departmental handoff']]}/><Link href={href('development')} className="mt-4 inline-block underline">Open my development plan</Link></Panel></>;break;
 case 'development':content=<><Panel title={`${leader} · Development plan`}><p className="mb-4 text-sm text-slate-600">Target role: {org.role} · Mentor: {mentor}</p>{learningActions}</Panel><Panel title={role==='mentor'?'Review development evidence':'Add development evidence'}><p className="mb-4">Example evidence: a meeting agenda, a delegation agreement, and a short reflection on the outcome.</p><form onSubmit={e=>{e.preventDefault();save(role==='mentor'?'Mentor review recorded':'Development evidence added');}} className="grid gap-3"><label className="grid gap-1 text-sm font-medium">{role==='mentor'?'Mentor observation':'What did you practice and learn?'}<textarea rows={4} required className={inputClass}/></label><button className={`${buttonClass} justify-self-start`}>{role==='mentor'?'Record sample review':'Add sample evidence'}</button></form></Panel></>;break;
 case 'mentoring':content=<><Panel title="Mentoring partnership"><p className="text-lg font-semibold">{leader} & {mentor}</p><p className="mt-2 text-slate-600">Target role: {org.role}</p><p className="mt-4">Next conversation: Thursday · 30 minutes</p></Panel><Panel title="Preparation worksheet"><form className="grid gap-4" onSubmit={e=>{e.preventDefault();save('Preparation worksheet updated');}}>{['What experience will we discuss?','What worked, and what would you do differently?','What support or feedback would help?','What is the next practical step?'].map((label,index)=><label key={label} className="grid gap-1 text-sm font-medium">{label}<textarea className={inputClass} rows={2} defaultValue={index===0?'Delegating ownership of the next team planning meeting.':''}/></label>)}<button className={`${buttonClass} justify-self-start`}>Save sample preparation</button></form></Panel><Panel title="Agreed next actions">{learningActions}</Panel></>;break;
 case 'projects':content=<><Panel title="Development projects"><Table head={['Project','Experience type','Progress','']} rows={[["Improve the team planning handoff",'Departmental project',<Badge key="a">In progress</Badge>,<button key="b" className="font-semibold underline" onClick={()=>setDetail('Project brief: improve the planning handoff. Lead a working session, document decision ownership, and gather feedback from the team. Success evidence: a shared checklist and a reflection reviewed with the mentor.')}>Open project</button>],['Coordinate a cross-team improvement','Cross-departmental project','Planned',<button key="c" className="underline" onClick={()=>setDetail('Project brief: work with a partner department to improve one shared process. Agree on the scope, the people involved, and how progress will be reviewed.')}>Open project</button>]]}/></Panel><Panel title="Project reflection"><form className="grid gap-3" onSubmit={e=>{e.preventDefault();save('Project reflection recorded');}}><label className="grid gap-1 text-sm font-medium">What changed because of this experience?<textarea className={inputClass} required rows={4}/></label><button className={`${buttonClass} justify-self-start`}>Save sample reflection</button></form></Panel></>;break;
 case 'personal-development':content=<><Panel title="Strengths, role, and growth"><div className="grid gap-4 sm:grid-cols-3">{[['Strengths','Building relationships and bringing structure to complex work.'],['Role expectations',`Prepare for ${org.role} by practicing communication, delegation, and collaboration.`],['Growth plan','Use one real work experience each week to practice your next priority.']].map(([title,text])=><div key={title} className="rounded-xl bg-teal-50 p-4"><h3 className="font-semibold text-teal-950">{title}</h3><p className="mt-2 text-sm">{text}</p></div>)}</div></Panel><Panel title="Current growth commitment"><label className="grid gap-2 text-sm font-medium">What will you practice?<textarea value={goal} onChange={e=>setGoal(e.target.value)} rows={3} className={inputClass}/></label><button onClick={()=>save('Growth commitment updated')} className={`${buttonClass} mt-4`}>Save sample commitment</button></Panel></>;break;
 case 'coaching':content=<>{engagement}<Panel title="Shared goals">{learningActions}</Panel><Panel title="Next session"><p>Thursday · 10:00 a.m. Mountain Time · Virtual</p><p className="mt-3 text-sm">Prepare an example of a delegated decision to discuss with {coach}.</p>{noteForm}</Panel></>;break;
 case 'goals':content=<><Panel title={`${leader} · Agreed goals`}><label className="grid gap-2 text-sm font-medium">Primary coaching goal<textarea className={inputClass} value={goal} onChange={e=>setGoal(e.target.value)} rows={3}/></label><button className={`${buttonClass} mt-4`} onClick={()=>save('Agreed goal updated')}>Save sample goal</button><p className="mt-4 text-sm text-slate-600">Starting point: delegation often returns to the leader. Target: the team owns clear decisions and follow-up.</p></Panel><Panel title="Next actions">{learningActions}</Panel></>;break;
 case 'sessions':content=<><Panel title="Upcoming session"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{leader} with {coach}</h3><p className="mt-2">Thursday · 10:00–11:00 a.m. Mountain Time</p></div><Badge>{sessionStatus}</Badge></div><p className="mt-4 text-sm">Focus: delegation, decision ownership, and reflection on the latest practice.</p>{role==='coach'&&<button className={`${buttonClass} mt-4`} onClick={()=>{setSessionStatus('Completed');save('Session marked complete');}}>Mark sample session complete</button>}</Panel><Panel title={role==='coach'?'Session documentation':'Prepare for your session'}>{noteForm}</Panel><Panel title="Session history"><Table head={['Session','Focus','Duration','Status']} rows={[["Session 1",'Goals and working agreement','60 minutes','Completed'],['Session 2','Practicing delegation','60 minutes','Completed']]}/></Panel></>;break;
 case 'notes':content=<><Panel title="Private coaching notes"><Badge>Coach private · Sample content</Badge><p className="mt-4">Example private note: consider an open question about how the client chooses which decisions to retain.</p><p className="mt-3 text-sm text-slate-500">This fictional note is shown only in the Coach sample perspective.</p></Panel><Panel title="Add a note">{noteForm}</Panel></>;break;
 case 'availability':content=<Panel title="Weekly availability"><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();save('Availability updated');}}><label className="grid gap-1 text-sm font-medium">Time zone<select className={inputClass}><option>America/Denver</option><option>America/Chicago</option><option>America/New_York</option></select></label><label className="grid gap-1 text-sm font-medium">Day<select className={inputClass}><option>Thursday</option><option>Tuesday</option><option>Wednesday</option></select></label><label className="grid gap-1 text-sm font-medium">Start<input className={inputClass} type="time" defaultValue="09:00" required/></label><label className="grid gap-1 text-sm font-medium">End<input className={inputClass} type="time" defaultValue="12:00" required/></label><label className="grid gap-1 text-sm font-medium">Maximum active clients<input className={inputClass} type="number" min={1} defaultValue={6}/></label><button className={`${buttonClass} self-end justify-self-start`}>Save sample availability</button></form></Panel>;break;
 case 'requests':case 'opportunities':content=<Panel title={role==='company-admin'?'Coaching request':role==='coach'?'New coaching opportunity':'Your proposed coach'}><div className="flex flex-wrap justify-between gap-3"><h3 className="text-lg font-semibold">Leadership confidence & delegation</h3><Badge>{requestStatus}</Badge></div><p className="mt-4">{leader} · {org.role} · {org.shortName}</p><p className="mt-3">Proposed coach: {coach}. Six virtual sessions focused on delegation and leadership communication.</p><div className="mt-5 flex flex-wrap gap-3">{role==='company-admin'?<button className={buttonClass} onClick={()=>{setRequestStatus('Coach invited');save('Coach invitation simulated');}}>Try inviting the sample coach</button>:<><button className={buttonClass} onClick={()=>{setRequestStatus(role==='coach'?'Interested':'Coach accepted');save(role==='coach'?'Interest recorded':'Coach accepted');}}>{role==='coach'?'Express sample interest':'Accept sample coach'}</button><button className="rounded-full border px-4 py-2 text-sm font-semibold" onClick={()=>{setRequestStatus('Declined');save('Request declined');}}>Decline sample request</button></>}</div><details className="mt-5 rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Coach profile and fit</summary><p className="mt-3">{coach} specializes in executive transitions and leadership communication. Virtual sessions are available in Mountain Time.</p></details></Panel>;break;
 case 'consent':content=<Panel title="Your sharing choices"><p className="mb-5 text-sm text-slate-600">Review what you choose to share with your coach and sponsoring organization.</p>{([['goals','Share agreed goals with my coach'],['development','Share selected development records with my coach'],['organization','Share progress summaries with my company']] as const).map(([key,label])=><label key={key} className="mb-3 flex items-start gap-3 rounded-xl border p-4"><input className="mt-1 h-4 w-4" type="checkbox" checked={sharing[key]} onChange={e=>{setSharing({...sharing,[key]:e.target.checked});save('Sharing preference updated');}}/><span>{label}</span></label>)}<p className="mt-4 text-sm">Private coaching notes are separate from these choices.</p></Panel>;break;
 case 'feedback':content=<Panel title="Your coaching experience"><form className="grid gap-4" onSubmit={e=>{e.preventDefault();save('Feedback recorded');}}>{['Overall experience','Progress toward agreed goals','Communication and professionalism'].map(label=><label key={label} className="grid gap-1 text-sm font-medium">{label}<select required className={inputClass} defaultValue=""><option value="" disabled>Choose a rating</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>)}<label className="grid gap-1 text-sm font-medium">What was valuable?<textarea rows={3} className={inputClass}/></label><p className="text-sm text-slate-500">Feedback is private to the platform. Exclude confidential coaching discussions.</p><button className={`${buttonClass} justify-self-start`}>Submit sample feedback</button></form></Panel>;break;
 case 'notifications':content=<Panel title="Your notifications"><div className="grid gap-3">{['Your next conversation is coming up.','A development action is ready to review.','Your shared goal has been updated.'].map(message=><div key={message} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><p>{message}</p><button className="text-sm font-semibold underline" onClick={e=>{e.currentTarget.textContent='Read';e.currentTarget.disabled=true;save('Notification marked read');}}>Mark read</button></div>)}</div></Panel>;break;
 case 'clients':case 'candidates':content=<Panel title={role==='coach'?'Your coaching clients':role==='mentor'?'Your assigned candidates':'Company candidates'}><Table head={['Name','Target role','Focus','']} rows={(role==='company-admin'?[...org.people]:[leader]).map(name=>[name,org.role,'Delegation and communication',<button className="font-semibold underline" key={name} onClick={()=>setDetail(`${name} · ${org.role}. Development focus: delegation and leadership communication. Mentor: ${mentor}. Shared progress: on track. Next step: review the team planning experience.`)}>View development summary</button>])}/><p className="mt-4 text-sm text-slate-500">{role==='mentor'?'This sample mentor has one assigned candidate.':role==='coach'?'This sample coach has one active client.':'Only this sample company’s leaders appear here.'}</p></Panel>;break;
 case 'roles':content=<Panel title="Priority roles"><Table head={['Role','Priority competencies','Candidates','']} rows={[[org.role,'Communication · Delegation · Collaboration','2',<button key="role" className="font-semibold underline" onClick={()=>setDetail(`${org.role}: guide a team, delegate clear decision ownership, coordinate cross-functional work, and communicate priorities. Sample target expectations can be reviewed with the candidates and their mentors.`)}>View role expectations</button>]]}/></Panel>;break;
 case 'reviews':content=<Panel title="360 review cycle"><Table head={['Leader','Review','Responses','Status']} rows={[[leader,'Leadership development review','4 of 6','In progress'],[org.people[identity.person?0:1],'Communication review','6 of 6','Ready for review']]}/><button className={`${buttonClass} mt-4`} onClick={()=>save('Review reminder simulated')}>Try a sample reminder</button></Panel>;break;
 case 'administration':content=<Panel title="Company users and assignments"><Table head={['Person','Role','Assignment','Status']} rows={[[org.admin,'Company Administrator',org.shortName,'Active'],[mentor,'Mentor',leader,'Active'],[leader,'Candidate',org.role,'Active']]}/><button className={`${buttonClass} mt-4`} onClick={()=>setDetail('Sample invitation: choose Candidate or Mentor, enter a sample name, and assign a target role or candidate. Live invitations are not sent from this preview.')}>Review invitation flow</button></Panel>;break;
 case 'marketplace':content=<Panel title="Find a coach"><div className="rounded-2xl border border-slate-200 p-5"><Badge>Available · Virtual</Badge><h3 className="mt-4 text-xl font-semibold">{coach}</h3><p className="mt-2">Executive transitions and leadership communication</p><p className="mt-3 text-sm text-slate-600">PCC · English · Mountain Time</p><p className="mt-4">Experience supporting leaders as they build confidence, delegate responsibility, and lead through change.</p><Link className={`${buttonClass} mt-5 inline-block`} href={href('requests')}>Review sample coaching request</Link></div></Panel>;break;
 case 'engagements':content=<>{engagement}<Panel title="Organization-shared progress"><Table head={['Agreed objective','Progress','Next review']} rows={[["Practice clearer delegation",'On track','After session 4'],['Communicate decision ownership','In progress','After session 4']]}/><p className="mt-4 text-sm text-slate-500">Company administrators see agreed objectives and shared progress. Private coaching notes are not part of this view.</p></Panel></>;break;
 case 'programs':content=<><Metrics items={[["Program participants",'2'],['Active coaching engagements','1'],['Planned sessions','12'],['Program status','Active']]}/><Panel title="Emerging Leaders"><p>A six-session coaching program paired with practical leadership experiences and mentor reviews.</p><Table head={['Participant','Target role','Status']} rows={org.people.map(name=>[name,org.role,name===leader?'Active coaching':'Matching'])}/></Panel></>;break;
 case 'analytics':content=<><Metrics items={[["Participating leaders",'2'],['Active engagements','1'],['Completed sessions','2 / 6'],['Goal actions complete','3 / 5']]}/><Panel title="Development outcomes"><Table head={['Measure','Starting point','Current observation']} rows={[["Delegation practice",'Leader retained most decisions','One planning workstream delegated'],['Communication','Unclear follow-up ownership','Team using an agreed follow-up checklist']]}/><p className="mt-4 text-sm text-slate-500">Illustrative sample observations, not measured results or proof of coaching impact.</p></Panel></>;break;
 case 'billing':case 'earnings':content=<><Metrics items={role==='coach'?[['Sample earnings',' $400'],['Pending payment','$200'],['Completed sessions','2'],['Payment status','Scheduled']]:[['Program commitment','$1,800'],['Paid','$600'],['Next installment','$600'],['Status','Current']]}/><Panel title={role==='coach'?'Compensation ledger':'Company invoices'}><Table head={['Reference','Description','Amount','Status']} rows={role==='coach'?[['DEMO-E01','Completed coaching sessions','$400','Recorded'],['DEMO-E02','Upcoming session compensation','$200','Pending completion']]:[['DEMO-I01','Leadership coaching · installment 1','$600','Paid'],['DEMO-I02','Leadership coaching · installment 2','$600','Scheduled']]}/><p className="mt-4 text-sm text-slate-500">Illustrative amounts only. This preview cannot charge a card, refund a payment, or initiate a payout.</p></Panel></>;break;
 case 'log':content=<><Metrics items={[["Sample coaching hours",'6'],['Paid hours','4'],['Pro bono hours','2'],['Active clients','1']]}/><Panel title="Coaching log"><Table head={['Client','Session','Hours','Category']} rows={[[leader,'Goal setting','1.0','Paid individual coaching'],[leader,'Delegation practice','1.0','Paid individual coaching']]}/><p className="mt-4 text-sm text-slate-500">Fictional log records for reviewing the coach experience.</p></Panel></>;break;
 case 'quality':content=<><Panel title="Your practice indicators"><Table head={['Indicator','Sample observation']} rows={[["Session documentation",'2 of 2 completed sessions documented'],['Professional development','One learning activity recorded'],['Client feedback average','Not shown: insufficient responses']]}/></Panel><Panel title="Professional development"><form className="grid gap-3" onSubmit={e=>{e.preventDefault();save('Professional development activity recorded');}}><label className="grid gap-1 text-sm font-medium">Activity title<input className={inputClass} required placeholder="Example: Coaching supervision"/></label><label className="grid gap-1 text-sm font-medium">Reflection<textarea className={inputClass} rows={3}/></label><button className={`${buttonClass} justify-self-start`}>Add sample activity</button></form></Panel></>;break;
 case 'resources':content=<Panel title="Mentor resources"><div className="grid gap-3">{[['Preparation worksheet','Prepare the experience, reflection, feedback, and next action before meeting.'],['Departmental project guide','Choose a bounded work experience with clear evidence of learning.'],['Cross-departmental project guide','Build relationships across teams while solving a shared problem.']].map(([title,text])=><details className="rounded-xl border p-4" key={title}><summary className="cursor-pointer font-semibold">{title}</summary><p className="mt-3 text-sm">{text}</p></details>)}</div></Panel>;break;
 default:content=null;
 }
 return <main className="app-page"><div className="mx-auto flex max-w-[1380px] flex-col gap-5 px-5 py-8 sm:px-8 lg:px-10"><header><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">{roleLabels[role]} · Sample experience</p><h1 className="mt-2 text-3xl font-semibold text-teal-950">{section==='home'?`Welcome, ${identity.name.split(' ')[0]}`:page.label}</h1><p className="mt-3 max-w-3xl text-slate-600">{page.description}</p></header><p className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">Explore example navigation and workflows for this role. Sample edits reset when you change pages or people.</p>{notice&&<div role="status" className="rounded-xl border border-teal-200 bg-teal-50 p-4 text-sm text-teal-950">{notice}</div>}{content}{notes.length>0&&<Panel title="Notes added in this preview">{notes.map((note,i)=><div key={i} className="mb-3 rounded-xl border p-4"><Badge>{note.visibility}</Badge><p className="mt-3 whitespace-pre-wrap">{note.text}</p></div>)}</Panel>}{detail&&<section role="region" aria-label="Sample record details" className="rounded-2xl border border-teal-200 bg-teal-50 p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold text-teal-950">Sample record details</h2><button className="text-sm font-semibold underline" onClick={()=>setDetail(null)}>Close details</button></div><p className="mt-3 text-sm">{detail}</p></section>}</div></main>;
}
