import { NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { addReview360RespondentSchema, createReview360Token, hashReview360Token } from "@/lib/review-360";
import { isAdminAppRole } from "@/lib/mentor-access";
import { requireWorkspaceProfile } from "@/lib/workspace";
import { getAppUrl } from "@/lib/env";
import { hasResendEnv } from "@/lib/env";
import { sendResendEmail } from "@/lib/resend";
type Context = { params: Promise<{ reviewId: string }> };
export async function POST(request: Request, context: Context) { try { const { reviewId } = await context.params; const { profile } = await requireWorkspaceProfile(); if (!isAdminAppRole(profile.role)) return NextResponse.json({error:"Forbidden"},{status:403}); const input=addReview360RespondentSchema.parse(await request.json()); const admin=createSupabaseAdminClient(); const cycle=await admin.from("review_360_cycles").select("id,title,role_title,status").eq("id",reviewId).eq("organization_id",profile.organization_id).maybeSingle(); if(cycle.error) throw cycle.error; if(!cycle.data||["completed","archived"].includes(cycle.data.status)) return NextResponse.json({error:"This review cannot accept respondents."},{status:409}); const token=createReview360Token(); const saved=await admin.from("review_360_respondents").insert({organization_id:profile.organization_id,review_cycle_id:reviewId,first_name:input.firstName,last_name:input.lastName,email:input.email.toLowerCase(),invited_relationship:input.relationship,token_hash:hashReview360Token(token),status:"pending",invited_at:new Date().toISOString()}).select("id").single(); if(saved.error) throw saved.error; await admin.from("review_360_cycles").update({status:"invitations_pending",launched_at:new Date().toISOString()}).eq("id",reviewId).eq("status","draft"); const link=`${getAppUrl().replace(/\/$/,"")}/360-review/survey/${token}`; if(hasResendEnv()) await sendResendEmail({to:input.email,subject:`Complete 360 Review: ${cycle.data.title}`,text:`Your feedback on ${cycle.data.role_title} is valuable. Complete the confidential review: ${link}`,html:`<p>Your feedback is valuable.</p><p><a href="${link}">Complete 360 Review</a></p>`,idempotencyKey:`360-${saved.data.id}`}); return NextResponse.json({id:saved.data.id,link},{status:201}); } catch(error) {return NextResponse.json({error:error instanceof Error?error.message:"Unable to invite respondent."},{status:400});} }
