import Link from "next/link";
import Image from "next/image";
import { getLegacyCertificationAsset } from "@/lib/legacy-certifications";
import { requirePaidWorkspaceProfile } from "@/lib/workspace";

export default async function ContinuityScorePage() {
  await requirePaidWorkspaceProfile();
  const asset = getLegacyCertificationAsset("bronze");
  return <main className="app-page"><div className="mx-auto max-w-6xl px-6 py-12"><Link href="/dashboard" className="text-sm font-semibold text-teal-800">← Back to Dashboard</Link><section className="mt-6 rounded-[2rem] border border-slate-200 bg-white p-8"><p className="text-sm font-semibold tracking-[0.16em] text-blue-800 uppercase">Leadership continuity signals</p><h1 className="mt-3 font-display text-4xl text-slate-900">Risk and recommended actions</h1><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-[1.5rem] border border-slate-200 bg-slate-50 p-6"><p className="text-sm font-semibold tracking-[0.14em] text-slate-500 uppercase">Legacy certification</p><div className="mt-3 flex items-center gap-4">{asset ? <Image src={asset.src} alt={asset.alt} width={64} height={64} /> : null}<h2 className="font-display text-4xl text-slate-900">Bronze</h2></div><p className="mt-5 text-base font-semibold text-blue-900">0 protected roles</p><div className="mt-3 space-y-2 text-sm leading-6 text-slate-600"><p>Top roles protected 0/3</p><p>Top roles covered 2/3</p><p>Two-deep top roles 1/3</p><p className="pt-3">Bench coverage is forming across the top visible roles, with at least one role already two-deep.</p></div></section><section className="rounded-[1.5rem] border border-slate-200 bg-slate-50 p-6"><p className="text-sm font-semibold tracking-[0.14em] text-slate-500 uppercase">Recommended next actions</p><h2 className="mt-3 font-display text-3xl text-slate-900">What the Leadership Continuity System is telling you next</h2><div className="mt-5 grid gap-3">{["Immediate risk watch","Development bottleneck","Bench strength signal"].map((title) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="font-semibold text-slate-900">{title}</p><p className="mt-2 text-sm leading-6 text-slate-600">Review the current role pipeline, candidate readiness, and mentoring activity.</p></article>)}</div></section></div></section></div></main>;
}
