const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(relative,dependencies={}){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(path.join(__dirname,'../../',relative),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('module','exports','require',code)(module,module.exports,name=>{if(name in dependencies)return dependencies[name];throw Error('Unexpected dependency '+name);});return module.exports;}
const m=load('src/lib/platform-preview/model.ts');
test('preview eligibility requires a live platform administrator and the private account',()=>{assert.equal(m.canUsePlatformPreview({role:'system_admin'},'david@cycleofbusiness.com'),true);for(const profile of [null,{role:'hospital_admin'},{role:'mentor'},{role:'candidate'},{role:'system_admin',deleted_at:'2026-01-01'}])assert.equal(m.canUsePlatformPreview(profile,'david@cycleofbusiness.com'),false);assert.equal(m.canUsePlatformPreview({role:'system_admin'},'other@example.test'),false);});
test('sample selector accepts only fictional company and person identifiers',()=>{assert.equal(m.resolveSample('real-company-uuid','real-person-uuid').company.id,'cedar');assert.equal(m.resolveSample('harbor','second').company.id,'harbor');assert.equal(m.resolveSample('harbor','second').person,1);assert.equal(m.sampleIdentity('mentor','harbor','first').name,'Casey Morgan');assert.equal(m.sampleIdentity('candidate','harbor','second').name,'Alex Parker');});
test('return navigation rejects external, auth, API, malformed, and nested-preview targets',()=>{for(const target of ['https://evil.test','//evil.test','/\\evil.test','/api/payments','/auth/logout','/view-as/coach','/%2f%2fevil.test','/../api/payments'])assert.equal(m.safeReturnPath(target),'/platform-operations');assert.equal(m.safeReturnPath('/admin/coaching/marketplace'),'/admin/coaching/marketplace');});
test('all preview links stay in the role namespace and carry normalized sample context',()=>{for(const role of m.previewRoles){const ids=m.rolePages[role].map(p=>p.id);assert.equal(new Set(ids).size,ids.length);for(const section of ids){const href=m.previewHref(role,section,{company:'harbor',person:'second',returnTo:'//evil.test'});const url=new URL(href,'https://example.test');assert.equal(url.pathname,`/view-as/${role}/${section}`);assert.equal(url.searchParams.get('company'),'harbor');assert.equal(url.searchParams.get('returnTo'),'/platform-operations');}}assert.match(m.previewHref('candidate','billing'),/^\/view-as\/candidate\/home\?/);});
test('private coach notes and company controls are absent from other role menus',()=>{assert(m.rolePages.coach.some(p=>p.id==='notes'));for(const role of ['candidate','mentor','coachee','company-admin'])assert(!m.rolePages[role].some(p=>p.id==='notes'));for(const role of ['candidate','mentor','coachee','coach'])assert(!m.rolePages[role].some(p=>['administration','billing'].includes(p.id)));});
function guard({user={id:'signed-in-user',email:'david@cycleofbusiness.com'},profile={role:'system_admin',deleted_at:null},error=null}={}){const calls=[];const query={select(fields){calls.push(['select',fields]);return this;},eq(key,value){calls.push(['eq',key,value]);return this;},is(key,value){calls.push(['is',key,value]);return this;},async maybeSingle(){return {data:profile,error};}};const server=load('src/lib/platform-preview/server.ts',{'server-only':{},'next/navigation':{notFound(){throw Error('NOT_FOUND');}},'@/lib/auth':{async requireUser(){if(!user)throw Error('AUTH_REQUIRED');return user;}},'@/lib/supabase/server':{async createSupabaseServerClient(){return {from(table){assert.equal(table,'profiles');return query;}};}},'./model':m});return {run:server.requirePlatformPreviewAdministrator,calls};}
test('server guard verifies authenticated identity and non-deleted profile before allowing a preview',async()=>{const g=guard();await g.run();assert(g.calls.some(c=>c[0]==='eq'&&c[1]==='auth_user_id'&&c[2]==='signed-in-user'));assert(g.calls.some(c=>c[0]==='is'&&c[1]==='deleted_at'&&c[2]===null));});
test('direct preview requests fail closed for absent, ordinary, deleted, or wrong-email users',async()=>{for(const options of [{user:null},{profile:null},{profile:{role:'hospital_admin'}},{profile:{role:'system_admin',deleted_at:'2026-01-01'}},{user:{id:'someone',email:'other@example.test'}},{error:{message:'database unavailable'}}])await assert.rejects(guard(options).run());});
