const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/DavidsAir/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.env.PREVIEW_BASE||'http://127.0.0.1:55457',login=process.env.PREVIEW_LOGIN||'http://127.0.0.1:55450/preview';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext();const page=await context.newPage();
 let writes=0;context.on('request',r=>{if(r.method()!=='GET'&&r.method()!=='HEAD'&&r.url().startsWith(base))writes++;});
 await page.goto(login+'?role=platform');await page.goto(base+'/admin/coaching');await page.getByLabel('View as',{exact:true}).waitFor();console.log('PASS administrator dropdown visible on a live page');
 for(const [role,label] of [['candidate','Candidate'],['mentor','Mentor'],['coachee','Person Being Coached'],['coach','Coach'],['company-admin','Company Administrator']]){
  await page.getByLabel('View as',{exact:true}).selectOption(role);await page.getByRole('region',{name:'Role preview banner'}).getByText('Viewing as: '+label,{exact:true}).waitFor();await page.locator('main h1').waitFor();assert((await page.locator('main').innerText()).length>300);console.log('PASS '+label+' perspective');
  const links=await page.getByRole('navigation',{name:label+' platform navigation'}).getByRole('link').evaluateAll(nodes=>nodes.map(n=>n.href));
  for(const href of links){await page.goto(href);await page.locator('main h1').waitFor();assert(!/Application error|Internal Server Error/.test(await page.locator('body').innerText()));assert((await page.locator('main').innerText()).length>250,'Empty preview '+href);}
  console.log('PASS '+label+' pages: '+links.length);
 }
 await page.getByLabel('View as',{exact:true}).selectOption('coach');await page.getByRole('navigation',{name:'Coach platform navigation'}).getByRole('link',{name:'Notes',exact:true}).click();await page.getByRole('heading',{name:'Private coaching notes',exact:true}).waitFor();
 await page.getByLabel('Coaching note',{exact:true}).fill('Sample-only reflection');await page.getByRole('button',{name:'Add sample note',exact:true}).click();await page.getByText('Sample-only reflection',{exact:true}).waitFor();console.log('PASS sample note editing');
 await page.getByLabel('View as',{exact:true}).selectOption('coachee');await page.locator('main').getByText('Person Being Coached · Sample experience',{exact:true}).waitFor();assert.equal(await page.getByText('Sample-only reflection',{exact:true}).count(),0);assert.equal(await page.getByRole('heading',{name:'Private coaching notes',exact:true}).count(),0);console.log('PASS coach note excluded from person perspective');
 await page.getByLabel('Sample company',{exact:true}).selectOption('harbor');await page.getByLabel('Sample person',{exact:true}).selectOption('second');await page.getByRole('navigation',{name:'Person Being Coached platform navigation'}).getByRole('link',{name:'My Coaching',exact:true}).click();await page.getByText(/Alex Parker · Coach: Drew Bennett/).waitFor();assert(!(await page.locator('main').innerText()).includes('Jordan Ellis'));console.log('PASS sample company/person isolation and navigation');
 await page.getByRole('navigation',{name:'Person Being Coached platform navigation'}).getByRole('link',{name:'Sharing & Consent',exact:true}).click();await page.getByLabel('Share progress summaries with my company',{exact:true}).check();await page.getByRole('status').filter({hasText:'Sharing preference updated'}).waitFor();assert.equal(writes,0);console.log('PASS sample interactions make no mutation requests');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);console.log('PASS mobile layout');await page.setViewportSize({width:1440,height:1100});await page.getByLabel('View as',{exact:true}).selectOption('candidate');await page.locator('main').getByText('Candidate · Sample experience',{exact:true}).waitFor();await page.screenshot({path:'/private/tmp/lc-platform-view-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Return to Administrator',exact:true}).click();await page.waitForURL(base+'/admin/coaching');await page.getByLabel('View as',{exact:true}).waitFor();assert.equal(await page.getByRole('region',{name:'Role preview banner'}).count(),0);console.log('PASS return to original administrator page');
 await page.goto(base+'/view-as/candidate/billing');await page.getByText('This page could not be found.').waitFor();console.log('PASS role-inappropriate route denied');
 const other=await browser.newContext();const otherPage=await other.newPage();await otherPage.goto(login+'?role=admin');await otherPage.goto(base+'/view-as/candidate/home');await otherPage.getByText('This page could not be found.').waitFor();assert.equal(await otherPage.getByLabel('View as',{exact:true}).count(),0);console.log('PASS other account cannot open role previews');await other.close();
 await context.close();
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
