import { NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { isAdminAppRole } from "@/lib/mentor-access";
import { requireWorkspaceProfile } from "@/lib/workspace";
import { getAppUrl, hasResendEnv } from "@/lib/env";
import { createReview360Token, hashReview360Token } from "@/lib/review-360";
import { sendResendEmail } from "@/lib/resend";
type Context={params:Promise<{reviewId:string;respondentId:string}>};
export async function POST(_:Request,ctx:Context){try{const {reviewId,respondentId}=await ctx.params;const {profile}=await requireWorkspaceProfile();if(!isAdminAppRole(profile.role))return NextResponse.json({error:"Forbidden"},{status:403});if(!hasResendEnv())return NextResponse.json({error:"Email delivery is not configured."},{status:400});const admin=createSupabaseAdminClient();const [cycle,result]=await Promise.all([admin.from("review_360_cycles").select("title,role_title").eq("id",reviewId).eq("organization_id",profile.organization_id).single(),admin.from("review_360_respondents").select("id,first_name,email,status").eq("id",respondentId).eq("review_cycle_id",reviewId).eq("organization_id",profile.organization_id).single()]);if(cycle.error||result.error)throw cycle.error??result.error;if(result.data.status==="completed")return NextResponse.json({error:"Completed responses cannot be resent."},{status:409});const token=createReview360Token();const link=`${getAppUrl().replace(/\/$/,"")}/360-review/survey/${token}`;await sendResendEmail({to:result.data.email,subject:`Complete 360 Review: ${cycle.data.title}`,text:`Your feedback on ${cycle.data.role_title} is valuable. Complete the confidential review: ${link}`,html:`<p>Your feedback is valuable.</p><p><a href="${link}">Complete 360 Review</a></p>`,idempotencyKey:`360-${respondentId}-${Date.now()}`});const now=new Date().toISOString();await admin.from("review_360_respondents").update({token_hash:hashReview360Token(token),status:"pending",invited_at:now}).eq("id",respondentId);await admin.from("review_360_cycles").update({status:"invitations_pending",launched_at:now}).eq("id",reviewId).eq("status","draft");return NextResponse.json({message:`Invitation sent to ${result.data.first_name}.`});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to send invitation."},{status:400});}}
