"use client";
import { useEffect, useState } from "react";
type Earning = { invoice_id: string; currency: string; commission_cents: number; status: string; reason: string; hold_until: string | null; affiliates: { name: string; payout_email: string | null } | { name: string; payout_email: string | null }[] | null };
export default function AffiliatePayoutsPage() {
 const [rows, setRows] = useState<Earning[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState<string | null>(null);
 async function load() { const response = await fetch("/api/platform-operations/affiliate-payouts"); const data = await response.json(); if (!response.ok) throw new Error(data.error); setRows(data.earnings ?? []); }
 useEffect(() => { let active = true; fetch("/api/platform-operations/affiliate-payouts").then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); if (active) setRows(data.earnings ?? []); }).catch(error => { if (active) setMessage(error instanceof Error ? error.message : "Unable to load payouts."); }); return () => { active = false; }; }, []);
 async function approve(id: string) { setBusy(id); setMessage(""); try { const response = await fetch("/api/platform-operations/affiliate-payouts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ earningId: id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage(`Transfer ${data.transferId} completed.`); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to approve payout."); } finally { setBusy(null); } }
 return <main className="mx-auto max-w-6xl space-y-6 px-6 py-10"><a className="underline" href="/platform-operations">Platform operations</a><h1 className="text-4xl font-semibold">Affiliate payout approval</h1><p className="text-slate-600">Only matured commissions appear here. Approving a row creates one idempotent Stripe transfer to the affiliate’s connected account.</p>{message && <p role="status" className="rounded-lg bg-amber-50 p-4">{message}</p>}<div className="overflow-auto rounded-2xl border bg-white"><table className="w-full text-left"><thead><tr><th className="p-4">Affiliate</th><th className="p-4">Invoice</th><th className="p-4">Amount</th><th className="p-4">Action</th></tr></thead><tbody>{rows.map(row => { const affiliate = Array.isArray(row.affiliates) ? row.affiliates[0] : row.affiliates; return <tr className="border-t" key={row.invoice_id}><td className="p-4">{affiliate?.name ?? "Unknown"}<div className="text-sm text-slate-500">{affiliate?.payout_email}</div></td><td className="p-4">{row.invoice_id}</td><td className="p-4">{new Intl.NumberFormat("en-US", { style: "currency", currency: row.currency }).format(row.commission_cents / 100)}</td><td className="p-4"><button disabled={busy !== null} onClick={() => void approve(row.invoice_id)} className="rounded-lg bg-slate-900 px-4 py-2 text-white disabled:opacity-50">{busy === row.invoice_id ? "Processing…" : "Approve payout"}</button></td></tr>; })}</tbody></table>{!rows.length && <p className="p-6">No payable affiliate commissions are waiting for approval.</p>}</div></main>;
}
