import { NextResponse } from "next/server";
import { z } from "zod";
import { ApiRouteError, createApiErrorResponse, requireApiWorkspaceProfile } from "@/lib/api-route";
import { sanitizeAppText } from "@/lib/text-sanitizer";

const schema = z.object({ action: z.enum(["save","recipient"]), surveyId: z.string().uuid().optional(), title: z.string().trim().min(3).max(160).optional(), introMessage: z.string().trim().max(6000).optional().default(""), thankYouMessage: z.string().trim().max(3000).optional().default(""), status: z.enum(["draft","active","closed"]).optional(), recipientName: z.string().trim().min(2).max(160).optional(), recipientEmail: z.string().trim().email().max(320).optional() });
export async function POST(request: Request) {
 try { const {admin,profile}=await requireApiWorkspaceProfile({product:"leadership_help"}); const p=schema.parse(await request.json()); const pd=await admin.from("personal_development_profiles").select("id").eq("profile_id",profile.id).maybeSingle(); if(!pd.data) throw new ApiRouteError("Save your role profile first.",400); const role=await admin.from("personal_role_profiles").select("id").eq("personal_development_profile_id",pd.data.id).maybeSingle(); if(!role.data) throw new ApiRouteError("Save your role profile first.",400);
 if(p.action==="save"){if(!p.title||!p.status) throw new ApiRouteError("Enter a title and status.",400); const now=new Date().toISOString(); const values={title:sanitizeAppText(p.title),intro_message:sanitizeAppText(p.introMessage)||null,thank_you_message:sanitizeAppText(p.thankYouMessage)||null,status:p.status,launched_at:p.status==="active"?now:null,closed_at:p.status==="closed"?now:null}; const q=p.surveyId?admin.from("personal_competency_surveys").update(values).eq("id",p.surveyId):admin.from("personal_competency_surveys").insert({...values,organization_id:profile.organization_id,personal_development_profile_id:pd.data.id,personal_role_profile_id:role.data.id,created_by_profile_id:profile.id}); const r=await q.select("id").single(); if(r.error) throw new ApiRouteError(r.error.message,500); return NextResponse.json({surveyId:r.data.id,message:"Personal survey saved."});}
 if(!p.surveyId||!p.recipientName||!p.recipientEmail) throw new ApiRouteError("Save the survey and enter a recipient.",400); const r=await admin.from("personal_competency_survey_recipients").insert({organization_id:profile.organization_id,survey_id:p.surveyId,recipient_name:sanitizeAppText(p.recipientName),recipient_email:p.recipientEmail.toLowerCase(),invited_at:new Date().toISOString()}).select("id,access_token").single(); if(r.error) throw new ApiRouteError(r.error.code==="23505"?"That recipient is already on this survey.":r.error.message,400); return NextResponse.json({recipientId:r.data.id,accessToken:r.data.access_token,message:"Recipient added. Copy the invitation link to send it."});
 } catch(e){return createApiErrorResponse(e,"Unable to manage the personal survey.");}
}
