const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),Stripe=require('stripe');
// Exercise production adapter exports with an in-memory provider and database transport.
// No Stripe keys, real transactions, or network calls are used.
function setup(){
 const calls=[],state={payment:{id:'p1',organization_id:'org1',engagement_id:'e1',agreement_id:'a1',amount:'466.67',currency:'USD',package_name:'Fictional coaching',checkout_attempt:1},events:new Set()};
 const db={rpc:async(name,{operation,payload})=>{calls.push({operation,payload});let data={};if(operation==='payment')data=state.payment;if(operation==='checkout_saved'){state.payment.stripe_checkout_session_id=payload.session_id;state.payment.checkout_url=payload.url;}if(operation==='event'){if(state.events.has(payload.event_id))data={duplicate:true};else state.events.add(payload.event_id);}if(operation==='connect')data={};if(operation==='refund')data={id:'r1',payment_intent_id:'pi1',amount:'100'};if(operation==='payout')data={id:'po1',amount:'175',currency:'USD',account_id:'acct1'};return {data,error:null};},from:()=>({select:()=>({eq:()=>({single:async()=>({data:{stripe_customer_id:'cus_existing'},error:null})})})})};
 const stripe={checkout:{sessions:{create:async(args,opts)=>{calls.push({checkout:args,key:opts.idempotencyKey});return {id:'cs1',url:'https://checkout.stripe.com/test',expires_at:2000000000};},retrieve:async()=>({status:'open',url:'https://checkout.stripe.com/test'})}},customers:{create:async()=>{throw Error('Should reuse existing subscription customer');}},accounts:{create:async(args,opts)=>{calls.push({account:args,key:opts.idempotencyKey});return {id:'acct1'};}},accountLinks:{create:async()=>({url:'https://connect.stripe.com/test'})},refunds:{create:async(args,opts)=>{calls.push({refund:args,key:opts.idempotencyKey});return {id:'re1',status:'succeeded'};}},transfers:{create:async(args,opts)=>{calls.push({transfer:args,key:opts.idempotencyKey});return {id:'tr1'};}},paymentIntents:{retrieve:async()=>({latest_charge:{balance_transaction:{fee:1383}}})}};
 const modelModule={exports:{}};new Function('module','exports',ts.transpileModule(fs.readFileSync('src/lib/coaching/commerce-model.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(modelModule,modelModule.exports);
 const customRequire=name=>name==='server-only'?{}:name==='stripe'?Stripe:name==='@/lib/stripe-billing'?{getStripe:()=>stripe,getStripeBillingReturnUrl:p=>'http://localhost'+p}:name==='@/lib/supabase/admin'?{createSupabaseAdminClient:()=>db}:name==='./commerce-model'?modelModule.exports:require(name);
 const module={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync('src/lib/coaching/commerce-provider.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(customRequire,module,module.exports);
 return {...module.exports,calls,state};
}
process.env.STRIPE_SECRET_KEY='sk_test_fictional_no_network';
test('checkout derives price from stored installment, reuses customer, and reuses open session',async()=>{const t=setup();assert.equal(await t.coachingCheckout('p1'),'https://checkout.stripe.com/test');await t.coachingCheckout('p1');const checkouts=t.calls.filter(c=>c.checkout);assert.equal(checkouts.length,1);assert.equal(checkouts[0].checkout.line_items[0].price_data.unit_amount,46667);assert.equal(checkouts[0].checkout.customer,'cus_existing');assert.equal(checkouts[0].key,'coaching-checkout-p1-1');});
test('Connect requests hosted onboarding and stores only provider ID',async()=>{const t=setup();assert.equal(await t.coachingConnect('coach1'),'https://connect.stripe.com/test');assert.ok(t.calls.some(c=>c.operation==='connect_saved'&&c.payload.account_id==='acct1'));});
test('refund and transfer use database amount with stable provider keys',async()=>{const t=setup();await t.coachingRefund('r1');await t.coachingPayout('po1');assert.equal(t.calls.find(c=>c.refund).refund.amount,10000);assert.equal(t.calls.find(c=>c.transfer).transfer.amount,17500);assert.equal(t.calls.find(c=>c.transfer).key,'coaching-payout-po1');});
test('real Stripe SDK signature verification rejects tampering before adapter processing',async()=>{const sdk=new Stripe('sk_test_fictional_no_network'),secret='whsec_fictional';const body=JSON.stringify({id:'evt_signed',type:'payment_intent.succeeded',created:1900000000,data:{object:{id:'pi1',amount:46667,currency:'usd',metadata:{coaching_payment_id:'p1'}}}});const signature=sdk.webhooks.generateTestHeaderString({payload:body,secret});const event=sdk.webhooks.constructEvent(body,signature,secret);assert.throws(()=>sdk.webhooks.constructEvent(body+' ',signature,secret));const t=setup();await t.handleCoachingStripeEvent(event);await t.handleCoachingStripeEvent(event);assert.equal(t.state.events.size,1);const payload=t.calls.find(c=>c.operation==='event').payload;assert.equal(payload.amount,466.67);assert.equal(payload.fee,13.83);assert.equal(payload.paid,true);});
test('coaching handler leaves subscription checkout to existing billing handler',async()=>{const t=setup();assert.equal(await t.handleCoachingStripeEvent({id:'sub',type:'checkout.session.completed',data:{object:{metadata:{},subscription:'sub1'}}}),false);});
