// Fictional localhost fixture only; never use this workflow test against production.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const ctx=await browser.newContext();const page=await ctx.newPage();const pass=[],base='http://127.0.0.1:55449';const main=()=>page.locator('main.app-page:not([aria-busy])');const login=async(role)=>{await page.goto('http://127.0.0.1:55448/preview?role='+role);await main().waitFor({state:'visible'});};const visit=async(path)=>{await page.goto(base+path);await main().waitFor({state:'visible'});assert(!(await main().innerText()).includes('Application error'));};const form=(operation)=>main().locator('form').filter({has:page.locator('input[name=operation][value="'+operation+'"]')});
await login('platform');await main().getByRole('heading',{name:'Marketplace health',exact:true}).waitFor();assert((await main().innerText()).includes('Marketplace funnel'));await page.screenshot({path:'/private/tmp/lc-s5-marketplace.jpg',type:'jpeg',quality:55});pass.push('Platform marketplace, funnel, timings and supply dashboard renders');
for(const route of ['recruitment','executive','credentials','quality-review','coach-applications','compliance','scale-settings','privacy'])await visit('/admin/coaching/'+route);pass.push('All platform operations screens render');
await login('admin');await main().getByRole('heading',{name:'Organization coaching analytics',exact:true}).waitFor();assert(!(await page.content()).includes('Coach compensation'));assert(!(await page.content()).includes('PRIVATE'));pass.push('Organization analytics omit platform financials and private feedback');
for(const format of ['csv','xlsx']){const r=await ctx.request.get(base+'/api/coaching/analytics-export?format='+format);assert.equal(r.status(),200);assert((await r.body()).length>0);}pass.push('Authorized CSV and XLSX reports export');
await visit('/coaching/programs');let f=form('program');await f.locator('[name=name]').fill('Board Leadership Development');await f.locator('[name=start_date]').fill('2026-09-15');await f.locator('[name=status]').selectOption('active');await f.locator('[name=budget_amount]').fill('12500.50');await f.getByRole('button').click();await f.getByRole('status').waitFor();assert.equal(await f.getByRole('alert').count(),0);pass.push('Organization creates a program with decimal budget');
f=form('participant');await f.locator('[name=program_id]').selectOption({label:'Board Leadership Development'});await f.locator('[name=candidate_id]').selectOption({label:'Jordan Morgan'});await f.locator('[name=engagement_id]').selectOption({label:'Executive Leadership Development'});await f.getByRole('button').click();await f.getByRole('status').waitFor();assert.equal(await f.getByRole('alert').count(),0);pass.push('Program links an existing candidate and engagement');
await visit('/coaching/roi');f=form('roi');await f.locator('[name=measure_name]').fill('Project delivery');await f.locator('[name=measure_type]').fill('Operational outcome');for(const name of ['measurement_method','data_sources','assumptions'])await f.locator('[name='+name+']').fill('Fictional organization-defined comparison; association only.');await f.locator('[name=period_start]').fill('2026-01-01');await f.locator('[name=period_end]').fill('2026-09-15');await f.getByRole('button').click();await f.getByRole('status').waitFor();assert.equal(await f.getByRole('alert').count(),0);pass.push('Organization-defined outcome saves with methodology');
await visit('/coaching/saved');f=form('saved_coach');await f.getByRole('button').click();await f.getByRole('status').waitFor();assert.equal(await f.getByRole('alert').count(),0);await visit('/coaching/marketplace?network=ours');assert((await main().innerText()).includes('Alex Rivera'));pass.push('Preferred organization coach network filters marketplace');
await login('leader');f=form('feedback');await f.locator('[name=overall_experience]').selectOption('5');await f.locator('[name=comments]').fill('PRIVATE BROWSER FEEDBACK');await f.getByRole('button').click();await f.getByRole('status').waitFor();assert.equal(await f.getByRole('alert').count(),0);pass.push('Leader submits platform-private closeout feedback');assert.equal((await ctx.request.get(base+'/api/coaching/analytics-export')).status(),403);pass.push('Leader cannot export organization analytics');
await login('coach');assert(!(await page.content()).includes('PRIVATE BROWSER FEEDBACK'));await visit('/coaching/onboarding');await main().getByRole('heading',{name:'Marketplace readiness',exact:true}).waitFor();f=form('training_complete').first();await f.getByRole('button').click();await f.getByRole('status').waitFor();pass.push('Coach sees readiness checklist and records orientation completion without private feedback');
await visit('/coaching/quality');f=form('professional_development');await f.locator('[name=title]').fill('Coaching supervision');await f.locator('[name=completion_date]').fill('2026-09-15');await f.locator('[name=hours]').fill('1.5');await f.getByRole('button').click();await f.getByRole('status').waitFor();assert.equal(await f.getByRole('alert').count(),0);pass.push('Coach records fractional professional-development hours');
const practiceExport=await ctx.request.get(base+'/api/coaching/analytics-export?section=practice&format=csv');assert.equal(practiceExport.status(),200);assert(!(await practiceExport.text()).includes('PRIVATE BROWSER FEEDBACK'));pass.push('Coach practice export excludes private client feedback');
await visit('/coaching/privacy');f=form('privacy_request');await f.locator('[name=reason]').fill('Fictional request to review analytics processing');await f.getByRole('button').click();await f.getByRole('status').waitFor();assert.equal(await f.getByRole('alert').count(),0);pass.push('Privacy request uses record-category selection');
await login('admin');await visit('/coaching/renewals');f=form('renewal');await f.locator('[name=focus]').fill('Continue executive communication development');await f.getByRole('button').click();await page.waitForURL('**/coaching/request?edit=*');pass.push('Renewal opens an editable new request');
await page.setViewportSize({width:390,height:844});await visit('/coaching/analytics');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:'/private/tmp/lc-s5-mobile.jpg',type:'jpeg',quality:55});pass.push('Analytics fit mobile viewport');
console.log(JSON.stringify({passed:pass},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
