// Uses only the fictional localhost Sprint 4 fixture. Never point this test at production.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const ctx=await browser.newContext();const page=await ctx.newPage();const pass=[];const base='http://127.0.0.1:55447',cid='00000000-0000-0000-0000-000000000201';const login=async(role)=>{await page.goto('http://127.0.0.1:55446/preview?role='+role);await page.waitForLoadState('networkidle');};const main=()=>page.locator('main.app-page:not([aria-busy])');
await login('admin');await main().getByRole('heading',{name:'Development Intelligence',exact:true}).waitFor();assert((await main().innerText()).includes('Jordan Morgan'));assert((await main().innerText()).includes('Not assessed'));pass.push('Candidate priorities show sourced gaps and missing assessments');await page.screenshot({path:'/private/tmp/lc-s4-priorities.jpg',type:'jpeg',quality:55});
await main().getByRole('button',{name:'Find a Coach for This Development Need'}).first().click();await page.waitForURL('**/coaching/request?edit=*');assert((await main().locator('[name=request_title]').inputValue()).includes('Communication'));pass.push('Development recommendation opens prepopulated editable request');
await page.goto(base+'/candidates/'+cid+'/development');assert((await main().innerText()).includes('Build development plan'));pass.push('Development portfolio and interactive map render');
let form=main().locator('form').filter({has:page.locator('input[name=operation][value=evidence]')});await form.locator('[name=title]').fill('Observed presentation');await form.locator('[name=description]').fill('Presented a concise recommendation in the agreed exercise.');await form.locator('[name=evidence_date]').fill('2026-09-15');await form.getByRole('button',{name:'Save',exact:true}).click();await form.getByRole('status').waitFor();assert.equal(await form.getByRole('alert').count(),0);pass.push('Development evidence can be recorded through the page');
await page.goto(base+'/candidates/'+cid+'/competencies/00000000-0000-0000-0000-000000000401/evidence');await main().getByRole('heading',{name:'Competency evidence timeline',exact:true}).waitFor();pass.push('Competency evidence timeline route renders');
await page.goto(base+'/candidates/'+cid+'/readiness-review');form=main().locator('form').filter({has:page.getByRole('button',{name:'Record human review',exact:true})});await form.locator('[name=match_status]').selectOption('not_yet');await form.locator('[name=readiness_score]').fill('60');await form.locator('[name=reason]').fill('Fictional human review: further observed practice is required.');await form.getByRole('button').click();await form.getByRole('status').waitFor();assert.equal(await form.getByRole('alert').count(),0);pass.push('Authorized human readiness review saves with reason and history');
await page.goto(base+'/coaching/outcomes');await main().getByRole('heading',{name:'Organization development heatmap',exact:true}).waitFor();assert(!(await page.content()).includes('SECRET INTERVIEW'));pass.push('Organization outcomes, heatmap and opportunities render without source narratives');await page.screenshot({path:'/private/tmp/lc-s4-outcomes.jpg',type:'jpeg',quality:55});
await login('coach');assert(!(await main().innerText()).includes('Recorded score 2'));assert(!(await page.content()).includes('SECRET INTERVIEW'));pass.push('Coach preview excludes unselected development sources');
await login('leader');await page.goto(base+'/candidates/'+cid+'/readiness-review');assert.equal(await main().getByRole('button',{name:'Record human review'}).count(),0);pass.push('Leader can read own readiness but cannot publish a readiness decision');
await login('platform');await main().getByRole('heading',{name:'Development method rules',exact:true}).waitFor();pass.push('Platform method and evidence configuration renders');
await login('admin');await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:'/private/tmp/lc-s4-mobile.jpg',type:'jpeg',quality:55});pass.push('Candidate priorities fit mobile viewport');
console.log(JSON.stringify({passed:pass},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
