'use client';
import { useActionState } from 'react';
import { mutateCoachPortal } from '@/lib/coaching/actions';

type Summary = { profile?: Record<string, unknown>; insurance?: Array<Record<string, unknown>>; credentials?: Array<Record<string, unknown>> };
export function CoachOnboarding({ summary }: { summary: Summary }) {
    const initialState: { error?: string; success?: string } = {};
    const [profileState, profileAction, profilePending] = useActionState(mutateCoachPortal, initialState);
    const [credentialState, credentialAction, credentialPending] = useActionState(mutateCoachPortal, initialState);
    const p = summary.profile ?? {};
    const insurance = summary.insurance?.[0];
    return <div className="grid gap-6 lg:grid-cols-2">
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><h2 className="text-xl font-semibold text-teal-950">Coach onboarding</h2><p className="mt-2 text-slate-600">Complete your profile and submit credentials and insurance so Leader Continuity can verify your eligibility.</p><div className="mt-4 flex flex-wrap gap-4 text-sm"><span className="rounded-full bg-sky-100 px-3 py-1">Profile: {String(p.profile_completion_percent ?? 0)}%</span><span className="rounded-full bg-amber-100 px-3 py-1">Eligibility: {String(p.eligibility_status ?? 'action_required').replaceAll('_',' ')}</span><span className="rounded-full bg-slate-100 px-3 py-1">Application: {String(p.profile_status ?? 'draft').replaceAll('_',' ')}</span></div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Profile details</h2><form action={profileAction} className="mt-4 grid gap-3"><input type="hidden" name="operation" value="profile"/><label>Headline<input name="headline" defaultValue={String(p.headline ?? '')} className="mt-1 w-full rounded-lg border p-2"/></label><label>Short bio<textarea name="short_bio" defaultValue={String(p.short_bio ?? '')} className="mt-1 w-full rounded-lg border p-2" rows={4}/></label><div className="grid gap-3 sm:grid-cols-2"><label>City<input name="city" defaultValue={String(p.city ?? '')} className="mt-1 w-full rounded-lg border p-2"/></label><label>Country<input name="country" defaultValue={String(p.country ?? '')} className="mt-1 w-full rounded-lg border p-2"/></label><label>Timezone<input name="timezone" defaultValue={String(p.timezone ?? '')} className="mt-1 w-full rounded-lg border p-2"/></label><label>Phone<input name="phone" defaultValue={String(p.phone ?? '')} className="mt-1 w-full rounded-lg border p-2"/></label></div><button disabled={profilePending} className="w-fit rounded-full bg-teal-950 px-5 py-2 text-white">{profilePending ? 'Saving…' : 'Save profile'}</button>{profileState.error && <p className="text-red-700">{profileState.error}</p>}{profileState.success && <p className="text-teal-800">{profileState.success}</p>}</form></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Insurance</h2><p className="mt-2 text-sm text-slate-600">{insurance ? `${String(insurance.insurer)} · ${String(insurance.verification_status)} · expires ${String(insurance.expiration_date)}` : 'No certificate submitted yet.'}</p><p className="mt-4 text-sm text-slate-600">Upload and certificate metadata can be added next; this status area is ready for the private document workflow.</p></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><h2 className="text-lg font-semibold">Credentials</h2><div className="mt-3 grid gap-2">{(summary.credentials ?? []).map(c => <div key={String(c.id)} className="rounded-lg border p-3 text-sm">{String(c.credential_name)} · {String(c.verification_status)}{c.expiration_date ? ` · expires ${String(c.expiration_date)}` : ''}</div>)}{!(summary.credentials ?? []).length && <p className="text-sm text-slate-600">No credentials submitted yet.</p>}</div><form action={credentialAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="operation" value="credential"/><input name="credential_name" required placeholder="Credential name" className="rounded-lg border p-2"/><input name="issuing_organization" placeholder="Issuing organization" className="rounded-lg border p-2"/><input name="credential_number" placeholder="Credential number" className="rounded-lg border p-2"/><input name="expiration_date" type="date" className="rounded-lg border p-2"/><button disabled={credentialPending} className="w-fit rounded-full bg-teal-950 px-5 py-2 text-white">{credentialPending ? 'Submitting…' : 'Submit credential'}</button>{credentialState.error && <p className="text-red-700">{credentialState.error}</p>}{credentialState.success && <p className="text-teal-800">{credentialState.success}</p>}</form></section>
    </div>;
}
