'use client';
import {useState,useRef} from 'react';
import Link from 'next/link';
import {CoachingForm} from './form';
import {Field,Select,Panel} from './ui';
import {coachingObjectives,type LeaderContext,type Reference,type Match} from '@/lib/coaching/workflow-model';
export function RequestWizard({leaders,contexts,specialties,industries,levels,initial}:{initial?:Record<string,unknown>;leaders:{id:string;name:string;candidate:boolean}[];contexts:Record<string,LeaderContext>;specialties:Reference[];industries:Reference[];levels:Reference[]}){
 const root=useRef<HTMLDivElement>(null);const [summary,setSummary]=useState<[string,string][]>([]);
 const value=(key:string)=>String(initial?.[key]??'');const selected=(key:string,id:string)=>Array.isArray(initial?.[key])&&(initial[key] as string[]).includes(id);
 const [step,setStep]=useState(0);const [leader,setLeader]=useState(value('requested_for_user_id')||leaders[0]?.id||'');
 const go=(next:number)=>{if(next===4){const form=root.current?.querySelector('form');if(form)setSummary(Array.from(new FormData(form).entries()).filter(([k])=>!k.startsWith('$')&&!['operation','id'].includes(k)).map(([k,v])=>[k.replaceAll('_',' '),String(v)]));}setStep(next);};const context=contexts[leader];
 const steps=['Who needs coaching?','Why coaching?','Development information','Coach preferences','Review'];
 return <div ref={root}><Panel title="Find a Coach"><ol className="mb-6 flex flex-wrap gap-3">{steps.map((name,i)=><li key={name}><button type="button" className={step===i?'font-bold text-teal-900':'text-slate-500'} onClick={()=>go(i)}>{i+1}. {name}</button></li>)}</ol><CoachingForm operation="request_save" hidden={initial?.id?{id:String(initial.id)}:{}} button="Submit request and find matches" showSubmit={step===4} onInvalid={event=>{event.preventDefault();const field=event.target as HTMLElement;setStep(Number(field.closest('fieldset')?.getAttribute('data-step')??1));requestAnimationFrame(()=>field.focus());}}>
 <fieldset data-step="0" hidden={step!==0}><label className="grid gap-2">Select existing leader or candidate<select name="requested_for_user_id" value={leader} onChange={e=>setLeader(e.target.value)} className="rounded-xl border p-3">{leaders.map(l=><option value={l.id} key={l.id}>{l.name}{l.candidate?' (Candidate)':''}</option>)}</select></label><p className="my-3">Current role: {context?.current_role??'Not recorded'} · Target role: {context?.target_role??'Not recorded'}</p><p>Development plan: {context?.development_records.length??0} linked experiences. Readiness is available in the existing candidate workspace.</p><Link href="/administration" target="_blank" className="mt-4 inline-block underline">Invite / add a new leader using Organization Administration</Link></fieldset>
 <fieldset data-step="1" hidden={step!==1} className="grid gap-4"><Field name="request_title" label="Request title (internal)" value={value("request_title")} required/><div className="grid gap-2 sm:grid-cols-2">{coachingObjectives.map(o=><label key={o}><input type="checkbox" name="objectives" value={o} defaultChecked={selected("objectives",o)} className="mr-2"/>{o}</label>)}</div><Field name="request_reason" label="What should this engagement accomplish? (Internal matching context)" type="textarea" value={value("request_reason")}/><Field name="development_focus" label="Organization objectives" type="textarea" value={value("development_focus")}/></fieldset>
 <fieldset data-step="2" hidden={step!==2} className="grid gap-4" key={leader}><p>This information will be used to improve coach matching. Detailed development information will not be shared with a coach until the appropriate permissions and consent have been granted.</p><label><input type="checkbox" name="context_categories" value="competencies" defaultChecked={selected("context_categories","competencies")} className="mr-2"/>Use target-role competencies</label><div className="grid gap-2 sm:grid-cols-2">{context?.competencies.map(c=><label key={c.id}><input type="checkbox" name="competency_ids" value={c.id} defaultChecked={selected("competency_ids",c.id)} className="mr-2"/>{c.name}</label>)}</div><label><input type="checkbox" name="context_categories" value="development_plan" defaultChecked={selected("context_categories","development_plan")} className="mr-2"/>Consider existing development-plan context</label>{context?.development_records.map(d=><p key={d.id}>{d.title} · {d.status}</p>)}<p className="text-sm text-slate-600">The initial matching rules use exact competency-to-specialty names. Assessment scores and private notes are not sent to prospective coaches.</p></fieldset>
 <fieldset data-step="3" hidden={step!==3} className="grid gap-3 sm:grid-cols-2"><Select name="preferred_credential" value={value("preferred_credential")} options={['acc','pcc','mcc']} empty="No credential preference"/><Select name="preferred_industry_id" value={value("preferred_industry_id")} label="Industry" options={industries.map(i=>({value:i.id,label:i.name}))} empty="No preference"/><Select name="preferred_leadership_level_id" value={value("preferred_leadership_level_id")} label="Leadership level" options={levels.map(i=>({value:i.id,label:i.name}))} empty="No preference"/><Select name="preferred_format" value={value("preferred_format")} label="Format" options={['video','phone','in_person']} empty="No preference"/><Field name="location_preference" value={value("location_preference")} label="City or country (optional)"/><Field name="timezone" value={value("timezone")} label="IANA time zone (e.g. America/Denver)"/><Field name="language" value={value("language")}/><Field name="preferred_start_date" value={value("preferred_start_date")} type="date"/><Field name="desired_duration_months" value={value("desired_duration_months")} type="number"/><Field name="estimated_sessions" value={value("estimated_sessions")} type="number"/><fieldset className="sm:col-span-2"><legend>Coaching specialties</legend><div className="flex flex-wrap gap-3">{specialties.map(s=><label key={s.id}><input type="checkbox" name="specialty_ids" value={s.id} defaultChecked={selected("specialty_ids",s.id)} className="mr-2"/>{s.name}</label>)}</div></fieldset></fieldset>
 <div hidden={step!==4}><h3 className="font-semibold">Review your request</h3><dl className="my-4 grid gap-2">{summary.filter(([,v])=>v).map(([k,v],i)=><div key={i}><dt className="text-sm font-medium">{k}</dt><dd className="break-words">{[...specialties,...industries,...levels,...(context?.competencies??[])].find(r=>r.id===v)?.name??(v===leader?context?.leader:v)}</dd></div>)}</dl><Select name="submit" label="Save as" value="true" options={[{value:"true",label:"Submit for matching"},{value:"false",label:"Draft"}]}/><p className="my-3">Leader: {context?.leader}. Target role: {context?.target_role??'No target role selected'}.</p><p>Use the steps above to review the need and preferences. Submitting generates an explainable rules-based shortlist. It does not invite a coach or activate an engagement.</p></div>
 <div className="flex gap-4">{step>0&&<button type="button" className="underline" onClick={()=>go(step-1)}>Back</button>}{step<4&&<button type="button" className="rounded-full border px-5 py-2" onClick={()=>go(step+1)}>Continue</button>}</div>
 </CoachingForm></Panel></div>;
}
export function CompareCoaches({matches}:{matches:Match[]}){
 const [selected,setSelected]=useState<string[]>([]);const rows=matches.filter(m=>selected.includes(m.coach_id));
 return <Panel title="Compare up to three coaches"><div className="flex flex-wrap gap-4">{matches.map(m=><label key={m.coach_id}><input className="mr-2" type="checkbox" checked={selected.includes(m.coach_id)} disabled={selected.length===3&&!selected.includes(m.coach_id)} onChange={e=>setSelected(e.target.checked?[...selected,m.coach_id]:selected.filter(id=>id!==m.coach_id))}/>{m.display_name}</label>)}</div>{rows.length>0&&<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Factor</th>{rows.map(r=><th className="p-3" key={r.coach_id}>{r.display_name}</th>)}</tr></thead><tbody>{[['Coaching Match',...rows.map(r=>`${r.match_score}%`)],['Credential',...rows.map(r=>r.icf_credential.toUpperCase())],['Years coaching',...rows.map(r=>r.years_coaching)],['Leadership experience',...rows.map(r=>r.years_leadership_experience)],['Industries',...rows.map(r=>r.industries?.join(', ')??'')],['Specialties',...rows.map(r=>r.specialties?.join(', ')??'')],['Leadership levels',...rows.map(r=>r.leadership_levels?.join(', ')??'')],['Availability',...rows.map(r=>r.availability_status)],['Format',...rows.map(r=>[r.virtual_available?'Virtual':'',r.in_person_available?'In person':''].filter(Boolean).join(', '))],['Match reasons',...rows.map(r=>r.match_reasons.join('; '))]].map((row,i)=><tr key={i} className="border-t">{row.map((v,j)=><td key={j} className="p-3 align-top">{v}</td>)}</tr>)}</tbody></table></div>}</Panel>;
}
export function SetupWizard({requestId,leader,coach,objectives}:{requestId:string;leader:string;coach:string;objectives:string}){
 const root=useRef<HTMLDivElement>(null);const [summary,setSummary]=useState<[string,string][]>([]);
 const [step,setStep]=useState(0);const go=(next:number)=>{if(next===5){const form=root.current?.querySelector('form');if(form)setSummary(Array.from(new FormData(form).entries()).filter(([k])=>!k.startsWith('$')&&!['operation','request_id'].includes(k)).map(([k,v])=>[k.replaceAll('_',' '),String(v)]));}setStep(next);};const steps=['Participants','Purpose','Structure','Sharing','Consent','Review'];
 return <div ref={root}><Panel title="Engagement Setup"><nav className="mb-5 flex flex-wrap gap-4">{steps.map((s,i)=><button key={s} onClick={()=>go(i)} className={step===i?'font-bold':'underline'}>{i+1}. {s}</button>)}</nav><CoachingForm operation="setup_engagement" hidden={{request_id:requestId}} button="Create engagement — pending consent" showSubmit={step===5} onInvalid={event=>{event.preventDefault();const field=event.target as HTMLElement;setStep(Number(field.closest('fieldset')?.getAttribute('data-step')??1));requestAnimationFrame(()=>field.focus());}}>
 <div hidden={step!==0}>Leader: {leader} · Coach: {coach}</div><fieldset data-step="1" hidden={step!==1}><Field name="title" label="Engagement title" required/><Select name="engagement_type" options={['leadership_development','executive_coaching','succession_readiness','executive_transition','performance_coaching','career_coaching','onboarding_coaching','custom']}/><Field name="organization_objectives" label="Organization-shared objectives" type="textarea" value={objectives}/></fieldset>
 <fieldset data-step="2" hidden={step!==2} className="grid gap-3 sm:grid-cols-2"><Field name="start_date" type="date" required/><Field name="planned_end_date" type="date" required/><Field name="planned_sessions" type="number" required/><Field name="planned_hours" type="number" required/></fieldset>
 <div hidden={step!==3}><h3 className="font-semibold">Three-way coaching agreement</h3><p>The organization sets shared funding objectives. Coach and leader establish their shared goals. Private coaching notes and reflections remain protected. Add shared coaching goals in the engagement after consent.</p></div>
 <div hidden={step!==4}><p>The leader must grant Record Retention, Credential Verification, Development Data Access, and Organization Reporting consent before activation. Development access still requires selection of individual records. No recording is enabled.</p></div>
 <div hidden={step!==5}><dl className="my-4 grid gap-3">{summary.map(([k,v],i)=><div key={i}><dt className="font-medium">{k}</dt><dd className="break-words">{v}</dd></div>)}</dl><p>Review each step before creating the engagement. The engagement stays pending until consent is complete and an authorized participant activates it.</p></div>
 <div className="flex gap-4">{step>0&&<button type="button" className="underline" onClick={()=>go(step-1)}>Back</button>}{step<5&&<button type="button" className="rounded-full border px-4 py-2" onClick={()=>go(step+1)}>Continue</button>}</div>
 </CoachingForm></Panel></div>;
}
