import Link from 'next/link';
import {notFound} from 'next/navigation';
import {coachingContext,rpc} from '@/lib/coaching/server';
import {type WorkflowRequest,type Opportunity,type Match,type Slot,type LeaderContext,type Reference,localTime} from '@/lib/coaching/workflow-model';
import {type Coach,type Filters,availabilityLabels} from '@/lib/coaching/model';
import {Panel,Field,Select,Metrics} from './ui';
import {CoachingForm,UnlockCoaching} from './form';
import {RequestWizard,CompareCoaches,SetupWizard} from './wizards';
type Context=Awaited<ReturnType<typeof coachingContext>>;
type Row={id:string;[key:string]:string};
async function rows(ctx:Context,table:string,column?:string,value?:string):Promise<Row[]>{const data:Row[]=[];for(let offset=0;;offset+=500){let q=ctx.db.from(table).select('*').order('id').range(offset,offset+499);if(column&&value)q=q.eq(column,value);const r=await q;if(r.error)throw new Error(r.error.message);data.push(...r.data as Row[]);if(r.data.length<500)return data;}}
export function isWorkflowPath(path:string[]){return ['request','requests','opportunities','availability','notifications'].includes(path[0])||(path[0]==='engagements'&&path[1]==='setup')||(path[0]==='admin'&&['overview','matching','workflow-requests','workflow-engagements'].includes(path[1]));}
export async function Workflow({ctx,path,filters}:{ctx:Context;path:string[];filters:Filters}){
 const requests=await rpc<WorkflowRequest[]>(ctx.db,'coaching_workflow_requests');
 if(path[0]==='notifications'){
 const notices=await rpc<Row[]>(ctx.db,'coaching_notifications');return <Panel title="Coaching Notifications">{notices.map(n=><div key={n.id} className="mb-4 rounded-2xl border p-4"><p className="font-semibold">{n.title}</p><p className="text-sm">{n.created_at.slice(0,16).replace('T',' ')}</p><Link className="mr-4 underline" href={n.href==='/coaching/notifications'?'/coaching/requests':n.href}>Open coaching workspace</Link>{!n.read_at&&<CoachingForm operation="notification_read" hidden={{id:n.id}} button="Mark read"/>}</div>)}{!notices.length&&<p>No coaching notifications yet.</p>}</Panel>;
 }
 if(path[0]==='availability')return <Availability ctx={ctx}/>;
 if(path[0]==='opportunities')return <Opportunities ctx={ctx}/>;
 if(path[0]==='admin'){
 if(!ctx.platformAdmin)notFound();
 if(path[1]==='matching'){
 const weights=await rows(ctx,'coaching_match_weights');return <Panel title="Matching Configuration"><p className="mb-4">Weights must total 100. Scores describe preference fit, not a probability of coaching success. New weights apply to future matching runs; historical results remain unchanged.</p><CoachingForm operation="weights"><div className="grid gap-3 sm:grid-cols-2">{weights.map(w=><Field key={w.id} name={`weight_${w.factor_key}`} label={w.factor_key.replaceAll('_',' ')} type="number" value={w.weight} required/>)}</div></CoachingForm></Panel>;
 }
 if(path[1]==='overview'){
 const summary=await rpc<Record<string,number>>(ctx.db,'coaching_operations_summary');
 return <><Metrics values={summary}/><Panel title="Coaching Operations"><div className="flex flex-wrap gap-4">{[['coaches','Coaches'],['requests','Access Requests'],['workflow-requests','Coaching Requests'],['workflow-engagements','Engagements'],['matching','Matching']].map(([p,l])=><Link className="underline" key={p} href={`/admin/coaching/${p}`}>{l}</Link>)}</div></Panel></>;
 }
 if(path[1]==='workflow-engagements')return <Panel title="Coaching Engagements">{(await rows(ctx,'coaching_engagements')).map(e=><p className="mb-3" key={e.id}><Link className="underline" href={`/coaching/clients/${e.id}`}>{e.title} · {e.status}</Link></p>)}</Panel>;
 }
 if(path[0]==='request'&&!path[1]){
 if(!ctx.admin)notFound();if(!ctx.active)return <Locked/>;
 const profiles=await rows(ctx,'profiles','organization_id',ctx.profile!.organization_id);
 const initial=filters.edit?(await rows(ctx,'coach_requests','id',filters.edit))[0]:undefined;
 const contexts=Object.fromEntries(await Promise.all(profiles.map(async p=>[p.auth_user_id,await rpc<LeaderContext>(ctx.db,'coaching_request_context',{leader:p.auth_user_id})])));
 const [specialties,industries,levels]=await Promise.all(['coaching_specialties','industries','leadership_levels'].map(t=>rows(ctx,t)));
 return <RequestWizard initial={initial} leaders={profiles.map(p=>({id:p.auth_user_id,name:p.full_name,candidate:Boolean(contexts[p.auth_user_id].candidate_id)}))} contexts={contexts} specialties={specialties as unknown as Reference[]} industries={industries as unknown as Reference[]} levels={levels as unknown as Reference[]}/>;
 }
 if(path[0]==='request'&&path[2]==='matches'){
 const request=requests.find(r=>r.id===path[1]);if(!request||!ctx.admin)notFound();if(!ctx.active&&!ctx.platformAdmin)return <Locked/>;
 const matches=await rpc<Match[]>(ctx.db,'coaching_workflow_matches',{rid:request.id});const coaches=await rpc<Coach[]>(ctx.db,'coaching_marketplace');
 const shown=filters.more==='true'?matches:matches.slice(0,5);
 return <><Panel title={`Matches: ${request.request_title}`}><p>Coaching Match measures how the listed preferences fit the coach profile. Unspecified preferences receive full points. This is not a prediction of success; availability must be confirmed when scheduling.</p><div className="mt-4"><CoachingForm operation="match" hidden={{request_id:request.id}} button="Refresh matches"/></div></Panel><CompareCoaches matches={shown.map(m=>({...m,industries:coaches.find(c=>c.id===m.coach_id)?.industries,specialties:coaches.find(c=>c.id===m.coach_id)?.specialties,leadership_levels:coaches.find(c=>c.id===m.coach_id)?.leadership_levels}))}/>{!matches.length&&<Panel title="We haven't identified a strong match yet.">Adjust your preferences or ask the Leader Continuity team to help identify additional coaches.</Panel>}<div className="grid gap-5 md:grid-cols-2">{shown.map(m=>{const c=coaches.find(c=>c.id===m.coach_id);return <Panel key={m.id} title={m.display_name}><p>{m.headline} · {m.icf_credential.toUpperCase()}</p><p className="my-3 text-3xl font-semibold text-teal-900">{Number(m.match_score).toFixed(0)}% Coaching Match</p><ul className="list-inside list-disc">{m.match_reasons.map(t=><li key={t}>{t}</li>)}</ul>{m.unmet_preferences.length>0&&<p className="mt-3 text-amber-900">Unmet: {m.unmet_preferences.join('; ')}</p>}<p className="mt-3">{c?.industries.join(' · ')}</p><p>{c?.specialties.join(' · ')}</p><p>{c?.leadership_levels.join(' · ')}</p><p>{availabilityLabels[m.availability_status]}</p><Link className="my-4 inline-block underline" href={`/coaching/marketplace/${m.coach_id}`}>View Profile</Link><CoachingForm operation="invite" hidden={{request_id:request.id,coach_id:m.coach_id}} button="Invite Coach"/>{ctx.platformAdmin&&<details className="mt-3"><summary>Recommendation intervention</summary><CoachingForm operation="recommendation" hidden={{request_id:request.id,coach_id:m.coach_id,excluded:'true'}} button="Remove recommendation"><Field name="admin_reason" label="Reason (audit)" required/></CoachingForm></details>}</Panel>;})}</div>{matches.length>5&&filters.more!=='true'&&<Link href={`?more=true`} className="underline">View More Coaches</Link>}{ctx.platformAdmin&&<Panel title="Add recommendation / capacity override"><CoachingForm operation="recommendation" hidden={{request_id:request.id}}><Select name="coach_id" options={coaches.map(c=>({value:c.id,label:c.display_name}))}/><Field name="admin_reason" required/><Select name="capacity_override" options={['false','true']}/></CoachingForm><p className="my-3 text-sm">An override is an administrator recommendation, not a computed match score. Override invitations require a separate explicit confirmation.</p><CoachingForm operation="invite" hidden={{request_id:request.id,capacity_override:'true'}} button="Invite with capacity override"><Select name="coach_id" options={coaches.map(c=>({value:c.id,label:c.display_name}))}/><Field name="admin_reason" required/></CoachingForm></Panel>}</>;
 }
 if(path[0]==='engagements'&&path[1]==='setup'){
 const r=requests.find(r=>r.id===path[2]);if(!r||!ctx.admin)notFound();return <SetupWizard requestId={r.id} leader={r.leader_name} coach={r.coach_name??'Selected coach'} objectives={r.development_focus??''}/>;
 }
 const opportunities=await rpc<Opportunity[]>(ctx.db,'coaching_opportunities');
 const meetings=await rows(ctx,'coaching_intro_meetings');
 return <><Panel title="Coaching Requests">{ctx.admin&&<Link className="inline-block rounded-full bg-teal-950 px-5 py-2 text-white" href="/coaching/request">Find a Coach</Link>}{!requests.length&&<><h3 className="mt-5 font-semibold">No coaching requests yet.</h3><p>When a leader would benefit from professional coaching, start a request to identify coaches whose experience aligns with the development need.</p></>}<div className="mt-5 grid gap-5">{requests.map(r=><Panel key={r.id} title={r.request_title}><p>{r.leader_name} · {r.status.replaceAll('_',' ')} · {r.coach_name??'Coach not selected'}</p><div className="mt-4 flex flex-wrap gap-4">{ctx.admin&&r.status==='draft'&&<Link className="underline" href={`/coaching/request?edit=${r.id}`}>Continue request</Link>}{ctx.admin&&!['draft','engagement_setup','converted_to_engagement','cancelled','closed'].includes(r.status)&&<Link className="underline" href={`/coaching/request/${r.id}/matches`}>View Matches</Link>}{ctx.admin&&r.status==='engagement_setup'&&<Link className="underline" href={`/coaching/engagements/setup/${r.id}`}>Set Up Engagement</Link>}{r.status==='converted_to_engagement'&&<Link className="underline" href="/coaching/engagements">Open engagements</Link>}</div>{!ctx.admin&&r.status==='leader_review'&&<p className="my-4">Your organization has identified a professional coach who may be a good fit for your development goals.</p>}{opportunities.filter(i=>i.request_id===r.id).map(i=><div key={i.id} className="mt-4 rounded-xl border p-4"><p>{i.coach_name} · {i.status}</p><Link className="underline" href={`/coaching/marketplace/${i.coach_id}`}>Review coach profile</Link>{r.requested_for_user_id===ctx.user.id&&i.status==='interested'&&<LeaderReview invitation={i}/>} {ctx.admin&&['pending','viewed','interested'].includes(i.status)&&<CoachingForm operation="withdraw_invitation" hidden={{id:i.id}} button="Withdraw invitation"/>}{ctx.platformAdmin&&i.admin_question&&<p className="mt-3">Coach question: {i.admin_question}</p>}</div>)}{meetings.filter(m=>m.coach_request_id===r.id).map(m=><p key={m.id} className="mt-3">Introduction: {m.status} · {m.scheduled_start_at??'Time to be arranged'} · {m.location_or_link}</p>)}{ctx.admin&&r.status!=='converted_to_engagement'&&<details className="mt-4"><summary>Request status</summary><CoachingForm operation="request_status" hidden={{request_id:r.id}}><Select name="status" options={['matching','cancelled','closed']}/></CoachingForm></details>}</Panel>)}</div></Panel></>;
}
function Locked(){return <Panel title="Unlock Coaching to begin working with a coach."><UnlockCoaching/></Panel>;}
function LeaderReview({invitation:i}:{invitation:Opportunity}){return <div className="mt-4 grid gap-4"><CoachingForm operation="leader_decision" hidden={{id:i.id,decision:'accept'}} button="I'm Comfortable Proceeding"/><CoachingForm operation="leader_decision" hidden={{id:i.id,decision:'another'}} button="I'd Like Another Coach"/><p className="text-sm">Requesting an introduction shares your identity with this coach for meeting coordination.</p><CoachingForm operation="intro" hidden={{id:i.id,status:'requested'}} button="Request Introductory Conversation"/></div>;}
async function Opportunities({ctx}:{ctx:Context}){
 if(!ctx.coach)notFound();const opportunities=await rpc<Opportunity[]>(ctx.db,'coaching_opportunities');const meetings=await rows(ctx,'coaching_intro_meetings');
 return <><Metrics values={{'New Opportunities':opportunities.filter(i=>i.status==='pending').length,'Pending Opportunities':opportunities.filter(i=>i.status==='viewed').length,'Accepted Opportunities':opportunities.filter(i=>['interested','converted'].includes(i.status)).length,'Declined Opportunities':opportunities.filter(i=>i.status==='declined').length}}/><Panel title="Coaching Opportunities">{!opportunities.length&&<><h3>No new coaching opportunities.</h3><p>New opportunities that align with your profile and availability will appear here.</p></>}<div className="grid gap-5 md:grid-cols-2">{opportunities.map(i=><Panel key={i.id} title={i.organization}><p>{i.industry} · {i.leadership_level} · {i.status}</p><p className="my-3">{i.objectives.join(' · ')}</p><p>{i.specialties.join(' · ')}</p><p>Start: {i.preferred_start_date??'Flexible'} · {i.duration_months??'Flexible'} months · {i.estimated_sessions??'TBD'} sessions</p><p>{i.format??'Flexible format'} · {i.timezone??'Time zone to be agreed'}</p><p className="mt-3 text-sm">The leader’s identity and detailed development records are withheld at this stage.</p>{['pending','viewed','interested'].includes(i.status)&&<div className="mt-4 grid gap-4"><CoachingForm operation="invitation_response" hidden={{id:i.id,decision:'viewed'}} button="Mark reviewed"/><CoachingForm operation="invitation_response" hidden={{id:i.id,decision:'interested'}} button="I'm Interested"/><details><summary>Decline opportunity</summary><CoachingForm operation="invitation_response" hidden={{id:i.id,decision:'declined'}} button="Decline"><Select name="decline_reason" options={['Schedule / Capacity','Not My Specialty','Conflict of Interest','Location','Engagement Type','Other']}/><Field name="response_message" label="Optional comments for administrators" type="textarea"/></CoachingForm></details><details><summary>Ask Platform Admin a Question</summary><CoachingForm operation="invitation_response" hidden={{id:i.id,decision:'question'}} button="Send question"><Field name="response_message" label="Question for platform administrator" type="textarea" required/></CoachingForm></details></div>}{(i.status==='converted'||(i.status==='interested'&&meetings.some(m=>m.coach_request_id===i.request_id&&m.coach_id===i.coach_id)))&&<details className="mt-4"><summary>Schedule introductory conversation</summary><CoachingForm operation="intro" hidden={{id:i.id,status:'scheduled'}}><Field name="scheduled_start_at" label="Start (ISO timestamp with time zone offset)" required/><Field name="scheduled_end_at" label="End (ISO timestamp with time zone offset)" required/><Select name="format" options={['video','phone','in_person']}/><Field name="location_or_link" label="Meeting location or link"/></CoachingForm></details>}</Panel>)}</div></Panel><Panel title="Introductory Meetings">{meetings.map(m=><p key={m.id} className="mb-3">{m.status} · {m.scheduled_start_at??'Time to be arranged'} · {m.location_or_link}</p>)}</Panel></>;
}
async function Availability({ctx}:{ctx:Context}){
 if(!ctx.coach)notFound();const [rules,exceptions]=await Promise.all([rows(ctx,'coach_availability_rules','coach_id',ctx.coach.id),rows(ctx,'coach_availability_exceptions','coach_id',ctx.coach.id)]);const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
 return <><Panel title="Weekly Availability"><p className="mb-4">Time windows use the specified IANA time zone, including daylight-saving changes.</p>{rules.filter(r=>String(r.active)==='true').map(r=><div key={r.id} className="mb-4 flex flex-wrap items-center gap-4"><p>{days[Number(r.day_of_week)]} {r.start_time}–{r.end_time} · {r.timezone}</p><CoachingForm operation="availability_remove" hidden={{coach_id:ctx.coach.id,id:r.id,kind:'rule'}} button="Remove time block"/></div>)}<CoachingForm operation="availability_rule" hidden={{coach_id:ctx.coach.id}} button="Add Time Block"><div className="grid gap-3 sm:grid-cols-2"><Select name="day_of_week" options={days.map((label,i)=>({label,value:String(i)}))}/><Field name="start_time" type="time" required/><Field name="end_time" type="time" required/><Field name="timezone" value={ctx.coach.timezone??'UTC'} required/><Field name="effective_start_date" type="date"/><Field name="effective_end_date" type="date"/></div></CoachingForm></Panel><Panel title="Exceptions / Block Date">{exceptions.map(x=><div key={x.id} className="mb-3"><p>{x.exception_date} · {x.exception_type} · {x.start_time??'All day'} {x.end_time}</p><CoachingForm operation="availability_remove" hidden={{coach_id:ctx.coach.id,id:x.id,kind:'exception'}} button="Remove exception"/></div>)}<CoachingForm operation="availability_exception" hidden={{coach_id:ctx.coach.id}} button="Add Exception"><Field name="exception_date" type="date" required/><Select name="exception_type" options={['unavailable','custom_availability']}/><Field name="start_time" type="time"/><Field name="end_time" type="time"/><Field name="timezone" value={ctx.coach.timezone??'UTC'} required/><Field name="notes" label="Private availability note"/></CoachingForm></Panel></>;
}
export async function EngagementWorkflow({ctx,id,tab,filters}:{ctx:Context;id:string;tab:string;filters:Filters}){
 const e=(await rows(ctx,'coaching_engagements','id',id))[0];if(!e)notFound();const participant=e.coachee_user_id===ctx.user.id||e.coach_id===ctx.coach?.id;
 if(tab==='Schedule'){
 if(!participant)notFound();const day=filters.day??new Date().toISOString().slice(0,10);const minutes=Number(filters.minutes??60);const zone=filters.zone??'UTC';let zoneValid=true;try{localTime(new Date().toISOString(),zone);}catch{zoneValid=false;}
 const slots=e.status==='active'?await rpc<Slot[]>(ctx.db,'coaching_available_slots',{cid:e.coach_id,day,minutes,engagement_id:id}):[];
 const sessions=await rows(ctx,'coaching_sessions','engagement_id',id);const changes=(await rows(ctx,'coaching_session_changes')).filter(c=>sessions.some(s=>s.id===c.session_id));
 return <><Panel title="Schedule Session"><p className="mb-4">Select a date in the coach’s time zone. Each slot also shows your selected display time zone.</p>{e.status!=='active'&&<p>Activate the engagement after consent before scheduling.</p>}<form className="mb-5 grid gap-3 sm:grid-cols-3"><input type="hidden" name="tab" value="Schedule"/><Field name="day" type="date" value={day}/><Field name="minutes" label="Duration (30, 45, 60, 90 or custom minutes)" type="number" value={minutes}/><Field name="zone" label="Your IANA time zone" value={zone}/><button className="rounded-full border p-2">Find available times</button></form>{!zoneValid&&<p role="alert">Enter a valid time zone such as America/Denver.</p>}<div className="grid gap-4 md:grid-cols-2">{slots.map(s=><Panel key={s.start}><p>{localTime(s.start,s.coach_timezone)} · Coach ({s.coach_timezone})</p>{zoneValid&&<p>{localTime(s.start,zone)} · You ({zone})</p>}<CoachingForm operation="schedule_session" hidden={{engagement_id:id,scheduled_start_at:s.start,scheduled_end_at:s.end}} button="Schedule Session"><Select name="session_format" options={['video','phone','in_person']}/></CoachingForm></Panel>)}</div>{e.status==='active'&&!slots.length&&<p>No open slots for this date and duration.</p>}</Panel><Panel title="Scheduled Sessions and Changes">{sessions.filter(s=>s.status==='scheduled').map(s=><Panel key={s.id} title={s.scheduled_start_at}><CoachingForm operation="session_change" hidden={{id:s.id}} button="Request change"><Select name="change_type" options={['reschedule','cancel']}/><Field name="requested_start_at" label="New start (ISO timestamp with offset; reschedule only)"/><Field name="requested_end_at" label="New end (ISO timestamp with offset; reschedule only)"/><Field name="reason" label="Reason (shared with your coach/client)"/></CoachingForm></Panel>)}{changes.map(c=><div key={c.id} className="my-4"><p>{c.change_type} · {c.status} · {c.reason}</p>{ctx.coach?.id===e.coach_id&&c.status==='pending'&&<div className="flex gap-4"><CoachingForm operation="resolve_session_change" hidden={{id:c.id,decision:'approve'}} button="Approve"/><CoachingForm operation="resolve_session_change" hidden={{id:c.id,decision:'decline'}} button="Decline"/></div>}</div>)}</Panel></>;
 }
 const closeout=(await rows(ctx,'coaching_engagement_closeouts','engagement_id',id))[0];
 return <><Panel title="Engagement Closeout"><div className="mb-4 flex flex-wrap gap-4"><Link className="underline" href={`/coaching/feedback?engagement=${id}`}>Give private closeout feedback</Link>{ctx.admin&&<Link className="underline" href={`/coaching/renewals?engagement=${id}`}>Continue with this coach or find another</Link>}</div><p className="mb-4">Closeout is available within 30 days of the planned end. Summaries entered here are organization-shared; keep private reflections in Notes.</p>{closeout&&<div className="mb-5"><p>Coach: {closeout.coach_shared_summary??'Pending'}</p><p>Leader: {closeout.coachee_shared_reflection??'Pending'}</p><p>Organization: {closeout.organization_outcome_notes??'Pending'}</p><p>Final status: {closeout.final_status??'Not finalized'}</p></div>}<CoachingForm operation="closeout" hidden={{engagement_id:id}} button="Submit closeout"><Field name="summary" label={ctx.admin&&!participant?'Organization outcomes and next steps':'Shared reflection, goals addressed and next steps'} type="textarea" required/><Select name="continue_recommended" label="Recommend continued coaching?" options={['false','true']}/>{ctx.admin&&<Select name="final_status" options={['completed','extended','renewed','terminated']} empty="Record feedback only"/>}</CoachingForm></Panel>{ctx.admin&&<Panel title="Extend Coaching"><CoachingForm operation="extend_engagement" hidden={{engagement_id:id}}><Field name="planned_end_date" type="date" value={e.planned_end_date} required/><Field name="planned_sessions" type="number" value={e.planned_sessions} required/><Field name="planned_hours" type="number" value={e.planned_hours} required/></CoachingForm></Panel>}</>;
}
