"use client";
import { useState } from "react";
type Assignment = { id: string; employeeName: string; roleTitle: string; department: string | null };
export function Review360Workspace({ assignments, cycles }: { assignments: Assignment[]; cycles: { id: string; title: string; employeeName: string; roleTitle: string; status: string; dueDate: string | null; completed: number; invited: number }[] }) {
  const [assignmentId, setAssignmentId] = useState(assignments[0]?.id ?? ""); const [title, setTitle] = useState(""); const [dueDate, setDueDate] = useState(""); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function createReview(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(null); const response = await fetch("/api/360-reviews", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employeeRoleAssignmentId: assignmentId, title, dueDate: dueDate || undefined }) }); const body = await response.json(); setSaving(false); if (!response.ok) { setMessage(body.error ?? "Unable to create review."); return; } window.location.reload(); }
  return <div className="grid gap-8"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Active 360 Reviews", cycles.filter(c=>["invitations_pending","in_progress"].includes(c.status)).length],["Awaiting Responses", cycles.reduce((sum,c)=>sum+c.invited-c.completed,0)],["Ready for Analysis", cycles.filter(c=>c.status==="ready_for_review").length],["Completed Reviews",cycles.filter(c=>c.status==="completed").length]].map(([label,value])=><div key={String(label)} className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-600">{label}</p><p className="mt-2 font-display text-4xl text-teal-900">{value}</p></div>)}</section>
  <section className="rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold tracking-[.16em] text-teal-700 uppercase">New review</p><h2 className="mt-2 font-display text-3xl text-slate-900">Create a current-role 360 review</h2><p className="mt-2 text-sm text-slate-600">The current Ideal Role Composite is snapshotted when you create the review.</p></div></div>{assignments.length ? <form onSubmit={createReview} className="mt-6 grid gap-4 md:grid-cols-3"><label className="grid gap-1 text-sm font-semibold text-slate-700">Employee and current role<select required value={assignmentId} onChange={e=>setAssignmentId(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2">{assignments.map(a=><option value={a.id} key={a.id}>{a.employeeName} — {a.roleTitle}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold text-slate-700">Review title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="2026 Baseline 360" className="rounded-xl border border-slate-300 px-3 py-2" /></label><label className="grid gap-1 text-sm font-semibold text-slate-700">Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2" /></label><button disabled={saving} className="w-fit rounded-full bg-teal-900 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Creating…" : "Create 360 Review"}</button></form> : <p className="mt-6 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Assign an employee’s current role before launching a 360 Review. This preserves the distinction between current-role feedback and future-role candidate assessment.</p>}{message?<p className="mt-3 text-sm text-red-700">{message}</p>:null}</section>
  <section className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="p-7"><p className="text-sm font-semibold tracking-[.16em] text-teal-700 uppercase">Active and completed reviews</p><h2 className="mt-2 font-display text-3xl text-slate-900">Review cycles</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-6 py-3">Employee</th><th>Role</th><th>Status</th><th>Responses</th><th>Due</th></tr></thead><tbody>{cycles.map(c=><tr key={c.id} className="border-t border-slate-100"><td className="px-6 py-4 font-semibold">{c.employeeName}</td><td>{c.roleTitle}</td><td className="capitalize">{c.status.replaceAll("_"," ")}</td><td>{c.completed} / {c.invited}</td><td>{c.dueDate ?? "—"}</td></tr>)}{!cycles.length?<tr><td colSpan={5} className="px-6 py-8 text-slate-500">No review cycles have been created.</td></tr>:null}</tbody></table></div></section></div>;
}
