"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import type { TemporaryTrainingProgram } from "@/lib/outside-training-programs";

type EditableProgram = TemporaryTrainingProgram;
const blank = { id: "", provider: "", name: "", description: "", websiteUrl: "", deliveryFormat: "", typicalDuration: "", intendedAudience: "", internalNote: "", competencyMatches: [{ competencyNames: [""], strength: "strong" as const, explanation: "" }] };

export function TrainingCatalogManager({ programs }: { programs: EditableProgram[] }) {
  const router = useRouter(); const [editing, setEditing] = useState<EditableProgram | typeof blank>(blank);
  const [message, setMessage] = useState<string | null>(null); const [isPending, startTransition] = useTransition();
  const setField = (key: keyof typeof blank, value: string) => setEditing((current) => ({ ...current, [key]: value }));
  function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(null); startTransition(async () => {
    const matches = editing.competencyMatches.map((match) => ({ competencyName: match.competencyNames[0]?.trim() ?? "", strength: match.strength, explanation: match.explanation }));
    const response = await fetch("/api/training-programs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editing.id || undefined, providerName: editing.provider, name: editing.name, description: editing.description, websiteUrl: editing.websiteUrl, deliveryFormats: editing.deliveryFormat.split(",").map((item) => item.trim()).filter(Boolean), audienceLevels: editing.intendedAudience.split(",").map((item) => item.trim()).filter(Boolean), typicalDuration: editing.typicalDuration, internalNotes: editing.internalNote, matches }) });
    const payload = await response.json() as { error?: string; message?: string }; setMessage(payload.error ?? payload.message ?? "Saved."); if (response.ok) { setEditing(blank); router.refresh(); }
  }); }
  function remove(id: string) { if (!confirm("Remove this training program?")) return; startTransition(async () => { const response = await fetch("/api/training-programs", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); const payload = await response.json() as { error?: string; message?: string }; setMessage(payload.error ?? payload.message ?? "Removed."); if (response.ok) { setEditing(blank); router.refresh(); } }); }
  return <details className="theme-panel rounded-[1.75rem] p-6"><summary className="cursor-pointer text-lg font-semibold text-slate-900">Manage training catalog</summary><p className="mt-3 text-sm leading-6 text-slate-600">Administrators can maintain providers, programs, and their competency matches. Program changes are immediately used by the finder.</p>
    <div className="mt-5 grid gap-2">{programs.map((program) => <div key={program.id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3"><span><b className="text-sm text-slate-900">{program.name}</b><small className="ml-2 text-slate-500">{program.provider}</small></span><span className="flex gap-3 text-sm font-semibold"><button type="button" className="text-teal-800" onClick={() => setEditing(program)}>Edit</button><button type="button" className="text-rose-700" onClick={() => remove(program.id)}>Remove</button></span></div>)}</div>
    <form onSubmit={save} className="mt-6 grid gap-3 border-t border-slate-200 pt-6 md:grid-cols-2">{([['provider','Provider'],['name','Program name'],['websiteUrl','Program website'],['typicalDuration','Typical duration'],['deliveryFormat','Formats (comma-separated)'],['intendedAudience','Audience levels (comma-separated)']] as const).map(([key,label]) => <label key={key} className="text-sm font-semibold text-slate-700">{label}<input required={key === 'provider' || key === 'name'} value={editing[key]} onChange={(event) => setField(key,event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal" /></label>)}
      <label className="text-sm font-semibold text-slate-700 md:col-span-2">Description<textarea required value={editing.description} onChange={(event) => setField('description',event.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal" /></label>
      <label className="text-sm font-semibold text-slate-700">Competency<label className="sr-only">Competency</label><input required value={editing.competencyMatches[0]?.competencyNames[0] ?? ''} onChange={(event) => setEditing((current) => ({ ...current, competencyMatches: [{ ...current.competencyMatches[0], competencyNames: [event.target.value] }] }))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Match strength<select value={editing.competencyMatches[0]?.strength ?? 'strong'} onChange={(event) => setEditing((current) => ({ ...current, competencyMatches: [{ ...current.competencyMatches[0], strength: event.target.value as 'strong'|'moderate'|'supporting' }] }))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal"><option value="strong">Strong</option><option value="moderate">Moderate</option><option value="supporting">Supporting</option></select></label>
      <label className="text-sm font-semibold text-slate-700 md:col-span-2">Why it matches<textarea required value={editing.competencyMatches[0]?.explanation ?? ''} onChange={(event) => setEditing((current) => ({ ...current, competencyMatches: [{ ...current.competencyMatches[0], explanation: event.target.value }] }))} className="mt-1 min-h-16 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal" /></label><div className="md:col-span-2"><button disabled={isPending} className="rounded-xl bg-teal-900 px-4 py-2 text-sm font-semibold text-white">{isPending ? 'Saving…' : editing.id ? 'Save changes' : 'Add program'}</button>{editing.id ? <button type="button" onClick={() => setEditing(blank)} className="ml-3 text-sm font-semibold text-slate-600">Cancel</button> : null}{message ? <p className="mt-2 text-sm text-slate-600">{message}</p> : null}</div></form></details>;
}
