-- Sprint 5: explicit human quality decisions and authorized analytics.
begin;
create schema coaching_scale_internal;
revoke all on schema coaching_scale_internal from public,anon,authenticated;
alter table coach_profiles add column marketplace_status text not null default 'approved' check(marketplace_status in ('approved','approved_limited','under_review','temporarily_unavailable','suspended','inactive')), add column credential_verified_at timestamptz, add column credential_verified_by uuid references auth.users(id), add column credential_verification_source text;
create table public.coaching_scale_versions(id uuid primary key default gen_random_uuid(),version text not null unique, minimum_outcome_sample_size integer not null default 5 check(minimum_outcome_sample_size>=5), minimum_feedback_sample_size integer not null default 5 check(minimum_feedback_sample_size>=3), outcome_matching_enabled boolean not null default false, requirements jsonb not null default '{"credential":false,"agreement":false,"payment":false,"orientation":false}', healthy_ratio numeric not null default 2 check(healthy_ratio>0), watch_ratio numeric not null default 1 check(watch_ratio>0), critical_ratio numeric not null default 0.5 check(critical_ratio>0), check(healthy_ratio>watch_ratio and watch_ratio>critical_ratio), created_by uuid references auth.users(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_scale_versions enable row level security;
revoke all on coaching_scale_versions from public,anon,authenticated;
create table public.coaching_feedback(id uuid primary key default gen_random_uuid(),engagement_id uuid not null references coaching_engagements(id), coach_id uuid not null references coach_profiles(id), submitted_by uuid not null references auth.users(id), respondent_type text not null check(respondent_type in ('coachee','organization')), overall_experience integer check(overall_experience between 1 and 5), goal_alignment integer check(goal_alignment between 1 and 5), communication integer check(communication between 1 and 5), reliability integer check(reliability between 1 and 5), professionalism integer check(professionalism between 1 and 5), development_value integer check(development_value between 1 and 5), would_recommend boolean, would_work_with_again boolean, comments text, visibility text not null default 'platform_private' check(visibility='platform_private'), submitted_at timestamptz not null default now(), unique(engagement_id,respondent_type),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_feedback enable row level security;
revoke all on coaching_feedback from public,anon,authenticated;
create table public.coach_quality_metrics(id uuid primary key default gen_random_uuid(),coach_id uuid not null references coach_profiles(id), metric_type text not null, metric_value numeric, metric_text text, measurement_period_start date not null, measurement_period_end date not null, sample_size integer not null, visibility text not null default 'coach_platform', definition_version text not null, calculation_method text not null, calculated_at timestamptz not null default now(), unique(coach_id,metric_type,measurement_period_start,measurement_period_end,definition_version),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coach_quality_metrics enable row level security;
revoke all on coach_quality_metrics from public,anon,authenticated;
create table public.coach_professional_development(id uuid primary key default gen_random_uuid(),coach_id uuid not null references coach_profiles(id), activity_type text not null check(activity_type in ('training','mentor_coaching','coaching_supervision','conference','certification','ethics_training','continuing_education','other')), title text not null, provider text, completion_date date not null, hours numeric check(hours between 0 and 10000), credential_related boolean not null default false, document_url text, notes text, supervisor text, supervision_type text,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coach_professional_development enable row level security;
revoke all on coach_professional_development from public,anon,authenticated;
create table public.coach_quality_flags(id uuid primary key default gen_random_uuid(),coach_id uuid not null references coach_profiles(id), engagement_id uuid references coaching_engagements(id), flag_type text not null, severity text not null check(severity in ('information','review','significant','urgent')), description text not null, status text not null default 'raised' check(status in ('raised','under_review','coach_response','additional_information','escalated','resolved')), reported_by uuid not null references auth.users(id), assigned_to uuid references auth.users(id), resolution text, outcome text, resolved_at timestamptz,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coach_quality_flags enable row level security;
revoke all on coach_quality_flags from public,anon,authenticated;
create table public.coach_quality_review_events(id uuid primary key default gen_random_uuid(),flag_id uuid not null references coach_quality_flags(id), actor uuid not null references auth.users(id), event_type text not null, content text not null, visibility text not null default 'platform_private' check(visibility in ('platform_private','coach_platform')),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coach_quality_review_events enable row level security;
revoke all on coach_quality_review_events from public,anon,authenticated;
create table public.coaching_conflicts(id uuid primary key default gen_random_uuid(),coach_id uuid not null references coach_profiles(id), coach_request_id uuid references coach_requests(id), engagement_id uuid references coaching_engagements(id), conflict_type text not null check(conflict_type in ('prior_relationship','current_relationship','financial_interest','organizational_relationship','personal_relationship','competitive_relationship','other')), description text not null, status text not null default 'declared' check(status in ('declared','under_review','cleared','recused')), reviewed_by uuid references auth.users(id), reviewed_at timestamptz, review_reason text, check(coach_request_id is not null or engagement_id is not null),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_conflicts enable row level security;
revoke all on coaching_conflicts from public,anon,authenticated;
create table public.organization_saved_coaches(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id), coach_id uuid not null references coach_profiles(id), saved_by uuid not null references auth.users(id), notes text, preferred boolean not null default false, approved_for_organization boolean not null default false, unique(organization_id,coach_id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table organization_saved_coaches enable row level security;
revoke all on organization_saved_coaches from public,anon,authenticated;
create table public.coaching_renewals(id uuid primary key default gen_random_uuid(),prior_engagement_id uuid not null references coaching_engagements(id), new_engagement_id uuid references coaching_engagements(id), new_request_id uuid unique references coach_requests(id), renewal_type text not null check(renewal_type in ('continue_same_coach','new_coach','extended_engagement','new_development_focus')), requested_by uuid not null references auth.users(id), status text not null default 'requested' check(status in ('requested','in_progress','completed','cancelled')), completed_at timestamptz,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_renewals enable row level security;
revoke all on coaching_renewals from public,anon,authenticated;
create table public.coaching_programs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id), name text not null, description text, start_date date not null, end_date date, program_owner uuid not null references auth.users(id), status text not null default 'planned' check(status in ('planned','active','completed','cancelled')), budget_amount numeric check(budget_amount between 0 and 1000000000), check(end_date is null or end_date>=start_date),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_programs enable row level security;
revoke all on coaching_programs from public,anon,authenticated;
create table public.coaching_program_participants(id uuid primary key default gen_random_uuid(),program_id uuid not null references coaching_programs(id), candidate_id uuid not null references candidates(id), engagement_id uuid references coaching_engagements(id), status text not null default 'active' check(status in ('active','completed','withdrawn')), added_at timestamptz not null default now(), completed_at timestamptz, unique(program_id,candidate_id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_program_participants enable row level security;
revoke all on coaching_program_participants from public,anon,authenticated;
create table public.coaching_engagement_participants(id uuid primary key default gen_random_uuid(),engagement_id uuid not null references coaching_engagements(id), user_id uuid not null references auth.users(id), participant_role text not null check(participant_role in ('coachee','coach')), unique(engagement_id,user_id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_engagement_participants enable row level security;
revoke all on coaching_engagement_participants from public,anon,authenticated;
create table public.coach_applications(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id), coach_id uuid not null unique references coach_profiles(id), status text not null default 'draft' check(status in ('draft','submitted','under_review','additional_information','approved','declined','withdrawn')), submitted_at timestamptz, reviewed_at timestamptz, reviewed_by uuid references auth.users(id), review_notes text,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coach_applications enable row level security;
revoke all on coach_applications from public,anon,authenticated;
create table public.coach_marketplace_agreements(id uuid primary key default gen_random_uuid(),version text not null unique, title text not null, terms text not null, published_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coach_marketplace_agreements enable row level security;
revoke all on coach_marketplace_agreements from public,anon,authenticated;
create table public.coach_marketplace_acceptances(id uuid primary key default gen_random_uuid(),coach_id uuid not null references coach_profiles(id), agreement_id uuid not null references coach_marketplace_agreements(id), accepted_by uuid not null references auth.users(id), accepted_at timestamptz not null default now(), unique(coach_id,agreement_id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coach_marketplace_acceptances enable row level security;
revoke all on coach_marketplace_acceptances from public,anon,authenticated;
create table public.coach_training_assignments(id uuid primary key default gen_random_uuid(),coach_id uuid not null references coach_profiles(id), title text not null, instructions text not null, required boolean not null default true, assigned_by uuid not null references auth.users(id), completed_at timestamptz, verified_at timestamptz, verified_by uuid references auth.users(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coach_training_assignments enable row level security;
revoke all on coach_training_assignments from public,anon,authenticated;
create table public.coaching_roi_measures(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id), engagement_id uuid references coaching_engagements(id), measure_name text not null, measure_type text not null, baseline_value numeric, target_value numeric, actual_value numeric, financial_value numeric, measurement_method text not null, data_sources text not null, assumptions text not null, period_start date not null, period_end date not null, entered_by uuid not null references auth.users(id), notes text, check(period_end>=period_start),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_roi_measures enable row level security;
revoke all on coaching_roi_measures from public,anon,authenticated;
create table public.coaching_program_feedback(id uuid primary key default gen_random_uuid(),program_id uuid not null references coaching_programs(id), submitted_by uuid not null references auth.users(id), satisfaction integer not null check(satisfaction between 1 and 5), matching integer check(matching between 1 and 5), administration integer check(administration between 1 and 5), billing integer check(billing between 1 and 5), development_value integer check(development_value between 1 and 5), comments text, unique(program_id,submitted_by),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_program_feedback enable row level security;
revoke all on coaching_program_feedback from public,anon,authenticated;
create table public.coaching_request_outcomes(id uuid primary key default gen_random_uuid(),coach_request_id uuid not null unique references coach_requests(id), reason text not null check(reason in ('no_suitable_coach','coach_declined','leader_declined','availability','price','organization_cancelled','development_need_changed','other')), explanation text, recorded_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_request_outcomes enable row level security;
revoke all on coaching_request_outcomes from public,anon,authenticated;
create table public.coaching_marketplace_events(id uuid primary key default gen_random_uuid(),organization_id uuid references organizations(id), event_type text not null check(event_type in ('view','search')), dimensions jsonb not null default '{}', result_count integer not null check(result_count>=0), day date not null default current_date, unique(organization_id,event_type,dimensions,day),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_marketplace_events enable row level security;
revoke all on coaching_marketplace_events from public,anon,authenticated;
create table public.coaching_retention_rules(id uuid primary key default gen_random_uuid(),record_category text not null check(record_category in ('coaching_logs','commercial_records','consent_records','analytics','coach_applications','quality_records','confidential_content')), retain_days integer check(retain_days>=1), disposition text not null check(disposition in ('review','delete','anonymize','restrict')), legal_basis text not null, created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_retention_rules enable row level security;
revoke all on coaching_retention_rules from public,anon,authenticated;
create table public.coaching_privacy_requests(id uuid primary key default gen_random_uuid(),organization_id uuid references organizations(id), subject_user_id uuid not null references auth.users(id), requested_by uuid not null references auth.users(id), action text not null check(action in ('delete','anonymize','retain','restrict_processing')), categories text[] not null, reason text not null, status text not null default 'requested' check(status in ('requested','under_review','approved','completed','declined')), decision_reason text, reviewed_by uuid references auth.users(id), execution_reference text,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_privacy_requests enable row level security;
revoke all on coaching_privacy_requests from public,anon,authenticated;
create table public.coaching_scale_snapshots(id uuid primary key default gen_random_uuid(),scope_key text not null, organization_id uuid references organizations(id), filters jsonb not null, data jsonb not null, definition_version text not null, calculated_at timestamptz not null default now(), unique(scope_key,filters),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_scale_snapshots enable row level security;
revoke all on coaching_scale_snapshots from public,anon,authenticated;
create table public.coaching_operating_costs(id uuid primary key default gen_random_uuid(),engagement_id uuid not null references coaching_engagements(id), cost_type text not null check(cost_type in ('acquisition','administration','other')), amount numeric not null check(amount between 0 and 1000000000), description text not null, entered_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default now());
alter table coaching_operating_costs enable row level security;
revoke all on coaching_operating_costs from public,anon,authenticated;
insert into coaching_scale_versions(version) values('scale-v1');
create function coaching_scale_internal.config() returns coaching_scale_versions language sql stable security definer set search_path=public as $$ select v from coaching_scale_versions v order by created_at desc limit 1 $$;
create function coaching_scale_internal.org() returns uuid language sql stable security definer set search_path=public as $$ select organization_id from profiles where auth_user_id=auth.uid() and deleted_at is null $$;
create function coaching_scale_internal.current_credential(c coach_profiles) returns boolean language sql stable as $$ select c.credential_verification_status='verified' and c.icf_credential not in ('none','other') and c.icf_credential_expiration_date is not null and c.icf_credential_expiration_date>=current_date $$;
create function coaching_scale_internal.readiness(cid uuid) returns jsonb language sql stable security definer set search_path=public as $$ select jsonb_build_object('profile',c.profile_status='approved','credential',coaching_scale_internal.current_credential(c),'agreement',exists(select 1 from coach_marketplace_acceptances where coach_id=cid and agreement_id=(select id from coach_marketplace_agreements order by created_at desc limit 1)),'payment',exists(select 1 from coach_payment_accounts where coach_id=cid and account_status='active' and payouts_enabled),'orientation',exists(select 1 from coach_training_assignments where coach_id=cid and required) and not exists(select 1 from coach_training_assignments where coach_id=cid and required and verified_at is null),'marketplace_status',c.marketplace_status) from coach_profiles c where id=cid $$;
create function coaching_scale_internal.eligible(cid uuid) returns boolean language plpgsql stable security definer set search_path=public as $$ declare cfg coaching_scale_versions; bits jsonb; k text; v jsonb;begin cfg:=coaching_scale_internal.config();bits:=coaching_scale_internal.readiness(cid);if bits is null or bits->>'profile'<>'true' or bits->>'marketplace_status' not in ('approved','approved_limited') then return false;end if;for k,v in select * from jsonb_each(cfg.requirements) loop if v='true' and coalesce(bits->>k,'false')<>'true' then return false;end if;end loop;return true;end $$;
alter function coaching_internal.eligible(uuid,boolean) rename to eligible_sprint2;
create function coaching_internal.eligible(cid uuid,override_capacity boolean default false) returns boolean language sql stable security definer set search_path=public as $$ select coaching_internal.eligible_sprint2(cid,override_capacity) and coaching_scale_internal.eligible(cid) $$;
-- Preserve the existing explicit marketplace projection and remove stale credential badges.
alter function public.coaching_marketplace() rename to coaching_marketplace_sprint4;
revoke all on function coaching_marketplace_sprint4() from public,anon,authenticated;
create function public.coaching_marketplace() returns jsonb language sql stable security definer set search_path=public as $$ select coalesce(jsonb_agg(x||jsonb_build_object('icf_credential',case when coaching_scale_internal.current_credential(c) then c.icf_credential else 'none' end,'credential_expired',c.icf_credential_expiration_date<current_date,'credential_label',case when coaching_scale_internal.current_credential(c) then upper(c.icf_credential) else 'Credential verification pending' end,'preferred',exists(select 1 from organization_saved_coaches where organization_id=coaching_scale_internal.org() and coach_id=c.id and preferred),'our_coach',exists(select 1 from organization_saved_coaches where organization_id=coaching_scale_internal.org() and coach_id=c.id and approved_for_organization),'similar_roles',(select coalesce(jsonb_agg(target_role_title),'[]') from coach_development_experience where coach_id=c.id and target_role_title is not null),'similar_needs',(select coalesce(jsonb_agg(need_type),'[]') from coach_development_experience where coach_id=c.id),'recently_available',c.accepting_clients and c.updated_at>=now()-interval '30 days')),'[]') from jsonb_array_elements(coaching_marketplace_sprint4()) x join coach_profiles c on c.id=(x->>'id')::uuid where coaching_scale_internal.eligible(c.id) $$;
create function coaching_scale_internal.audit(op text,item uuid,org uuid,detail jsonb default '{}') returns void language sql security definer set search_path=public as $$ insert into platform_audit_events(actor_profile_id,organization_id,event_type,details) values((select id from profiles where auth_user_id=auth.uid()),org,'coaching_scale.'||op,jsonb_build_object('record_id',item,'actor_user_id',auth.uid())||detail) $$;
create function public.coaching_scale_mutate(operation text,payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare item uuid:=nullif(payload->>'id','')::uuid; cid uuid:=nullif(payload->>'coach_id','')::uuid; eid uuid:=nullif(payload->>'engagement_id','')::uuid; org uuid:=coaching_scale_internal.org(); rid uuid:=nullif(payload->>'coach_request_id','')::uuid; result uuid; e coaching_engagements; c coach_profiles; p coaching_programs; f coach_quality_flags; a coach_applications; old coaching_privacy_requests; v text; n numeric; b jsonb;begin
if not coaching_identity_enabled() then raise exception 'Not authorized';end if;
if eid is not null then select * into e from coaching_engagements where id=eid;if e.id is null then raise exception 'Engagement unavailable';end if;org:=e.organization_id;cid:=e.coach_id;end if;
if cid is null then select id into cid from coach_profiles where user_id=auth.uid();end if;
select * into c from coach_profiles where id=cid;
for v in select unnest(array['baseline_value','target_value','actual_value','financial_value','hours','budget_amount','amount']) loop if nullif(payload->>v,'') is not null then n:=(payload->>v)::numeric;if n::text in ('NaN','Infinity','-Infinity') then raise exception 'Finite numeric values required';end if;end if;end loop;
if operation in ('config','credential','marketplace_status','flag_review','conflict_review','application_review','agreement_publish','training_assign','training_verify','retention','privacy_review','operating_cost') and not coaching_platform_admin() then raise exception 'Platform administrator required';end if;
if operation='config' then
 b:=payload->'requirements';if jsonb_typeof(b)<>'object' or not b ?& array['credential','agreement','payment','orientation'] or (select count(*) from jsonb_object_keys(b))<>4 or exists(select 1 from jsonb_each(b) where jsonb_typeof(value)<>'boolean') then raise exception 'Four boolean eligibility requirements required';end if;
 insert into coaching_scale_versions(version,minimum_outcome_sample_size,minimum_feedback_sample_size,outcome_matching_enabled,requirements,healthy_ratio,watch_ratio,critical_ratio,created_by) values(payload->>'version',(payload->>'minimum_outcome_sample_size')::int,(payload->>'minimum_feedback_sample_size')::int,coalesce((payload->>'outcome_matching_enabled')::boolean,false),b,(payload->>'healthy_ratio')::numeric,(payload->>'watch_ratio')::numeric,(payload->>'critical_ratio')::numeric,auth.uid()) returning id into result;
elsif operation='credential' then
 if c.id is null or nullif(trim(payload->>'verification_source'),'') is null then raise exception 'Coach and verification source required';end if;
 update coach_profiles set icf_credential=payload->>'credential',icf_credential_number=payload->>'credential_number',icf_credential_issue_date=nullif(payload->>'issue_date','')::date,icf_credential_expiration_date=nullif(payload->>'expiration_date','')::date,credential_verification_status=payload->>'verification_status',credential_verified_at=now(),credential_verified_by=auth.uid(),credential_verification_source=payload->>'verification_source' where id=cid returning id into result;
 if payload->>'verification_status'='verified' and (nullif(payload->>'expiration_date','') is null or (payload->>'expiration_date')::date<current_date) then raise exception 'A verified credential requires a current expiration date';end if;
elsif operation='marketplace_status' then
 if length(trim(coalesce(payload->>'reason','')))<5 then raise exception 'Human review reason required';end if;
 update coach_profiles set marketplace_status=payload->>'status',profile_status=case when payload->>'status'='suspended' then 'suspended' when payload->>'status'='inactive' then 'inactive' when payload->>'status' in ('approved','approved_limited') and approved_at is not null then 'approved' else profile_status end where id=cid returning id into result;
elsif operation='feedback' then
 if e.id is null or e.status<>'completed' then raise exception 'Feedback is available at completed engagement closeout';end if;
 v:=payload->>'respondent_type';if not ((v='coachee' and coaching_is_client(eid)) or (v='organization' and coaching_admin(org))) then raise exception 'Feedback respondent not authorized';end if;
 if nullif(payload->>'overall_experience','') is null then raise exception 'Overall experience is required';end if;
 insert into coaching_feedback(engagement_id,coach_id,submitted_by,respondent_type,overall_experience,goal_alignment,communication,reliability,professionalism,development_value,would_recommend,would_work_with_again,comments) values(eid,cid,auth.uid(),v,(payload->>'overall_experience')::int,nullif(payload->>'goal_alignment','')::int,nullif(payload->>'communication','')::int,nullif(payload->>'reliability','')::int,nullif(payload->>'professionalism','')::int,nullif(payload->>'development_value','')::int,nullif(payload->>'would_recommend','')::boolean,nullif(payload->>'would_work_with_again','')::boolean,payload->>'comments') returning id into result;
elsif operation='professional_development' then
 if not coaching_internal.owner(cid) then raise exception 'Coach account required';end if;
 if nullif(payload->>'document_url','') is not null and payload->>'document_url' !~ '^https://' then raise exception 'Use an HTTPS document URL';end if;
 insert into coach_professional_development(coach_id,activity_type,title,provider,completion_date,hours,credential_related,document_url,notes,supervisor,supervision_type) values(cid,payload->>'activity_type',nullif(trim(payload->>'title'),''),payload->>'provider',(payload->>'completion_date')::date,nullif(payload->>'hours','')::numeric,coalesce((payload->>'credential_related')::boolean,false),payload->>'document_url',payload->>'notes',payload->>'supervisor',payload->>'supervision_type') returning id into result;
elsif operation='flag' then
 if not (coaching_platform_admin() or (e.id is not null and (coaching_admin(org) or coaching_is_client(eid)))) then raise exception 'Authorized engagement participant required';end if;
 insert into coach_quality_flags(coach_id,engagement_id,flag_type,severity,description,reported_by) values(cid,eid,payload->>'flag_type',payload->>'severity',nullif(trim(payload->>'description'),''),auth.uid()) returning id into result;
elsif operation in ('flag_review','flag_response') then
 select * into f from coach_quality_flags where id=item for update;if f.id is null then raise exception 'Review unavailable';end if;
 if operation='flag_response' then if f.status='resolved' or not coaching_internal.owner(f.coach_id) or not exists(select 1 from coach_quality_review_events where flag_id=item and visibility='coach_platform') then raise exception 'Coach response has not been requested';end if;v:='coach_response';else v:=payload->>'status';end if;
 insert into coach_quality_review_events(flag_id,actor,event_type,content,visibility) values(item,auth.uid(),v,nullif(trim(payload->>'content'),''),case when operation='flag_response' then 'coach_platform' else coalesce(payload->>'visibility','platform_private') end);
 update coach_quality_flags set status=v,assigned_to=case when operation='flag_review' then auth.uid() else assigned_to end,resolution=case when v='resolved' then payload->>'content' else resolution end,outcome=case when v='resolved' then payload->>'outcome' else outcome end,resolved_at=case when v='resolved' then now() else null end where id=item;result:=item;
 -- A resolution records a human outcome; any marketplace status change is a separate reviewed action.
elsif operation='conflict' then
 if not coaching_internal.owner(cid) or not ((e.id is not null and e.coach_id=cid) or exists(select 1 from coaching_invitations where coach_request_id=rid and coach_id=cid)) then raise exception 'Assigned opportunity or engagement required';end if;
 insert into coaching_conflicts(coach_id,coach_request_id,engagement_id,conflict_type,description) values(cid,rid,eid,payload->>'conflict_type',nullif(trim(payload->>'description'),'')) returning id into result;
elsif operation='conflict_review' then
 if length(trim(coalesce(payload->>'reason','')))<5 then raise exception 'Human decision reason required';end if;
 update coaching_conflicts set status=payload->>'status',reviewed_by=auth.uid(),reviewed_at=now(),review_reason=payload->>'reason' where id=item returning id into result;
elsif operation='saved_coach' then
 if not coaching_admin(org) or not coaching_scale_internal.eligible(cid) then raise exception 'Organization administrator and eligible coach required';end if;
 insert into organization_saved_coaches(organization_id,coach_id,saved_by,notes,preferred,approved_for_organization) values(org,cid,auth.uid(),payload->>'notes',coalesce((payload->>'preferred')::boolean,false),coalesce((payload->>'approved_for_organization')::boolean,false)) on conflict(organization_id,coach_id) do update set notes=excluded.notes,preferred=excluded.preferred,approved_for_organization=excluded.approved_for_organization returning id into result;
elsif operation='renewal' then
 if not coaching_admin(org) or e.status<>'completed' then raise exception 'Organization administrator and completed engagement required';end if;
 if exists(select 1 from coaching_renewals where prior_engagement_id=eid and status in ('requested','in_progress')) then raise exception 'A renewal is already in progress';end if;
 result:=coaching_mutate('request_save',jsonb_build_object('requested_for_user_id',e.coachee_user_id,'request_title',e.title||' — continuation','development_focus',coalesce(payload->>'focus',e.organization_objectives),'objectives',jsonb_build_array('Improve Leadership Effectiveness'),'submit',false));
 insert into coaching_renewals(prior_engagement_id,new_request_id,renewal_type,requested_by) values(eid,result,payload->>'renewal_type',auth.uid());
 if payload->>'renewal_type'<>'new_coach' then update coach_requests set coach_id=e.coach_id where id=result;end if;
 -- Reuse request selection, new consents and new commerce. Never copy notes or permissions.
elsif operation='program' then
 if not coaching_admin(org) then raise exception 'Organization administrator required';end if;
 if item is null then insert into coaching_programs(organization_id,name,description,start_date,end_date,program_owner,status,budget_amount) values(org,nullif(trim(payload->>'name'),''),payload->>'description',(payload->>'start_date')::date,nullif(payload->>'end_date','')::date,auth.uid(),payload->>'status',nullif(payload->>'budget_amount','')::numeric) returning id into result;
 else update coaching_programs set status=payload->>'status' where id=item and organization_id=org returning id into result;end if;
elsif operation in ('participant','program_feedback') then
 select * into p from coaching_programs where id=(payload->>'program_id')::uuid;if p.id is null or not coaching_admin(p.organization_id) then raise exception 'Program administrator required';end if;org:=p.organization_id;
 if operation='participant' then
 if not exists(select 1 from candidates where id=(payload->>'candidate_id')::uuid and organization_id=org and deleted_at is null) or (eid is not null and (e.organization_id<>org or e.candidate_id is distinct from (payload->>'candidate_id')::uuid)) then raise exception 'Candidate and engagement must belong to program organization';end if;
 insert into coaching_program_participants(program_id,candidate_id,engagement_id,status) values(p.id,(payload->>'candidate_id')::uuid,eid,payload->>'status') on conflict(program_id,candidate_id) do update set engagement_id=excluded.engagement_id,status=excluded.status,completed_at=case when excluded.status='completed' then now() end returning id into result;
 else insert into coaching_program_feedback(program_id,submitted_by,satisfaction,matching,administration,billing,development_value,comments) values(p.id,auth.uid(),(payload->>'satisfaction')::int,nullif(payload->>'matching','')::int,nullif(payload->>'administration','')::int,nullif(payload->>'billing','')::int,nullif(payload->>'development_value','')::int,payload->>'comments') returning id into result;end if;
elsif operation='roi' then
 if not coaching_admin(org) then raise exception 'Organization administrator required';end if;
 insert into coaching_roi_measures(organization_id,engagement_id,measure_name,measure_type,baseline_value,target_value,actual_value,financial_value,measurement_method,data_sources,assumptions,period_start,period_end,entered_by,notes) values(org,eid,nullif(trim(payload->>'measure_name'),''),payload->>'measure_type',nullif(payload->>'baseline_value','')::numeric,nullif(payload->>'target_value','')::numeric,nullif(payload->>'actual_value','')::numeric,nullif(payload->>'financial_value','')::numeric,nullif(trim(payload->>'measurement_method'),''),nullif(trim(payload->>'data_sources'),''),nullif(trim(payload->>'assumptions'),''),(payload->>'period_start')::date,(payload->>'period_end')::date,auth.uid(),payload->>'notes') returning id into result;
elsif operation='application' then
 select * into a from coach_applications where user_id=auth.uid();
 if a.id is null then
 if cid is null then insert into coach_profiles(user_id,display_name,profile_status) values(auth.uid(),nullif(trim(payload->>'display_name'),''),'draft') returning id into cid;end if;
 if not coaching_internal.owner(cid) then raise exception 'Own coach profile required';end if;
 insert into coach_applications(user_id,coach_id) values(auth.uid(),cid) returning id into item;else item:=a.id;end if;
 if payload->>'status' not in ('draft','submitted','withdrawn') then raise exception 'Invalid application transition';end if;
 update coach_applications set status=payload->>'status',submitted_at=case when payload->>'status'='submitted' then now() else submitted_at end where id=item and status not in ('approved','declined') returning id into result;
elsif operation='application_review' then
 if payload->>'status' is null or payload->>'status' not in ('under_review','additional_information','approved','declined') or length(trim(coalesce(payload->>'review_notes','')))<5 then raise exception 'Human application decision and review notes required';end if;
 select * into a from coach_applications where id=item for update;
 if payload->>'status'='approved' and not exists(select 1 from coach_profiles where id=a.coach_id and length(trim(coalesce(headline,'')))>0 and length(trim(coalesce(short_bio,'')))>0) then raise exception 'Complete the coach profile before approval';end if;
 update coach_applications set status=payload->>'status',review_notes=nullif(trim(payload->>'review_notes'),''),reviewed_by=auth.uid(),reviewed_at=now() where id=item returning id into result;
 if payload->>'status'='approved' then update coach_profiles set profile_status='approved',approved_at=now(),approved_by=auth.uid() where id=a.coach_id;end if;
elsif operation='agreement_publish' then insert into coach_marketplace_agreements(version,title,terms,published_by) values(nullif(trim(payload->>'version'),''),nullif(trim(payload->>'title'),''),nullif(trim(payload->>'terms'),''),auth.uid()) returning id into result;
elsif operation='agreement_accept' then
 if not coaching_internal.owner(cid) or coalesce(payload->>'attest','false')<>'true' then raise exception 'Coach attestation required';end if;
 if item is distinct from (select id from coach_marketplace_agreements order by created_at desc limit 1) then raise exception 'Review the current agreement';end if;
 insert into coach_marketplace_acceptances(coach_id,agreement_id,accepted_by) values(cid,item,auth.uid()) on conflict(coach_id,agreement_id) do update set accepted_by=excluded.accepted_by returning id into result;
elsif operation='training_assign' then insert into coach_training_assignments(coach_id,title,instructions,assigned_by) values(cid,nullif(trim(payload->>'title'),''),nullif(trim(payload->>'instructions'),''),auth.uid()) returning id into result;
elsif operation='training_complete' then update coach_training_assignments set completed_at=now() where id=item and coaching_internal.owner(coach_id) returning id into result;
elsif operation='training_verify' then update coach_training_assignments set verified_at=now(),verified_by=auth.uid() where id=item and completed_at is not null returning id into result;
elsif operation='request_outcome' then
 if not coaching_internal.request_admin(rid) then raise exception 'Request administrator required';end if;
 insert into coaching_request_outcomes(coach_request_id,reason,explanation,recorded_by) values(rid,payload->>'reason',payload->>'explanation',auth.uid()) on conflict(coach_request_id) do update set reason=excluded.reason,explanation=excluded.explanation returning id into result;
elsif operation='retention' then insert into coaching_retention_rules(record_category,retain_days,disposition,legal_basis,created_by) values(payload->>'record_category',nullif(payload->>'retain_days','')::int,payload->>'disposition',nullif(trim(payload->>'legal_basis'),''),auth.uid()) returning id into result;
elsif operation='privacy_request' then
 if (payload->>'subject_user_id')::uuid is distinct from auth.uid() and not coaching_admin(org) then raise exception 'Own privacy request or organization administrator required';end if;
 if (payload->>'subject_user_id')::uuid is distinct from auth.uid() and not exists(select 1 from profiles where auth_user_id=(payload->>'subject_user_id')::uuid and organization_id=org) then raise exception 'Subject must belong to organization';end if;
 insert into coaching_privacy_requests(organization_id,subject_user_id,requested_by,action,categories,reason) values(org,(payload->>'subject_user_id')::uuid,auth.uid(),payload->>'action',array(select jsonb_array_elements_text(payload->'categories')),nullif(trim(payload->>'reason'),'')) returning id into result;
elsif operation='privacy_review' then
 select * into old from coaching_privacy_requests where id=item for update;
 if payload->>'status'='completed' and length(trim(coalesce(payload->>'execution_reference','')))<5 then raise exception 'Document execution or retained-record decision before completion';end if;
 update coaching_privacy_requests set status=payload->>'status',decision_reason=nullif(trim(payload->>'decision_reason'),''),reviewed_by=auth.uid(),execution_reference=payload->>'execution_reference' where id=item returning id into result;
 -- Retention workflow records review and verified execution references, never automatically erases ledgers.
elsif operation='operating_cost' then insert into coaching_operating_costs(engagement_id,cost_type,amount,description,entered_by) values(eid,payload->>'cost_type',(payload->>'amount')::numeric,nullif(trim(payload->>'description'),''),auth.uid()) returning id into result;
else raise exception 'Unsupported operation';end if;
if result is null then raise exception 'Record unavailable or invalid transition';end if;
perform coaching_scale_internal.audit(operation,result,org,case when operation='marketplace_status' then jsonb_build_object('human_reason',payload->>'reason','status',payload->>'status') else '{}'::jsonb end);return result;end $$;
alter table coaching_engagements add column first_activated_at timestamptz, add column completed_at timestamptz;
create function coaching_scale_internal.engagement_guard() returns trigger language plpgsql security definer set search_path=public as $$ begin
if new.status='active' and (tg_op='INSERT' or old.status is distinct from 'active') then
 if not coaching_scale_internal.eligible(new.coach_id) or exists(select 1 from coaching_conflicts where coach_id=new.coach_id and (coach_request_id=new.coach_request_id or engagement_id=new.id) and status<>'cleared') then raise exception 'Marketplace eligibility and conflict review required before activation';end if;
 new.first_activated_at:=coalesce(old.first_activated_at,now());end if;
if new.status='completed' and (tg_op='INSERT' or old.status is distinct from 'completed') then new.completed_at:=now();end if;
return new;end $$;
create trigger coaching_scale_engagement_guard before insert or update on coaching_engagements for each row execute function coaching_scale_internal.engagement_guard();
create function coaching_scale_internal.link_renewal() returns trigger language plpgsql security definer set search_path=public as $$ begin
 update coaching_renewals set new_engagement_id=new.id,status=case when new.status='active' then 'completed' else 'in_progress' end,completed_at=case when new.status='active' then now() end where new_request_id=new.coach_request_id and status not in ('completed','cancelled');
 insert into coaching_engagement_participants(engagement_id,user_id,participant_role) values(new.id,new.coachee_user_id,'coachee') on conflict do nothing;return new;end $$;
create trigger coaching_scale_link_renewal after insert or update of status on coaching_engagements for each row execute function coaching_scale_internal.link_renewal();
insert into coaching_engagement_participants(engagement_id,user_id,participant_role) select id,coachee_user_id,'coachee' from coaching_engagements;
create function coaching_scale_internal.invitation_guard() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if new.status in ('pending','interested','converted') and exists(select 1 from coaching_conflicts where coach_id=new.coach_id and coach_request_id=new.coach_request_id and status<>'cleared') then raise exception 'Resolve the declared conflict before continuing this opportunity';end if;return new;end $$;
create trigger coaching_scale_invitation_guard before insert or update of status on coaching_invitations for each row execute function coaching_scale_internal.invitation_guard();
create function coaching_scale_internal.quality_refresh() returns void language plpgsql security definer set search_path=public as $$ declare c coach_profiles; cfg coaching_scale_versions;begin cfg:=coaching_scale_internal.config();
for c in select * from coach_profiles loop
insert into coach_quality_metrics(coach_id,metric_type,metric_value,metric_text,measurement_period_start,measurement_period_end,sample_size,definition_version,calculation_method)
select c.id,type,value,detail,current_date-365,current_date,n,cfg.version,method from (
 select 'engagement_completion_rate' type,round(100.0*count(*) filter(where status='completed')/nullif(count(*),0),1) value,null::text detail,count(*)::int n,'Completed / engagements with observed activation or active, paused, completed status in the trailing-year creation cohort.' method from coaching_engagements where coach_id=c.id and created_at>=current_date-365 and (first_activated_at is not null or status in ('active','paused','completed'))
 union all select 'session_completion_rate',round(100.0*count(*) filter(where status='completed')/nullif(count(*),0),1),null,count(*)::int,'Completed / sessions due by today; rescheduled sessions excluded.' from coaching_sessions where coach_id=c.id and session_date between current_date-365 and current_date and status<>'rescheduled'
 union all select 'documentation_compliance',round(100.0*count(*) filter(where coach_confirmed and actual_start_at is not null and actual_end_at is not null)/nullif(count(*),0),1),null,count(*)::int,'Completed sessions with coach confirmation and actual times / completed sessions. Notes are not inspected.' from coaching_sessions where coach_id=c.id and session_date>=current_date-365 and status='completed'
 union all select respondent_type||'_experience',case when count(distinct engagement_id)>=cfg.minimum_feedback_sample_size then round(avg(overall_experience),2) end,case when count(distinct engagement_id)<cfg.minimum_feedback_sample_size then 'More completed-engagement feedback is needed before displaying this metric.' end,count(distinct engagement_id)::int,'Mean optional overall experience (1–5); at least the configured number of distinct completed engagements required. Written feedback stays platform-private.' from coaching_feedback where coach_id=c.id and submitted_at>=current_date-365 group by respondent_type
 union all select 'goal_progress_rate',round(100.0*count(*) filter(where g.status='achieved')/nullif(count(*),0),1),null,count(*)::int,'Achieved / explicitly organization-shared goals with current reporting consent.' from coaching_goals g join coaching_engagements e on e.id=g.engagement_id where e.coach_id=c.id and g.created_at>=current_date-365 and g.visibility='organization_shared' and coaching_has_consent(e.id,'organization_reporting')
 union all select 'development_milestone_rate',count(*)::numeric,null,count(distinct x.coaching_engagement_id)::int,'Explicitly shared development milestones; sample is distinct engagements. Activity is not proof of causation.' from development_evidence x join coaching_engagements e on e.id=x.coaching_engagement_id where e.coach_id=c.id and x.created_at>=current_date-365 and x.visibility in ('organization','readiness_review') and coaching_has_consent(e.id,'organization_reporting')
 union all select 'repeat_engagement_rate',count(*)::numeric,null,count(distinct r.prior_engagement_id)::int,'Completed same-coach renewal workflows; sample is distinct prior engagements.' from coaching_renewals r join coaching_engagements e on e.id=r.prior_engagement_id where e.coach_id=c.id and r.status='completed' and r.renewal_type<>'new_coach' and r.created_at>=current_date-365
 union all select 'coach_response_time',round(avg(extract(epoch from responded_at-invited_at)/3600)::numeric,1),null,count(*)::int,'Hours from invitation to response; only responded invitations.' from coaching_invitations where coach_id=c.id and responded_at is not null and invited_at>=current_date-365
 union all select 'credential_status',null,case when coaching_scale_internal.current_credential(c) then 'Current verified credential' else 'Credential verification pending or expired' end,1,'Live credential verification and expiration; current badge is evaluated on every marketplace read.'
) m on conflict(coach_id,metric_type,measurement_period_start,measurement_period_end,definition_version) do update set metric_value=excluded.metric_value,metric_text=excluded.metric_text,sample_size=excluded.sample_size,calculated_at=now();
end loop;end $$;
create function coaching_scale_internal.analytics(filters jsonb,org uuid default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare date_from date:=coalesce(nullif(filters->>'from','')::date,date_trunc('year',current_date)::date); date_to date:=coalesce(nullif(filters->>'to','')::date,current_date); coach uuid:=nullif(filters->>'coach','')::uuid; spec uuid:=nullif(filters->>'specialty','')::uuid; industry uuid:=nullif(filters->>'industry','')::uuid; levelid uuid:=nullif(filters->>'leadership_level','')::uuid; package uuid:=nullif(filters->>'package','')::uuid; result jsonb;begin
if date_to<date_from or date_to-date_from>3660 then raise exception 'Choose a period of ten years or less';end if;
with engagements as (select e.* from coaching_engagements e where (org is null or e.organization_id=org) and e.created_at::date between date_from and date_to and (coach is null or e.coach_id=coach) and (spec is null or exists(select 1 from coach_specialties where coach_id=e.coach_id and specialty_id=spec)) and (industry is null or exists(select 1 from coach_industries where coach_id=e.coach_id and industry_id=industry)) and (levelid is null or exists(select 1 from coach_leadership_levels where coach_id=e.coach_id and leadership_level_id=levelid)) and (package is null or exists(select 1 from coaching_quotes q join coaching_commercial_agreements a on a.quote_id=q.id where q.engagement_id=e.id and q.package_id=package))),
requests as (select r.* from coach_requests r where (org is null or organization_id=org) and submitted_at::date between date_from and date_to and (coach is null or coach_id=coach or exists(select 1 from coaching_invitations i where i.coach_request_id=r.id and i.coach_id=coach)) and (spec is null or spec=any(specialty_ids)) and (industry is null or preferred_industry_id=industry) and (levelid is null or preferred_leadership_level_id=levelid) and (package is null or exists(select 1 from engagements where coach_request_id=r.id))),
invites as (select i.* from coaching_invitations i join requests r on r.id=i.coach_request_id),
proof as (select x.* from development_evidence x join engagements e on e.id=x.coaching_engagement_id where x.visibility in ('organization','readiness_review') and coaching_has_consent(e.id,'organization_reporting')),
needs as (select n.* from leadership_development_needs n where (org is null or n.organization_id=org) and n.created_at::date between date_from and date_to and development_internal.source_visible(n) and (coach is null or exists(select 1 from engagements e where e.candidate_id=n.candidate_id))),
finance as (select r.* from coaching_platform_revenue r join engagements e on e.id=r.engagement_id),
funnel as (select jsonb_build_object('Marketplace views',(select count(*) from coaching_marketplace_events where (org is null or organization_id=org) and day between date_from and date_to and event_type='view'),'Activation requests',(select count(*) from coaching_opt_in_requests where (org is null or organization_id=org) and created_at::date between date_from and date_to),'Coaching activated',(select count(*) from organization_features where feature_key='coaching' and status='active' and (org is null or organization_id=org)),'Coaching requests',(select count(*) from requests),'Requests with matches',(select count(*) from requests r where exists(select 1 from coaching_match_results where coach_request_id=r.id)),'Coach invitations',(select count(*) from invites),'Coach interested',(select count(*) from invites where status in ('interested','converted')),'Leader accepted',(select count(*) from requests where leader_accepted_at is not null),'Engagements created',(select count(*) from engagements),'Engagements activated',(select count(*) from engagements where first_activated_at is not null or status in ('active','paused','completed')),'Engagements completed',(select count(*) from engagements where status='completed'),'Renewed',(select count(*) from coaching_renewals where prior_engagement_id in(select id from engagements) and status='completed')) value)
select jsonb_build_object('period',jsonb_build_object('from',date_from,'to',date_to),'funnel',(select value from funnel),'metrics',jsonb_build_object(
'Leaders coached',(select count(distinct coachee_user_id) from engagements where first_activated_at is not null or status in ('active','paused','completed')),'Active engagements',(select count(*) from engagements where status='active'),'Completed engagements',(select count(*) from engagements where status='completed'),'Coaching hours',(select coalesce(round(sum(s.duration_minutes)/60,1),0) from coaching_sessions s join engagements e on e.id=s.engagement_id where s.status='completed'),'Competencies with shared evidence',(select count(distinct competency_id) from proof),'Open requests',(select count(*) from requests where status not in ('converted_to_engagement','closed','cancelled','declined')),'Leader acceptance rate',(select round(100.0*count(*) filter(where leader_accepted_at is not null)/nullif(count(*) filter(where exists(select 1 from invites i where i.coach_request_id=r.id and i.status in ('interested','converted'))),0),1) from requests r),'Renewal rate',(select round(100.0*count(*) filter(where exists(select 1 from coaching_renewals where prior_engagement_id=e.id and status='completed'))/nullif(count(*),0),1) from engagements e where status='completed'),'Match acceptance rate',(select round(100.0*count(*) filter(where status in ('interested','converted'))/nullif(count(*),0),1) from invites),'Completion rate',(select round(100.0*count(*) filter(where status='completed')/nullif(count(*) filter(where first_activated_at is not null or status in ('active','paused','completed')),0),1) from engagements),'Shared goals achieved',(select count(*) from coaching_goals g join engagements e on e.id=g.engagement_id where g.status='achieved' and g.visibility='organization_shared' and coaching_has_consent(e.id,'organization_reporting')),'Shared evidence',(select count(*) from proof),'Development priorities addressed',(select count(distinct development_need_id) from development_plan_steps where development_need_id in(select id from needs) and status in ('active','completed')),'Readiness reviews',(select count(*) from readiness_history where candidate_id in(select candidate_id from engagements) and changed_at::date between date_from and date_to),'High-priority development coverage',(select round(100.0*count(*) filter(where exists(select 1 from development_plan_steps where development_need_id=n.id and status='active'))/nullif(count(*),0),1) from needs n where priority in ('high','urgent')),'High-priority needs',(select count(*) from needs where priority in ('high','urgent')),'High-priority needs with active plan',(select count(*) from needs n where priority in ('high','urgent') and exists(select 1 from development_plan_steps where development_need_id=n.id and status='active'))),
'time_to_match',jsonb_build_object('First match hours',(select round(avg(extract(epoch from ((select min(created_at) from coaching_match_results where coach_request_id=r.id)-r.submitted_at))/3600)::numeric,1) from requests r),'Coach interest hours',(select round(avg(extract(epoch from ((select min(responded_at) from invites where coach_request_id=r.id and status in ('interested','converted'))-r.submitted_at))/3600)::numeric,1) from requests r),'Leader acceptance hours',(select round(avg(extract(epoch from (leader_accepted_at-submitted_at))/3600)::numeric,1) from requests),'Active engagement hours',(select round(avg(extract(epoch from (e.first_activated_at-r.submitted_at))/3600)::numeric,1) from engagements e join requests r on r.id=e.coach_request_id)),
'financial',case when org is null then jsonb_build_object('Average agreed engagement value',(select round(avg(organization_price),2) from coaching_commercial_agreements where engagement_id in(select id from engagements)),'Outstanding receivables',(select coalesce(sum(amount),0) from coaching_payments where engagement_id in(select id from engagements) and status in ('pending','processing','failed')),'Renewal receipts',(select coalesce(sum(f.organization_revenue),0) from finance f where f.engagement_id in(select new_engagement_id from coaching_renewals where status='completed')),'Gross coaching receipts',(select coalesce(sum(organization_revenue),0) from finance),'Coach compensation',(select coalesce(sum(coach_cost),0) from finance),'Payment processing cost',(select coalesce(sum(payment_processing_cost),0) from finance),'Refunds',(select coalesce(sum(refund_amount),0) from finance),'Platform revenue',(select coalesce(sum(net_platform_revenue),0) from finance),'Entered operating costs',(select coalesce(sum(amount),0) from coaching_operating_costs where engagement_id in(select id from engagements)),'Contribution after entered costs',(select coalesce(sum(net_platform_revenue),0) from finance)-(select coalesce(sum(amount),0) from coaching_operating_costs where engagement_id in(select id from engagements))) else jsonb_build_object('Coaching investment',(select coalesce(sum(p.amount),0) from coaching_payments p join engagements e on e.id=p.engagement_id where p.status in ('paid','partially_refunded','refunded'))-(select coalesce(sum(amount),0) from coaching_refunds where engagement_id in(select id from engagements) and status='completed')) end,
'competencies',(select coalesce(jsonb_agg(x),'[]') from (select rc.name competency,count(distinct n.candidate_id) leaders,count(*) filter(where 'coaching'=any(n.recommended_response)) coaching_needs,(select count(*) from development_plan_steps p where p.development_need_id in(select id from needs where competency_id=rc.id) and p.method='mentoring') mentoring,(select count(*) from development_plan_steps p where p.development_need_id in(select id from needs where competency_id=rc.id) and p.method='project') projects,(select count(*) from proof where competency_id=rc.id) evidence,count(*) filter(where n.status not in ('resolved','dismissed')) remaining_needs from needs n join role_competencies rc on rc.id=n.competency_id group by rc.id,rc.name) x),
'revenue_by_coach',case when org is null then (select coalesce(jsonb_agg(x),'[]') from (select c.display_name coach,sum(f.organization_revenue) receipts,sum(f.coach_cost) compensation,sum(f.net_platform_revenue) platform_revenue from finance f join engagements e on e.id=f.engagement_id join coach_profiles c on c.id=e.coach_id group by c.id,c.display_name) x) else '[]'::jsonb end,
'revenue_by_organization',case when org is null then (select coalesce(jsonb_agg(x),'[]') from (select o.name organization,sum(f.organization_revenue) receipts,sum(f.net_platform_revenue) platform_revenue from finance f join engagements e on e.id=f.engagement_id join organizations o on o.id=e.organization_id group by o.id,o.name) x) else '[]'::jsonb end,
'roles',(select coalesce(jsonb_agg(x),'[]') from (select r.title role,count(distinct e.candidate_id) leaders,count(distinct e.id) engagements from engagements e join candidates c on c.id=e.candidate_id join roles r on r.id=c.target_role_id group by r.id,r.title) x),
'readiness_movement',(select coalesce(jsonb_agg(x),'[]') from (select case when new_readiness is null or previous_readiness is null then 'No comparable score' when new_readiness=previous_readiness then 'Score retained' when new_readiness>previous_readiness then 'Higher role-goal score' else 'Lower role-goal score; review context' end movement,count(*) reviews from readiness_history where candidate_id in(select candidate_id from engagements) and changed_at::date between date_from and date_to group by 1) x),
'methods',(select coalesce(jsonb_agg(x),'[]') from (select p.method,count(*) plan_steps,count(*) filter(where p.status='completed') completed_steps from development_plan_steps p where development_need_id in(select id from needs) group by p.method) x),
'trend',(select coalesce(jsonb_agg(x order by period_month),'[]') from (select date_trunc('month',e.created_at)::date as period_month,count(*) engagements,count(*) filter(where e.status='completed') completed,sum((select coalesce(suM(duration_minutes)/60,0) from coaching_sessions where engagement_id=e.id and status='completed')) coaching_hours,sum((select count(*) from proof where coaching_engagement_id=e.id)) shared_evidence from engagements e group by 1) x),
'renewals',(select coalesce(jsonb_agg(x),'[]') from (select renewal_type,count(*) requests,count(*) filter(where status='completed') completed from coaching_renewals where prior_engagement_id in(select id from engagements) group by renewal_type) x),
'request_failures',(select coalesce(jsonb_agg(x),'[]') from (select reason,count(*) requests from coaching_request_outcomes where coach_request_id in(select id from requests) group by reason) x),
'expansion_opportunities',(select coalesce(jsonb_agg(x),'[]') from (select o.name organization,count(distinct n.candidate_id) leaders,count(*) suitable_needs from needs n join organizations o on o.id=n.organization_id where 'coaching'=any(n.recommended_response) and n.status in ('identified','accepted','active') and not exists(select 1 from coaching_engagements ce where ce.candidate_id=n.candidate_id and ce.status in ('requested','coach_accepted','coachee_accepted','active','paused')) group by o.id,o.name) x),
'continuity',jsonb_build_object('Target roles',(select count(distinct target_role_id) from candidates where (org is null or organization_id=org) and deleted_at is null),'Roles with development',(select count(distinct target_role_id) from needs where status in ('accepted','active'))),
'definitions',jsonb_build_array('Version scale-v1. Engagement and request creation/submission cohorts within the selected dates; later outcomes are shown as of refresh. This is not a reconstruction of historical state.','Marketplace views are distinct signed-in organization/day observations, not unique visitors. Visitor tracking starts with Sprint 5.','Funnel stages use different units and are not a single person-level conversion cohort. Match acceptance uses interested/converted invitations divided by all invitations.','Coach, specialty, industry, leadership level and package filters apply to requests/engagements; marketplace view and activation counts remain organization/date totals.','Null means no observations or denominator. Unknown historical activation timestamps are omitted from timing averages.','Development progress is associated with activity, not caused by coaching. Role-goal score changes are not promotion decisions.','Financial metrics cover the selected engagement cohort through refresh; investment is paid receipts less completed refunds. Contribution excludes expenses not entered; it is not net profit.','Critical-role and Ready-Now designations are not inferred from role-goal scores.')) into result;
return result;end $$;
create function coaching_scale_internal.supply() returns jsonb language sql stable security definer set search_path=public as $$
with c as (select p.*, (select count(distinct coachee_user_id) from coaching_engagements where coach_id=p.id and status='active') load from coach_profiles p where coaching_scale_internal.eligible(p.id)),
s as (select c.id,c.max_active_clients,c.load,c.accepting_clients,c.availability_status,d.key dimension,t.value tag from c cross join lateral jsonb_each(jsonb_build_object('specialty',(select coalesce(jsonb_agg(x.name),'["Unspecified"]') from coach_specialties j join coaching_specialties x on x.id=j.specialty_id where j.coach_id=c.id),'industry',(select coalesce(jsonb_agg(x.name),'["Unspecified"]') from coach_industries j join industries x on x.id=j.industry_id where j.coach_id=c.id),'leadership_level',(select coalesce(jsonb_agg(x.name),'["Unspecified"]') from coach_leadership_levels j join leadership_levels x on x.id=j.leadership_level_id where j.coach_id=c.id),'credential',jsonb_build_array(case when coaching_scale_internal.current_credential((select cp from coach_profiles cp where cp.id=c.id)) then c.icf_credential else 'unverified' end),'geography',jsonb_build_array(coalesce(c.country,'Unspecified')),'timezone',jsonb_build_array(coalesce(c.timezone,'Unspecified')),'format',to_jsonb(array_remove(array[case when c.virtual_available then 'virtual' end,case when c.in_person_available then 'in_person' end],null)),'availability',jsonb_build_array(c.availability_status))) d cross join lateral jsonb_array_elements_text(d.value) t),
d as (select r.id,x.key dimension,t.value tag from coach_requests r cross join lateral jsonb_each(jsonb_build_object('specialty',(select coalesce(jsonb_agg(name),'["Unspecified"]') from coaching_specialties where id=any(r.specialty_ids)),'industry',jsonb_build_array(coalesce((select name from industries where id=r.preferred_industry_id),'Unspecified')),'leadership_level',jsonb_build_array(coalesce((select name from leadership_levels where id=r.preferred_leadership_level_id),'Unspecified')),'credential',jsonb_build_array(coalesce(r.preferred_credential,'Unspecified')),'geography',jsonb_build_array(coalesce(r.location_preference,'Unspecified')),'timezone',jsonb_build_array(coalesce(r.timezone,'Unspecified')),'format',jsonb_build_array(case when r.preferred_format in ('video','phone') then 'virtual' else coalesce(r.preferred_format,'Unspecified') end),'availability',jsonb_build_array('available'))) x cross join lateral jsonb_array_elements_text(x.value) t where r.status not in ('draft','converted_to_engagement','closed','cancelled','declined')),
ss as(select dimension,tag,count(*) coaches,count(*) filter(where accepting_clients and availability_status<>'unavailable') accepting,count(*) filter(where max_active_clients is null and accepting_clients and availability_status<>'unavailable') unknown_capacity,sum(case when accepting_clients and availability_status<>'unavailable' then greatest(0,max_active_clients-load) else 0 end) capacity from s group by 1,2), dd as(select dimension,tag,count(*) demand from d group by 1,2), rows as(select coalesce(ss.dimension,dd.dimension) dimension,coalesce(ss.tag,dd.tag) area,coalesce(coaches,0) coaches,coalesce(accepting,0) accepting,coalesce(unknown_capacity,0) unknown_capacity,coalesce(capacity,0) capacity,coalesce(demand,0) demand,round(capacity::numeric/nullif(demand,0),2) ratio from ss full join dd using(dimension,tag))
select coalesce(jsonb_agg(to_jsonb(rows)||jsonb_build_object('status',case when demand=0 then 'No open demand' when unknown_capacity>0 then 'Capacity incomplete' when coalesce(ratio,0)<(coaching_scale_internal.config()).critical_ratio then 'Critical shortage' when coalesce(ratio,0)<(coaching_scale_internal.config()).watch_ratio then 'Shortage' when coalesce(ratio,0)<(coaching_scale_internal.config()).healthy_ratio then 'Watch' else 'Healthy' end)),'[]') from rows $$;
create function coaching_scale_internal.platform_extra() returns jsonb language sql stable security definer set search_path=public as $$ select jsonb_build_object('supply',coaching_scale_internal.supply(),'marketplace',jsonb_build_object('Approved coaches',(select count(*) from coach_profiles where profile_status='approved'),'Eligible coaches',(select count(*) from coach_profiles where coaching_scale_internal.eligible(id)),'Accepting clients',(select count(*) from coach_profiles where coaching_internal.eligible(id)),'Organizations using coaching',(select count(distinct organization_id) from coaching_engagements),'Open quality reviews',(select count(*) from coach_quality_flags where status<>'resolved')),'search_gaps',(select coalesce(jsonb_agg(x),'[]') from (select dimensions,count(*) organization_days from coaching_marketplace_events where event_type='search' and result_count<=1 and day>=current_date-90 group by dimensions) x),'utilization',(select coalesce(jsonb_agg(jsonb_build_object('coach',c.display_name,'maximum_clients',c.max_active_clients,'active_clients',(select count(distinct coachee_user_id) from coaching_engagements where coach_id=c.id and status='active'),'utilization_percent',round(100.0*(select count(distinct coachee_user_id) from coaching_engagements where coach_id=c.id and status='active')/nullif(c.max_active_clients,0),1),'availability',c.availability_status)),'[]') from coach_profiles c),'growth',(select coalesce(jsonb_agg(x order by period_month),'[]') from (select date_trunc('month',created_at)::date as period_month,count(*) new_coaches from coach_profiles group by 1) x)) $$;
create function public.coaching_scale_refresh(filters jsonb default '{}') returns uuid language plpgsql security definer set search_path=public as $$ declare org uuid; key text; data jsonb; result uuid;begin
if not coaching_identity_enabled() then raise exception 'Not authorized';end if;
org:=case when coaching_platform_admin() then nullif(filters->>'organization','')::uuid else coaching_scale_internal.org() end;
if not coaching_platform_admin() and not coaching_admin(org) then raise exception 'Analytics administrator required';end if;
if not coaching_platform_admin() and nullif(filters->>'organization','') is not null and (filters->>'organization')::uuid<>org then raise exception 'Organization scope mismatch';end if;
key:=case when coaching_platform_admin() then 'platform:'||coalesce(org::text,'all') else 'organization:'||org end;
perform pg_advisory_xact_lock(hashtext('scale-refresh:'||key));
data:=coaching_scale_internal.analytics(filters,org);
if coaching_platform_admin() then data:=data||coaching_scale_internal.platform_extra();end if;
insert into coaching_scale_snapshots(scope_key,organization_id,filters,data,definition_version) values(key,org,filters,data,(coaching_scale_internal.config()).version) on conflict on constraint coaching_scale_snapshots_scope_key_filters_key do update set data=excluded.data,calculated_at=now(),definition_version=excluded.definition_version returning id into result;
perform coaching_scale_internal.audit('analytics_refresh',result,org);return result;end $$;
create function public.coaching_scale_read(section text default 'workspace',filters jsonb default '{}') returns jsonb language plpgsql security definer set search_path=public as $$ declare org uuid:=coaching_scale_internal.org(); cid uuid; admin boolean:=coaching_platform_admin(); cfg coaching_scale_versions; key text; snap coaching_scale_snapshots;begin
if not coaching_identity_enabled() then raise exception 'Not authorized';end if;
select id into cid from coach_profiles where user_id=auth.uid();cfg:=coaching_scale_internal.config();
if section='analytics' then
if not admin and not coaching_admin(org) then raise exception 'Analytics administrator required';end if;
if not admin and nullif(filters->>'organization','') is not null and (filters->>'organization')::uuid<>org then raise exception 'Organization scope mismatch';end if;
key:=case when admin then 'platform:'||coalesce(nullif(filters->>'organization',''),'all') else 'organization:'||org end;
select * into snap from coaching_scale_snapshots where scope_key=key and coaching_scale_snapshots.filters=coaching_scale_read.filters;
return jsonb_build_object('snapshot',snap.data,'calculated_at',snap.calculated_at,'version',snap.definition_version,'configuration',to_jsonb(cfg));end if;
return jsonb_build_object('configuration',to_jsonb(cfg),'coach_id',cid,'organization_id',org,
'coaches',case when admin then (select coalesce(jsonb_agg(to_jsonb(c)||jsonb_build_object('readiness',coaching_scale_internal.readiness(c.id),'eligible',coaching_scale_internal.eligible(c.id),'active_clients',(select count(distinct coachee_user_id) from coaching_engagements where coach_id=c.id and status='active'))),'[]') from coach_profiles c) when cid is not null then (select jsonb_build_array(to_jsonb(c)||jsonb_build_object('readiness',coaching_scale_internal.readiness(c.id),'eligible',coaching_scale_internal.eligible(c.id))) from coach_profiles c where id=cid) else coaching_marketplace() end,
'quality',(select coalesce(jsonb_agg(to_jsonb(q)||jsonb_build_object('metric_value',case when q.metric_type in ('coachee_experience','organization_experience') and q.sample_size<cfg.minimum_feedback_sample_size then null else q.metric_value end)),'[]') from coach_quality_metrics q where (admin or q.coach_id=cid) and q.privacy_valid and q.definition_version=cfg.version and q.measurement_period_end=(select max(measurement_period_end) from coach_quality_metrics where coach_id=q.coach_id and definition_version=cfg.version)),
'feedback',case when admin then (select coalesce(jsonb_agg(to_jsonb(f)),'[]') from coaching_feedback f) else '[]'::jsonb end,
'professional_development',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coach_professional_development x where admin or coach_id=cid),
'flags',case when admin then (select coalesce(jsonb_agg(to_jsonb(f)),'[]') from coach_quality_flags f) else (select coalesce(jsonb_agg(jsonb_build_object('id',f.id,'status',f.status,'severity',f.severity)),'[]') from coach_quality_flags f where f.coach_id=cid and exists(select 1 from coach_quality_review_events where flag_id=f.id and visibility='coach_platform')) end,
'review_events',(select coalesce(jsonb_agg(to_jsonb(x) order by created_at),'[]') from coach_quality_review_events x where admin or (visibility='coach_platform' and flag_id in(select id from coach_quality_flags where coach_id=cid))),
'conflicts',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coaching_conflicts x where admin or coach_id=cid),
'saved',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from organization_saved_coaches x where organization_id=org and coaching_admin(org)),
'programs',(select coalesce(jsonb_agg(to_jsonb(p)||jsonb_build_object('participants',(select count(*) from coaching_program_participants where program_id=p.id),
'active_coaching',(select count(*) from coaching_engagements where status='active' and id in(select engagement_id from coaching_program_participants where program_id=p.id)),
'completed_coaching',(select count(*) from coaching_engagements where status='completed' and id in(select engagement_id from coaching_program_participants where program_id=p.id)),
'coaching_hours',(select coalesce(round(sum(duration_minutes)/60,1),0) from coaching_sessions where status='completed' and engagement_id in(select engagement_id from coaching_program_participants where program_id=p.id)),
'shared_goals',(select count(*) from coaching_goals where engagement_id in(select engagement_id from coaching_program_participants where program_id=p.id) and visibility='organization_shared' and coaching_has_consent(engagement_id,'organization_reporting')),
'goals_achieved',(select count(*) from coaching_goals where engagement_id in(select engagement_id from coaching_program_participants where program_id=p.id) and status='achieved' and visibility='organization_shared' and coaching_has_consent(engagement_id,'organization_reporting')),
'shared_evidence',(select count(*) from development_evidence where coaching_engagement_id in(select engagement_id from coaching_program_participants where program_id=p.id) and visibility in ('organization','readiness_review') and coaching_has_consent(coaching_engagement_id,'organization_reporting')),
'readiness_reviews',(select count(*) from readiness_history where candidate_id in(select candidate_id from coaching_program_participants where program_id=p.id) and changed_at::date>=p.start_date and (p.end_date is null or changed_at::date<=p.end_date)),
'spent',(select coalesce(sum(pay.amount),0) from coaching_payments pay where pay.status in ('paid','partially_refunded','refunded') and pay.engagement_id in(select engagement_id from coaching_program_participants where program_id=p.id))-(select coalesce(sum(ref.amount),0) from coaching_refunds ref where ref.status='completed' and ref.engagement_id in(select engagement_id from coaching_program_participants where program_id=p.id)))),'[]') from coaching_programs p where coaching_admin(p.organization_id)),
'program_feedback',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coaching_program_feedback x join coaching_programs p on p.id=x.program_id where coaching_admin(p.organization_id)),
'participants',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coaching_program_participants x join coaching_programs p on p.id=x.program_id where coaching_admin(p.organization_id)),
'roi',(select coalesce(jsonb_agg(to_jsonb(x)||jsonb_build_object('value_label','Organization-provided estimate','entered_by_name',(select full_name from profiles where auth_user_id=x.entered_by))),'[]') from coaching_roi_measures x where coaching_admin(organization_id)),
'renewals',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coaching_renewals x join coaching_engagements e on e.id=x.prior_engagement_id where coaching_admin(e.organization_id)),
'applications',case when admin then (select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coach_applications x) else (select coalesce(jsonb_agg(to_jsonb(x)-'review_notes'),'[]') from coach_applications x where user_id=auth.uid()) end,
'agreements',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from (select * from coach_marketplace_agreements order by created_at desc limit 1) x),
'training',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coach_training_assignments x where admin or coach_id=cid),
'retention',case when admin then (select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coaching_retention_rules x) else '[]'::jsonb end,
'privacy',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coaching_privacy_requests x where admin or subject_user_id=auth.uid() or (organization_id=org and coaching_admin(org))),
'engagements',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'title',title,'status',status,'coach_id',coach_id,'candidate_id',candidate_id)),'[]') from coaching_engagements e where coaching_admin(e.organization_id) or coaching_is_coach(e.id) or coaching_is_client(e.id)),
'requests',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'title',request_title,'status',status)),'[]') from coach_requests r where coaching_admin(r.organization_id) or exists(select 1 from coaching_invitations where coach_request_id=r.id and coach_id=cid)),
'candidates',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',full_name)),'[]') from candidates where deleted_at is null and coaching_admin(organization_id)),
'organizations',case when admin then (select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name)),'[]') from organizations) else '[]'::jsonb end,
'specialties',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name)),'[]') from coaching_specialties where active),
'industries',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name)),'[]') from industries where active),
'levels',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name)),'[]') from leadership_levels where active),
'packages',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name)),'[]') from coaching_packages where active));end $$;
-- Only structured marketplace dimensions are recorded; no free-text searches or user identifiers.
create function public.coaching_scale_observe(dimensions jsonb default '{}',result_count integer default 0) returns void language plpgsql security definer set search_path=public as $$ declare org uuid:=coaching_scale_internal.org(); safe jsonb;begin
if not coaching_identity_enabled() or org is null then return;end if;
select coalesce(jsonb_object_agg(key,value),'{}') into safe from jsonb_each_text(dimensions) where key in ('specialty','industry','level','credential','format') and length(value)<=100 and (case key when 'specialty' then exists(select 1 from coaching_specialties where name=value) when 'industry' then exists(select 1 from industries where name=value) when 'level' then exists(select 1 from leadership_levels where name=value) when 'credential' then value in ('none','acc','pcc','mcc','other') when 'format' then value in ('virtual','in_person') else false end);
insert into coaching_marketplace_events(organization_id,event_type,dimensions,result_count) values(org,case when safe='{}' then 'view' else 'search' end,safe,greatest(result_count,0)) on conflict do nothing;end $$;
alter table coach_quality_metrics add column privacy_valid boolean not null default true;
create function coaching_scale_internal.invalidate_privacy() returns trigger language plpgsql security definer set search_path=public as $$ begin
 delete from coaching_scale_snapshots;
 update coach_quality_metrics set privacy_valid=false where metric_type in ('goal_progress_rate','development_milestone_rate');return null;end $$;
create trigger scale_consent_invalidation after insert or update or delete on coaching_consents for each statement execute function coaching_scale_internal.invalidate_privacy();
create trigger scale_evidence_invalidation after insert or update or delete on development_evidence for each statement execute function coaching_scale_internal.invalidate_privacy();
create trigger scale_goal_invalidation after insert or update or delete on coaching_goals for each statement execute function coaching_scale_internal.invalidate_privacy();
create function coaching_scale_internal.daily() returns void language plpgsql security definer set search_path=public as $$ declare o record; c coach_profiles; threshold int; recipient uuid; data jsonb; cfg coaching_scale_versions;begin
if not pg_try_advisory_xact_lock(hashtext('coaching-scale-daily')) then return;end if;cfg:=coaching_scale_internal.config();
perform coaching_scale_internal.quality_refresh();update coach_quality_metrics set privacy_valid=true where calculated_at=now();
for o in select id from organizations loop
 data:=coaching_scale_internal.analytics('{}',o.id);
 insert into coaching_scale_snapshots(scope_key,organization_id,filters,data,definition_version) values('organization:'||o.id,o.id,'{}',data,cfg.version) on conflict on constraint coaching_scale_snapshots_scope_key_filters_key do update set data=excluded.data,definition_version=excluded.definition_version,calculated_at=now();end loop;
data:=coaching_scale_internal.analytics('{}',null)||coaching_scale_internal.platform_extra();
insert into coaching_scale_snapshots(scope_key,filters,data,definition_version) values('platform:all','{}',data,cfg.version) on conflict on constraint coaching_scale_snapshots_scope_key_filters_key do update set data=excluded.data,definition_version=excluded.definition_version,calculated_at=now();
for c in select * from coach_profiles where user_id is not null loop
 threshold:=case when c.icf_credential_expiration_date<current_date then 0 when c.icf_credential_expiration_date<=current_date+30 then 30 when c.icf_credential_expiration_date<=current_date+60 then 60 when c.icf_credential_expiration_date<=current_date+90 then 90 when c.icf_credential_expiration_date<=current_date+120 then 120 end;
 if threshold is not null then
 for recipient in select c.user_id union select auth_user_id from profiles where role='system_admin' and deleted_at is null loop
 insert into notifications(recipient_user_id,event_type,title,href,dedupe_key) values(recipient,'credential_review',case when threshold=0 then 'Coaching credential has expired; review required' else 'Coaching credential expires within '||threshold||' days' end,case when recipient=c.user_id then '/coaching/quality' else '/admin/coaching/credentials' end,'credential:'||c.id||':'||c.icf_credential_expiration_date||':'||threshold) on conflict do nothing;end loop;end if;
 if (c.max_active_clients is not null and (select count(distinct coachee_user_id) from coaching_engagements where coach_id=c.id and status='active')>=c.max_active_clients*0.8) or not exists(select 1 from coach_availability_rules where coach_id=c.id and active and (effective_end_date is null or effective_end_date>=current_date)) then
 insert into notifications(recipient_user_id,event_type,title,href,dedupe_key) values(c.user_id,'capacity_review','Review coaching capacity and future availability','/coaching/availability','capacity:'||c.id||':'||date_trunc('week',current_date)) on conflict do nothing;end if;
end loop;end $$;
create function public.coaching_scale_run_daily() returns boolean language plpgsql security definer set search_path=public as $$ begin if not coaching_platform_admin() then raise exception 'Platform administrator required';end if;perform coaching_scale_internal.daily();return true;end $$;
alter function public.coaching_run_matching(uuid) rename to coaching_run_matching_sprint4;
revoke all on function coaching_run_matching_sprint4(uuid) from public,anon,authenticated;
create function public.coaching_run_matching(rid uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare run uuid; m coaching_match_results; cfg coaching_scale_versions; samples int; goal_samples int; outcome numeric; reliability numeric; factors jsonb; fraction numeric; weight numeric; total numeric; active_weight numeric; k text; v jsonb;begin
run:=coaching_run_matching_sprint4(rid);cfg:=coaching_scale_internal.config();
for m in select * from coaching_match_results where run_id=run loop
 if not coaching_scale_internal.eligible(m.coach_id) or exists(select 1 from coaching_conflicts where coach_id=m.coach_id and coach_request_id=rid and status<>'cleared') then update coaching_match_results set excluded=true,admin_reason='Marketplace eligibility or conflict review required' where id=m.id;continue;end if;
 if not coaching_scale_internal.current_credential((select cp from coach_profiles cp where cp.id=m.coach_id)) and (select preferred_credential from coach_requests where id=rid) not in ('none') and (select preferred_credential from coach_requests where id=rid) is not null then
 m.match_score:=greatest(0,m.match_score-coalesce((m.factor_scores->'credential'->>'points')::numeric,0));
 m.factor_scores:=jsonb_set(m.factor_scores,'{credential}',coalesce(m.factor_scores->'credential','{}')||jsonb_build_object('fraction',0,'points',0));
 update coaching_match_results set match_score=m.match_score,factor_scores=m.factor_scores,unmet_preferences=unmet_preferences||jsonb_build_array('Credential preference requires current verification') where id=m.id;end if;
 if not cfg.outcome_matching_enabled then continue;end if;
 select count(*) into samples from coaching_engagements where coach_id=m.coach_id and status='completed' and created_at>=current_date-365;
 select count(distinct e.id) into goal_samples from coaching_engagements e join coaching_goals g on g.engagement_id=e.id where e.coach_id=m.coach_id and e.status='completed' and e.created_at>=current_date-365 and g.visibility='organization_shared' and coaching_has_consent(e.id,'organization_reporting');
 outcome:=null;reliability:=null;
 if goal_samples>=cfg.minimum_outcome_sample_size then select metric_value/100 into outcome from coach_quality_metrics where coach_id=m.coach_id and metric_type='goal_progress_rate' and privacy_valid and definition_version=cfg.version and calculated_at>=now()-interval '2 days' order by calculated_at desc limit 1;end if;
 if samples>=cfg.minimum_outcome_sample_size then select metric_value/100 into reliability from coach_quality_metrics where coach_id=m.coach_id and metric_type='engagement_completion_rate' and definition_version=cfg.version and calculated_at>=now()-interval '2 days' order by calculated_at desc limit 1;end if;
 active_weight:=90+case when outcome is null then 0 else 5 end+case when reliability is null then 0 else 5 end;factors:='{}';total:=0;
 for k,v in select * from jsonb_each(m.factor_scores) loop weight:=coalesce((v->>'weight')::numeric,0)*0.9*100/active_weight;fraction:=coalesce((v->>'fraction')::numeric,0);total:=total+weight*fraction;factors:=factors||jsonb_build_object(k,v||jsonb_build_object('weight',weight,'points',weight*fraction));end loop;
 factors:=factors||jsonb_build_object('shared_outcomes',jsonb_build_object('weight',case when outcome is null then 0 else 500/active_weight end,'fraction',coalesce(outcome,0),'points',coalesce(outcome,0)*500/active_weight,'sample_size',goal_samples,'minimum_sample',cfg.minimum_outcome_sample_size),'completion_reliability',jsonb_build_object('weight',case when reliability is null then 0 else 500/active_weight end,'fraction',coalesce(reliability,0),'points',coalesce(reliability,0)*500/active_weight,'sample_size',samples,'minimum_sample',cfg.minimum_outcome_sample_size));
 total:=total+coalesce(outcome,0)*500/active_weight+coalesce(reliability,0)*500/active_weight;
 update coaching_match_results set match_score=least(100,round(total,4)),factor_scores=factors,matching_version='v3:'||cfg.version,match_reasons=match_reasons||jsonb_build_array('Historical factors require the configured minimum sample and fresh, authorized metrics. Missing factors are omitted and remaining weights normalized. Preferred status does not change fit scoring.') where id=m.id;
end loop;return run;end $$;
create view public.coaching_marketplace_funnel as select scope_key,organization_id,filters,data->'funnel' as funnel,definition_version,calculated_at from coaching_scale_snapshots;
revoke all on coaching_marketplace_funnel from public,anon,authenticated;
create trigger scale_updated_at before update on coaching_scale_versions for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_feedback for each row execute function set_updated_at();
create trigger scale_updated_at before update on coach_quality_metrics for each row execute function set_updated_at();
create trigger scale_updated_at before update on coach_professional_development for each row execute function set_updated_at();
create trigger scale_updated_at before update on coach_quality_flags for each row execute function set_updated_at();
create trigger scale_updated_at before update on coach_quality_review_events for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_conflicts for each row execute function set_updated_at();
create trigger scale_updated_at before update on organization_saved_coaches for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_renewals for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_programs for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_program_participants for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_engagement_participants for each row execute function set_updated_at();
create trigger scale_updated_at before update on coach_applications for each row execute function set_updated_at();
create trigger scale_updated_at before update on coach_marketplace_agreements for each row execute function set_updated_at();
create trigger scale_updated_at before update on coach_marketplace_acceptances for each row execute function set_updated_at();
create trigger scale_updated_at before update on coach_training_assignments for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_roi_measures for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_program_feedback for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_request_outcomes for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_marketplace_events for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_retention_rules for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_privacy_requests for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_scale_snapshots for each row execute function set_updated_at();
create trigger scale_updated_at before update on coaching_operating_costs for each row execute function set_updated_at();
-- Relevant indexes keep cohort/report refreshes off operational request paths.
create index scale_feedback_coach on coaching_feedback(coach_id,submitted_at);
create index scale_engagement_period on coaching_engagements(organization_id,created_at,coach_id);
create index scale_request_period on coach_requests(organization_id,submitted_at);
create index scale_flags_coach on coach_quality_flags(coach_id,status);
create index scale_conflict_request on coaching_conflicts(coach_request_id,coach_id,status);
create index scale_quality_latest on coach_quality_metrics(coach_id,definition_version,calculated_at);
revoke all on all functions in schema coaching_scale_internal from public,anon,authenticated;
revoke all on function coaching_scale_mutate(text,jsonb),coaching_scale_read(text,jsonb),coaching_scale_refresh(jsonb),coaching_scale_run_daily(),coaching_scale_observe(jsonb,integer),coaching_marketplace(),coaching_run_matching(uuid) from public,anon,authenticated;
grant execute on function coaching_scale_mutate(text,jsonb),coaching_scale_read(text,jsonb),coaching_scale_refresh(jsonb),coaching_scale_run_daily(),coaching_scale_observe(jsonb,integer),coaching_marketplace(),coaching_run_matching(uuid) to authenticated;
-- Supabase deployments with pg_cron enabled receive a daily database job. No external HTTP calls.
do $$ begin if exists(select 1 from pg_extension where extname='pg_cron') then execute $q$select cron.schedule('coaching-scale-daily','15 3 * * *','select coaching_scale_internal.daily()')$q$;else raise notice 'Enable pg_cron and schedule coaching_scale_internal.daily() daily; platform manual refresh is available.';end if;end $$;
commit;
