-- Development intelligence references existing assessment and activity records.
-- No private coaching note or reflection is a source for these functions.
begin;
create schema development_internal;
revoke all on schema development_internal from public,anon,authenticated;
create table public.leadership_development_needs(id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), candidate_id uuid not null references candidates(id), target_role_id uuid references roles(id), competency_id uuid references role_competencies(id), need_type text not null, title text not null, description text not null, source_type text not null, source_id uuid, source_key text not null, gap_severity text check(gap_severity in ('minor','moderate','significant','critical')), priority text not null default 'moderate' check(priority in ('low','moderate','high','urgent')), recommended_response text[] not null default '{}', status text not null default 'identified' check(status in ('identified','accepted','active','resolved','dismissed')), baseline_level numeric check(baseline_level between 1 and 5), target_level numeric check(target_level between 1 and 5), identified_at timestamptz not null default now(), identified_by uuid references auth.users(id), reviewed_by uuid references auth.users(id), reviewed_at timestamptz, unique(candidate_id,source_key), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.leadership_development_needs enable row level security;
revoke all on public.leadership_development_needs from anon,authenticated;
create table public.development_method_rules(id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id), competency_id uuid references role_competencies(id), competency_name text, need_type text, coaching_weight integer not null default 0 check(coaching_weight between 0 and 3), mentoring_weight integer not null default 0 check(mentoring_weight between 0 and 3), project_weight integer not null default 0 check(project_weight between 0 and 3), training_weight integer not null default 0 check(training_weight between 0 and 3), experience_weight integer not null default 0 check(experience_weight between 0 and 3), rationale text not null, version text not null, active boolean not null default true, created_by uuid references auth.users(id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.development_method_rules enable row level security;
revoke all on public.development_method_rules from anon,authenticated;
create table public.development_intelligence_versions(id uuid primary key default gen_random_uuid(), version text not null unique, matching_version text not null default 'v2-development', evidence_scoring_version text not null, matching_weights jsonb not null, evidence_weights jsonb not null, review_days integer not null default 90 check(review_days between 1 and 730), recency_days integer not null default 365 check(recency_days between 30 and 3650), minimum_independent_sources integer not null default 2 check(minimum_independent_sources between 1 and 20), created_by uuid references auth.users(id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.development_intelligence_versions enable row level security;
revoke all on public.development_intelligence_versions from anon,authenticated;
create table public.development_recommendations(id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), candidate_id uuid not null references candidates(id), development_need_id uuid not null references leadership_development_needs(id), recommendation_type text not null, recommendation_data jsonb not null, reviewed_data jsonb, rationale text not null, source text not null default 'deterministic_rules' check(source='deterministic_rules'), model_version text not null, rule_id uuid references development_method_rules(id), status text not null default 'suggested' check(status in ('suggested','accepted','modified','dismissed','completed')), reviewed_by uuid references auth.users(id), reviewed_at timestamptz, unique(development_need_id,model_version,rule_id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.development_recommendations enable row level security;
revoke all on public.development_recommendations from anon,authenticated;
create table public.coaching_focus_areas(id uuid primary key default gen_random_uuid(), engagement_id uuid not null references coaching_engagements(id), development_need_id uuid references leadership_development_needs(id), competency_id uuid references role_competencies(id), title text not null, description text, baseline_level numeric check(baseline_level between 1 and 5), target_level numeric check(target_level between 1 and 5), priority text not null default 'moderate', status text not null default 'planned' check(status in ('planned','active','achieved','paused','closed')), created_by uuid references auth.users(id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.coaching_focus_areas enable row level security;
revoke all on public.coaching_focus_areas from anon,authenticated;
create table public.development_plan_steps(id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), candidate_id uuid not null references candidates(id), development_need_id uuid not null references leadership_development_needs(id), method text not null check(method in ('coaching','mentoring','project','training','experience','assessment','self_development')), title text not null, activity text not null, owner_user_id uuid references auth.users(id), target_date date, review_date date, evidence_required text not null, status text not null default 'planned' check(status in ('planned','active','completed','cancelled')), development_record_id uuid references development_records(id), project_assignment_id uuid references candidate_project_assignments(id), training_selection_id uuid references training_selections(id), mentor_assignment_id uuid references mentor_role_assignments(id), coaching_engagement_id uuid references coaching_engagements(id), created_by uuid references auth.users(id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.development_plan_steps enable row level security;
revoke all on public.development_plan_steps from anon,authenticated;
create table public.development_evidence(id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), candidate_id uuid not null references candidates(id), development_need_id uuid references leadership_development_needs(id), competency_id uuid references role_competencies(id), coaching_engagement_id uuid references coaching_engagements(id), coaching_goal_id uuid references coaching_goals(id), project_assignment_id uuid references candidate_project_assignments(id), training_selection_id uuid references training_selections(id), mentor_assignment_id uuid references mentor_role_assignments(id), development_record_id uuid references development_records(id), evidence_type text not null, title text not null, description text not null, evidence_date date not null, source_user_id uuid not null references auth.users(id), visibility text not null default 'private' check(visibility in ('private','coach_client','organization','readiness_review')), verification_status text not null default 'self_reported' check(verification_status in ('unverified','self_reported','coach_confirmed','mentor_confirmed','manager_confirmed','verified')), verified_by uuid references auth.users(id), verified_at timestamptz, readiness_approved_by uuid references auth.users(id), readiness_approved_at timestamptz, scoring_version text not null, evidence_weight integer not null default 1 check(evidence_weight between 0 and 10), request_key uuid not null unique, created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.development_evidence enable row level security;
revoke all on public.development_evidence from anon,authenticated;
create table public.development_progress_reviews(id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), candidate_id uuid not null references candidates(id), engagement_id uuid references coaching_engagements(id), development_need_id uuid not null references leadership_development_needs(id), competency_id uuid references role_competencies(id), review_type text not null check(review_type in ('30_day','60_day','90_day','midpoint','closeout','custom')), baseline_level numeric check(baseline_level between 1 and 5), current_level numeric check(current_level between 1 and 5), progress_status text not null check(progress_status in ('not_started','early_progress','progressing','significant_progress','target_achieved','needs_attention','insufficient_evidence')), evidence_summary text not null, evidence_ids uuid[] not null default '{}', visibility text not null default 'coach_client' check(visibility in ('coach_client','organization','readiness_review')), reviewed_by uuid not null references auth.users(id), reviewed_at timestamptz not null default now(), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.development_progress_reviews enable row level security;
revoke all on public.development_progress_reviews from anon,authenticated;
create table public.readiness_history(id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), candidate_id uuid not null references candidates(id), target_role_id uuid not null references roles(id), previous_match_id uuid references candidate_role_matches(id), new_match_id uuid not null unique references candidate_role_matches(id), previous_readiness numeric, new_readiness numeric check(new_readiness between 0 and 100), reason text not null, supporting_evidence_ids uuid[] not null default '{}', changed_by uuid not null references auth.users(id), changed_at timestamptz not null default now(), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.readiness_history enable row level security;
revoke all on public.readiness_history from anon,authenticated;
create table public.coaching_outcome_measures(id uuid primary key default gen_random_uuid(), engagement_id uuid not null references coaching_engagements(id), development_need_id uuid references leadership_development_needs(id), competency_id uuid references role_competencies(id), measure_type text not null, baseline_value numeric, target_value numeric, final_value numeric, baseline_text text, target_text text, final_text text, measurement_source text not null, evidence_id uuid references development_evidence(id), visibility text not null default 'coach_client' check(visibility in ('coach_client','organization','readiness_review')), measured_by uuid references auth.users(id), measured_at timestamptz not null default now(), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.coaching_outcome_measures enable row level security;
revoke all on public.coaching_outcome_measures from anon,authenticated;
create table public.coach_development_experience(id uuid primary key default gen_random_uuid(), coach_id uuid not null references coach_profiles(id), need_type text not null, target_role_title text, description text not null, verified_by uuid not null references auth.users(id), unique(coach_id,need_type,target_role_title), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default now());
alter table public.coach_development_experience enable row level security;
revoke all on public.coach_development_experience from anon,authenticated;
alter table coaching_goals add column focus_area_id uuid references coaching_focus_areas(id);
alter table coach_requests add column development_need_id uuid references leadership_development_needs(id);
alter table coaching_data_permissions drop constraint coaching_data_permissions_data_type_check;
alter table coaching_data_permissions add check(data_type in ('role_composite','competencies','clifton_strengths','assessment','360_review','development_plan','mentor_plan','project','training','readiness','development_need','target_role'));
insert into development_intelligence_versions(version,evidence_scoring_version,matching_weights,evidence_weights) values('development-rules-v1','evidence-v1','{"specialty":20,"competency":20,"development_need":15,"industry":10,"leadership_level":10,"target_role":10,"credential":5,"format":3,"availability":4,"geography":3}','{"unverified":0,"self_reported":1,"coach_confirmed":2,"mentor_confirmed":2,"manager_confirmed":3,"verified":3}');
insert into development_method_rules(competency_name,need_type,coaching_weight,mentoring_weight,project_weight,training_weight,experience_weight,rationale,version) values
('Executive Communication','executive_communication',3,2,2,1,2,'Focused practice, feedback and reflection can support executive communication; combine coaching with real presentations and mentor feedback.','method-v1'),
('Communication','executive_communication',3,2,2,1,2,'Communication can benefit from structured practice, feedback and accountability. Check the assessment context before choosing coaching.','method-v1'),
('Technical Accounting Knowledge','technical_knowledge',1,2,2,3,3,'Knowledge gaps usually need training and applied experience. Coaching is optional support, not a replacement for technical learning.','method-v1'),
('Delegation','delegation',3,2,2,1,2,'Practice delegation in real work with feedback and accountability.','method-v1'),
('Strategic Thinking','strategic_thinking',2,2,3,1,3,'Strategic judgment benefits from substantive projects and experience, supported by coaching or mentoring.','method-v1');
create function development_internal.admin(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from candidates c where c.id=cid and c.deleted_at is null and coaching_admin(c.organization_id)) $$;
create function development_internal.self(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select coaching_identity_enabled() and exists(select 1 from organization_users u join profiles p on p.id=u.profile_id where u.candidate_id=cid and coalesce(u.auth_user_id,p.auth_user_id)=auth.uid() and u.deleted_at is null and u.status='active' and p.deleted_at is null) $$;
create function development_internal.mentor(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select coaching_identity_enabled() and exists(select 1 from mentor_role_assignments m join profiles p on p.id=m.mentor_profile_id join candidates c on c.id=m.candidate_id where m.candidate_id=cid and m.role_id=c.target_role_id and m.organization_id=c.organization_id and m.status='active' and p.auth_user_id=auth.uid() and p.deleted_at is null) $$;
create function development_internal.member(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select development_internal.admin(cid) or development_internal.self(cid) or development_internal.mentor(cid) $$;
create function development_internal.shared(eid uuid, kind text, item uuid) returns boolean language sql stable security definer set search_path=public as $$ select coaching_has_consent(eid,'development_data_access') and exists(select 1 from coaching_data_permissions where engagement_id=eid and data_type=kind and data_id=item and revoked_at is null) $$;
create function development_internal.need_read(nid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from leadership_development_needs n where id=nid and (development_internal.member(n.candidate_id) or exists(select 1 from coaching_engagements e where e.candidate_id=n.candidate_id and e.organization_id=n.organization_id and coaching_is_coach(e.id) and development_internal.shared(e.id,'development_need',n.id)))) $$;
create function development_internal.evidence_read(x development_evidence) returns boolean language sql stable security definer set search_path=public as $$ select coaching_identity_enabled() and (
 (x.source_user_id=auth.uid() and (development_internal.member(x.candidate_id) or coaching_is_coach(x.coaching_engagement_id)))
 or (x.visibility='coach_client' and (coaching_is_client(x.coaching_engagement_id) or coaching_is_coach(x.coaching_engagement_id)))
 or (x.visibility in ('organization','readiness_review') and (development_internal.member(x.candidate_id) or (coaching_is_coach(x.coaching_engagement_id) and (x.development_need_id is null or development_internal.shared(x.coaching_engagement_id,'development_need',x.development_need_id)))) and (x.coaching_engagement_id is null or coaching_has_consent(x.coaching_engagement_id,'organization_reporting')))) $$;
create function development_internal.audit(ev text,cid uuid,item uuid,detail jsonb default '{}') returns void language sql security definer set search_path=public as $$ insert into platform_audit_events(actor_profile_id,organization_id,event_type,details) values((select id from profiles where auth_user_id=auth.uid()),(select organization_id from candidates where id=cid),'development.'||ev,jsonb_build_object('candidate_id',cid,'record_id',item)||detail) $$;
-- Narrow source adapter: intentionally excludes interview narratives, raw 360 comments,
-- mentoring private notes, personal reflections, medical/HR data and coaching notes.
create function development_internal.sources(cid uuid) returns jsonb language sql stable security definer set search_path=public as $$
with subject as (select * from candidates where id=cid and deleted_at is null), items as (
 select r.id,'target_role' kind,r.title title,r.description description,null::uuid competency_id,null::numeric current_level,null::numeric target_level,r.updated_at occurred_at,'current' status
 from roles r join subject c on c.target_role_id=r.id and c.organization_id=r.organization_id where r.deleted_at is null
 union all select r.id,'role_composite',r.title||' role composite',string_agg(rc.name||' (target '||rc.target_score||'/5)',', ' order by rc.name),null,null,null,r.updated_at,'current' from subject c join roles r on r.id=c.target_role_id and r.organization_id=c.organization_id join role_competencies rc on rc.role_id=r.id and rc.organization_id=c.organization_id and rc.deleted_at is null group by r.id,r.title,r.updated_at
 union all select rc.id,'competencies',rc.name,rc.definition,rc.id,null,rc.target_score,rc.updated_at,'current' from role_competencies rc join subject c on rc.role_id=c.target_role_id and rc.organization_id=c.organization_id where rc.deleted_at is null
 union all select ip.id,'assessment',rc.name||' — completed panel',ip.panel_name,rc.id,round(avg(s.score_numeric),2),rc.target_score,ip.date_completed::timestamptz,'completed' from interview_panels ip join subject c on ip.candidate_id=c.id and ip.role_id=c.target_role_id and ip.organization_id=c.organization_id join interview_scores s on s.panel_id=ip.id and s.organization_id=c.organization_id join role_competencies rc on rc.id=s.competency_id and rc.role_id=ip.role_id and rc.organization_id=c.organization_id and rc.deleted_at is null where ip.date_completed is not null group by ip.id,rc.id,rc.name,ip.panel_name,rc.target_score,ip.date_completed
 union all select d.id,'development_plan',d.experience_title,d.mentee_task,rc.id,dc.current_score,dc.target_score,d.mentor_review_date::timestamptz,d.status from development_records d join subject c on d.candidate_id=c.id and d.organization_id=c.organization_id and (d.role_id=c.target_role_id or d.role_id is null) left join development_record_competencies dc on dc.development_record_id=d.id left join role_competencies rc on rc.role_id=c.target_role_id and rc.organization_id=c.organization_id and lower(trim(rc.name))=lower(trim(dc.competency_name)) and rc.deleted_at is null where d.archived_at is null
 union all select cy.id,'360_review',sc.name||' — released 360 aggregate','Released non-self ratings meet the confidentiality threshold; no respondent comments are included.',sc.source_role_competency_id,round(avg(rr.rating),2),sc.target_score,cy.results_released_at,'released' from subject c join review_360_cycles cy on cy.organization_id=c.organization_id and (cy.candidate_id=c.id or cy.employee_organization_user_id in (select id from organization_users where candidate_id=c.id and organization_id=c.organization_id and deleted_at is null)) join review_360_snapshot_competencies sc on sc.review_cycle_id=cy.id and sc.organization_id=c.organization_id join review_360_ratings rr on rr.snapshot_competency_id=sc.id and rr.review_cycle_id=cy.id and rr.organization_id=c.organization_id join review_360_respondents resp on resp.id=rr.respondent_id and resp.review_cycle_id=cy.id and resp.organization_id=c.organization_id where cy.results_released_at is not null and cy.status='completed' and cy.role_id=c.target_role_id and resp.status='completed' and coalesce(resp.confirmed_relationship,resp.invited_relationship)<>'self' and not rr.not_observed group by cy.id,sc.id,sc.name,sc.source_role_competency_id,sc.target_score,cy.results_released_at,cy.confidentiality_threshold having count(distinct rr.respondent_id)>=cy.confidentiality_threshold
 union all select pa.id,'project',dp.title,dp.description,null,null,null,pa.updated_at,pa.status from candidate_project_assignments pa join subject c on pa.candidate_id=c.id and pa.organization_id=c.organization_id join development_projects dp on dp.id=pa.development_project_id and (dp.organization_id=c.organization_id or dp.organization_id is null) where dp.deleted_at is null
 union all select t.id,'training',tp.name,tp.description,null,null,null,t.updated_at,t.status from training_selections t join subject c on t.candidate_id=c.id and t.organization_id=c.organization_id join training_programs tp on tp.id=t.training_program_id and tp.organization_id=c.organization_id
 union all select m.id,'mentor_plan','Mentoring with '||p.full_name,'Active target-role mentor assignment',null,null,null,m.updated_at,m.status from mentor_role_assignments m join subject c on m.candidate_id=c.id and m.organization_id=c.organization_id and m.role_id=c.target_role_id join profiles p on p.id=m.mentor_profile_id and p.organization_id=c.organization_id and p.deleted_at is null where m.status='active'
 union all select s.id,'clifton_strengths',s.theme_name,'Strengths theme rank '||s.rank||' ('||s.domain||'). Preference context, not an observed performance score.',null,null,null,s.updated_at,'recorded' from candidate_strengths s join subject c on s.candidate_id=c.id and s.organization_id=c.organization_id
 union all select m.id,'readiness','Human readiness record','Role alignment: '||m.match_status||'. Recorded role-goal score: '||coalesce(m.readiness_score::text,'not recorded')||' / 100. This is not a probability of readiness.',null,null,null,m.created_at,'recorded' from candidate_role_matches m join subject c on m.candidate_id=c.id and m.organization_id=c.organization_id and m.role_id=c.target_role_id
)
select coalesce(jsonb_agg(jsonb_build_object('id',id,'data_type',kind,'title',title,'description',description,'competency_id',competency_id,'current_level',current_level,'target_level',target_level,'occurred_at',occurred_at,'status',status) order by occurred_at desc nulls last),'[]') from items $$;
create function development_internal.source_visible(n leadership_development_needs) returns boolean language sql stable security definer set search_path=public as $$ select n.source_type in ('leader_input','self_assessment','mentor_observation','other') or exists(select 1 from jsonb_array_elements(development_internal.sources(n.candidate_id)) s where s->>'id'=n.source_id::text and s->>'data_type'=n.source_type) $$;
create or replace function development_internal.need_read(nid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from leadership_development_needs n where id=nid and development_internal.source_visible(n) and (development_internal.member(n.candidate_id) or exists(select 1 from coaching_engagements e where e.candidate_id=n.candidate_id and e.organization_id=n.organization_id and coaching_is_coach(e.id) and development_internal.shared(e.id,'development_need',n.id)))) $$;
-- Expand existing client-controlled consent selection instead of creating a second permission system.
create or replace function public.coaching_development(eid uuid, available boolean default false) returns jsonb language plpgsql stable security definer set search_path=public as $$
declare e coaching_engagements; items jsonb;begin
 select * into e from coaching_engagements where id=eid;
 if not(coaching_is_client(eid) or coaching_is_coach(eid)) then raise exception 'Not authorized';end if;
 if available and not coaching_is_client(eid) then raise exception 'Only the client may select data to share';end if;
 if not available and not coaching_has_consent(eid,'development_data_access') then return '[]';end if;
 items:=development_internal.sources(e.candidate_id);
 select items||coalesce(jsonb_agg(jsonb_build_object('id',n.id,'data_type','development_need','title',n.title,'description',n.description,'competency_id',n.competency_id,'priority',n.priority,'status',n.status)),'[]') into items from leadership_development_needs n where candidate_id=e.candidate_id and organization_id=e.organization_id and development_internal.source_visible(n);
 return (select coalesce(jsonb_agg(x),'[]') from jsonb_array_elements(items) x where available or development_internal.shared(eid,x->>'data_type',(x->>'id')::uuid));end $$;
create function development_internal.recommend(nid uuid) returns uuid language plpgsql security definer set search_path=public as $$
declare n leadership_development_needs; rule development_method_rules; cfg development_intelligence_versions; methods jsonb; result uuid; name text;begin
 select * into n from leadership_development_needs where id=nid;select * into cfg from development_intelligence_versions order by created_at desc,id desc limit 1;
 select rc.name into name from role_competencies rc where id=n.competency_id;
 select * into rule from development_method_rules r where active and (r.organization_id=n.organization_id or r.organization_id is null) and (r.competency_id=n.competency_id or (r.competency_id is null and lower(trim(r.competency_name))=lower(trim(name))) or (r.competency_id is null and r.competency_name is null and r.need_type=n.need_type)) order by (r.organization_id is not null) desc,(r.competency_id is not null) desc,r.created_at desc,r.id desc limit 1;
 if rule.id is null then methods:='{"assessment":2,"self_development":1}';else methods:=jsonb_build_object('coaching',rule.coaching_weight,'mentoring',rule.mentoring_weight,'project',rule.project_weight,'training',rule.training_weight,'experience',rule.experience_weight);end if;
 insert into development_recommendations(organization_id,candidate_id,development_need_id,recommendation_type,recommendation_data,rationale,model_version,rule_id)
 select n.organization_id,n.candidate_id,n.id,'development_methods',jsonb_build_object('weights',methods,'focus','Practice '||n.title||' through an agreed activity, feedback and reflection.','duration_months','3–6','session_range','6–12','source_type',n.source_type,'source_id',n.source_id,'baseline',n.baseline_level,'target',n.target_level,'rule_version',coalesce(rule.version,'unconfigured'),'coaching_suitable',coalesce(rule.coaching_weight,0)>=2),coalesce(rule.rationale,'No method rule is configured for this need. Review the evidence and determine the appropriate development approach.'),cfg.version,rule.id
 where not exists(select 1 from development_recommendations where development_need_id=n.id and model_version=cfg.version and rule_id is not distinct from rule.id) returning id into result;
 if result is not null then update leadership_development_needs set recommended_response=array(select key from jsonb_each_text(methods) where value::int>=2) where id=n.id;end if;return result;end $$;
create function public.development_intelligence_analyze(candidate uuid) returns integer language plpgsql security definer set search_path=public as $$
declare c candidates; competency record; score jsonb; gap numeric; nid uuid; count_new integer:=0; rule development_method_rules;begin
 if not development_internal.admin(candidate) then raise exception 'Organization administrator required';end if;
 select * into c from candidates where id=candidate for update;
 for competency in select * from role_competencies where role_id=c.target_role_id and organization_id=c.organization_id and deleted_at is null loop
 select s into score from jsonb_array_elements(development_internal.sources(c.id)) s where s->>'competency_id'=competency.id::text and s->>'current_level' is not null and (s->>'data_type'<>'development_plan' or s->>'occurred_at' is not null) order by (s->>'occurred_at')::timestamptz desc nulls last,case s->>'data_type' when 'assessment' then 0 when 'development_plan' then 1 else 2 end limit 1;
 if score is null then continue;end if;gap:=competency.target_score-(score->>'current_level')::numeric;if gap<=0 then continue;end if;
 select * into rule from development_method_rules where active and (organization_id=c.organization_id or organization_id is null) and (competency_id=competency.id or lower(trim(competency_name))=lower(trim(competency.name))) order by (organization_id is not null) desc,created_at desc limit 1;
 insert into leadership_development_needs(organization_id,candidate_id,target_role_id,competency_id,need_type,title,description,source_type,source_id,source_key,gap_severity,priority,baseline_level,target_level,identified_by)
 values(c.organization_id,c.id,c.target_role_id,competency.id,coalesce(rule.need_type,'competency_gap'),competency.name,'Recorded score '||(score->>'current_level')||' / 5; role target '||competency.target_score||' / 5. Source: '||(score->>'title')||'. Human review required.',score->>'data_type',(score->>'id')::uuid,competency.id||':'||(score->>'data_type')||':'||(score->>'id'),case when gap>=3 then 'critical' when gap>=2 then 'significant' when gap>=1 then 'moderate' else 'minor' end,case when gap>=2 then 'high' else 'moderate' end,(score->>'current_level')::numeric,competency.target_score,auth.uid()) on conflict(candidate_id,source_key) do nothing returning id into nid;
 if nid is null then select id into nid from leadership_development_needs where candidate_id=c.id and source_key=competency.id||':'||(score->>'data_type')||':'||(score->>'id');else count_new:=count_new+1;end if;
 perform development_internal.recommend(nid);
 end loop;
 perform development_internal.audit('analysis_requested',candidate,null,jsonb_build_object('new_needs',count_new));return count_new;end $$;
create function public.development_intelligence_mutate(operation text,payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare cid uuid:=nullif(payload->>'candidate_id','')::uuid; item uuid:=nullif(payload->>'id','')::uuid; nid uuid:=nullif(payload->>'development_need_id','')::uuid; eid uuid:=nullif(payload->>'engagement_id','')::uuid; c candidates; n leadership_development_needs; e coaching_engagements; rec development_recommendations; ev development_evidence; cfg development_intelligence_versions; oldmatch candidate_role_matches; result uuid; goal coaching_goals; focus coaching_focus_areas; sid uuid; userid uuid; rule development_method_rules; source jsonb; v text; weight integer; levels jsonb;begin
 if not coaching_identity_enabled() then raise exception 'Not authorized';end if;
 if nid is not null then select * into n from leadership_development_needs where id=nid;if n.id is null or not development_internal.need_read(n.id) then raise exception 'Development need unavailable';end if;if cid is not null and cid<>n.candidate_id then raise exception 'Candidate mismatch';end if;cid:=n.candidate_id;end if;
 if eid is not null then select * into e from coaching_engagements where id=eid;if e.id is null or not(coaching_is_coach(eid) or coaching_is_client(eid) or development_internal.admin(e.candidate_id)) then raise exception 'Engagement unavailable';end if;if cid is not null and cid<>e.candidate_id then raise exception 'Candidate and engagement mismatch';end if;cid:=e.candidate_id;end if;
 select * into c from candidates where id=cid and deleted_at is null;select * into cfg from development_intelligence_versions order by created_at desc,id desc limit 1;
 if operation in ('rule','version','experience') then
 if not coaching_platform_admin() then raise exception 'Platform administrator required';end if;
 if operation='rule' then
 if item is not null then update development_method_rules set active=false where id=item;result:=item;
 else
 if nullif(payload->>'competency_id','') is not null and not exists(select 1 from role_competencies where id=(payload->>'competency_id')::uuid and organization_id=(payload->>'organization_id')::uuid and deleted_at is null) then raise exception 'Competency must belong to the configured organization';end if;
 insert into development_method_rules(organization_id,competency_id,competency_name,need_type,coaching_weight,mentoring_weight,project_weight,training_weight,experience_weight,rationale,version,created_by) values(nullif(payload->>'organization_id','')::uuid,nullif(payload->>'competency_id','')::uuid,nullif(payload->>'competency_name',''),nullif(payload->>'need_type',''),(payload->>'coaching_weight')::int,(payload->>'mentoring_weight')::int,(payload->>'project_weight')::int,(payload->>'training_weight')::int,(payload->>'experience_weight')::int,nullif(trim(payload->>'rationale'),''),nullif(trim(payload->>'version'),''),auth.uid()) returning id into result;end if;
 elsif operation='experience' then insert into coach_development_experience(coach_id,need_type,target_role_title,description,verified_by) values((payload->>'coach_id')::uuid,payload->>'need_type',nullif(payload->>'target_role_title',''),payload->>'description',auth.uid()) returning id into result;
 else
 levels:=payload->'matching_weights';if jsonb_typeof(levels)<>'object' or (select sum(value::numeric) from jsonb_each_text(levels))<>100 or exists(select 1 from jsonb_each_text(levels) where value::numeric<0 or value::numeric>100) or not levels ?& array['specialty','competency','development_need','industry','leadership_level','target_role','credential','format','availability','geography'] or (select count(*) from jsonb_object_keys(levels))<>10 then raise exception 'The ten matching weights must total 100';end if;
 if jsonb_typeof(payload->'evidence_weights')<>'object' or not (payload->'evidence_weights') ?& array['unverified','self_reported','coach_confirmed','mentor_confirmed','manager_confirmed','verified'] or exists(select 1 from jsonb_each_text(payload->'evidence_weights') where value::numeric<>trunc(value::numeric) or value::numeric not between 0 and 10) then raise exception 'Evidence weights must be whole numbers from 0 to 10';end if;
 insert into development_intelligence_versions(version,evidence_scoring_version,matching_weights,evidence_weights,review_days,recency_days,minimum_independent_sources,created_by) values(payload->>'version',payload->>'evidence_scoring_version',levels,payload->'evidence_weights',(payload->>'review_days')::int,(payload->>'recency_days')::int,(payload->>'minimum_independent_sources')::int,auth.uid()) returning id into result;end if;
 elsif operation='need' then
 if c.id is null or not development_internal.member(cid) then raise exception 'Candidate access required';end if;
 if nullif(payload->>'competency_id','') is not null and not exists(select 1 from role_competencies where id=(payload->>'competency_id')::uuid and organization_id=c.organization_id and role_id=c.target_role_id and deleted_at is null) then raise exception 'Competency must belong to target role';end if;
 if payload->>'source_type' not in ('leader_input','self_assessment','mentor_observation','other') then
 select s into source from jsonb_array_elements(development_internal.sources(cid)) s where s->>'id'=payload->>'source_id' and s->>'data_type'=payload->>'source_type' limit 1;if source is null then raise exception 'Authorized source required';end if;
 end if;
 if payload->>'source_type'='mentor_observation' and not development_internal.mentor(cid) and not development_internal.admin(cid) then raise exception 'Assigned mentor required';end if;
 insert into leadership_development_needs(organization_id,candidate_id,target_role_id,competency_id,need_type,title,description,source_type,source_id,source_key,gap_severity,priority,baseline_level,target_level,identified_by) values(c.organization_id,c.id,c.target_role_id,nullif(payload->>'competency_id','')::uuid,payload->>'need_type',nullif(trim(payload->>'title'),''),nullif(trim(payload->>'description'),''),payload->>'source_type',nullif(payload->>'source_id','')::uuid,'human:'||(payload->>'request_key')::uuid,nullif(payload->>'gap_severity',''),payload->>'priority',nullif(payload->>'baseline_level','')::numeric,nullif(payload->>'target_level','')::numeric,auth.uid()) returning id into result;
 perform development_internal.recommend(result);
 elsif operation='need_status' then
 if not development_internal.member(cid) then raise exception 'Candidate team required';end if;
 update leadership_development_needs set status=payload->>'status',reviewed_by=auth.uid(),reviewed_at=now() where id=nid;result:=nid;
 elsif operation='recommendation' then
 select * into rec from development_recommendations where id=item for update;if rec.id is null or not development_internal.need_read(rec.development_need_id) or not development_internal.member(rec.candidate_id) then raise exception 'Recommendation review access required';end if;cid:=rec.candidate_id;
 if payload->>'status' not in ('accepted','modified','dismissed','completed') then raise exception 'Human decision required';end if;
 if payload->>'status'='modified' and length(trim(coalesce(payload->>'focus','')))<3 then raise exception 'Describe the modified recommendation';end if;
 update development_recommendations set status=payload->>'status',reviewed_data=case when payload->>'status'='modified' then jsonb_build_object('focus',payload->>'focus') else reviewed_data end,reviewed_by=auth.uid(),reviewed_at=now() where id=item;result:=item;
 elsif operation='coaching_request' then
 if not development_internal.admin(cid) or not coaching_enabled(c.organization_id) then raise exception 'Activate Professional Coaching to receive coach matches and begin an engagement';end if;
 if not 'coaching'=any(n.recommended_response) then raise exception 'Review development methods before starting a coaching request';end if;
 select coalesce(u.auth_user_id,p.auth_user_id) into userid from organization_users u join profiles p on p.id=u.profile_id where u.candidate_id=cid and u.organization_id=c.organization_id and u.deleted_at is null and u.status='active' and p.deleted_at is null limit 1;
 if userid is null then raise exception 'Link the candidate to an active Leader Continuity user before requesting coaching';end if;
 select id into result from coach_requests where development_need_id=nid and status='draft' and organization_id=c.organization_id order by created_at desc limit 1;
 if result is null then
 result:=coaching_mutate('request_save',jsonb_build_object('requested_for_user_id',userid,'request_title',n.title||' development','request_reason','Development priority: '||n.priority||'. '||n.description,'development_focus',coalesce((select coalesce(reviewed_data->>'focus',recommendation_data->>'focus') from development_recommendations where development_need_id=nid and status in ('accepted','modified') order by reviewed_at desc,id desc limit 1),'Develop '||n.title||' through practice, feedback and measurable evidence.'),'competency_ids',case when n.competency_id is null then '[]'::jsonb else jsonb_build_array(n.competency_id) end,'context_categories',jsonb_build_array('competencies'),'objectives',jsonb_build_array('Prepare for Future Leadership Role'),'desired_duration_months',6,'estimated_sessions',12,'submit',false));
 update coach_requests set development_need_id=nid,preferred_industry_id=(select i.id from industries i join organizations o on lower(i.name)=lower(o.industry) where o.id=c.organization_id limit 1) where id=result;end if;
 elsif operation in ('plan','plan_status') then
 if not development_internal.member(cid) then raise exception 'Candidate team required';end if;
 if operation='plan_status' then update development_plan_steps set status=payload->>'status' where id=item and candidate_id=cid returning id into result;
 else
 for v in select unnest(array['development_record_id','project_assignment_id','training_selection_id','mentor_assignment_id']) loop
 if nullif(payload->>v,'') is not null and not exists(select 1 from jsonb_array_elements(development_internal.sources(cid)) s where s->>'id'=payload->>v and s->>'data_type'=case v when 'development_record_id' then 'development_plan' when 'project_assignment_id' then 'project' when 'training_selection_id' then 'training' else 'mentor_plan' end) then raise exception 'Activity does not belong to candidate';end if;end loop;
 if nullif(payload->>'owner_user_id','') is not null and not exists(select 1 from profiles where auth_user_id=(payload->>'owner_user_id')::uuid and organization_id=c.organization_id and deleted_at is null) then raise exception 'Owner must belong to organization';end if;
 insert into development_plan_steps(organization_id,candidate_id,development_need_id,method,title,activity,owner_user_id,target_date,review_date,evidence_required,development_record_id,project_assignment_id,training_selection_id,mentor_assignment_id,coaching_engagement_id,created_by) values(c.organization_id,c.id,nid,payload->>'method',payload->>'title',payload->>'activity',nullif(payload->>'owner_user_id','')::uuid,nullif(payload->>'target_date','')::date,nullif(payload->>'review_date','')::date,payload->>'evidence_required',nullif(payload->>'development_record_id','')::uuid,nullif(payload->>'project_assignment_id','')::uuid,nullif(payload->>'training_selection_id','')::uuid,nullif(payload->>'mentor_assignment_id','')::uuid,eid,auth.uid()) returning id into result;end if;
 elsif operation='focus' then
 if eid is null or not(coaching_is_coach(eid) or coaching_is_client(eid)) or not development_internal.shared(eid,'development_need',nid) then raise exception 'Shared development need required';end if;
 if item is not null then update coaching_focus_areas set status=payload->>'status' where id=item and engagement_id=eid returning id into result;
 else insert into coaching_focus_areas(engagement_id,development_need_id,competency_id,title,description,baseline_level,target_level,priority,created_by) values(eid,nid,n.competency_id,payload->>'title',payload->>'description',n.baseline_level,n.target_level,n.priority,auth.uid()) returning id into result;end if;
 elsif operation='link_goal' then
 select * into goal from coaching_goals where id=(payload->>'goal_id')::uuid;select * into focus from coaching_focus_areas where id=(payload->>'focus_area_id')::uuid;
 if goal.engagement_id is distinct from eid or focus.engagement_id is distinct from eid or not coaching_is_coach(eid) or not development_internal.shared(eid,'development_need',focus.development_need_id) then raise exception 'Authorized goal and focus in the same engagement required';end if;
 update coaching_goals set focus_area_id=focus.id where id=goal.id;result:=goal.id;
 elsif operation='evidence' then
 if c.id is null or not(development_internal.member(cid) or coaching_is_coach(eid)) then raise exception 'Evidence access required';end if;
 if eid is not null and not(coaching_is_client(eid) or coaching_is_coach(eid)) then raise exception 'Only participants can originate coaching evidence';end if;
 if coaching_is_coach(eid) and nid is not null and not development_internal.shared(eid,'development_need',nid) then raise exception 'Development need not shared';end if;
 if payload->>'evidence_type' not in ('project_completed','presentation_delivered','training_completed','360_change','manager_observation','mentor_observation','coach_shared_milestone','assessment_change','behavior_demonstrated','assignment_completed','certification','document','other') then raise exception 'Invalid evidence type';end if;
 if payload->>'evidence_type'='coach_shared_milestone' and not coaching_is_coach(eid) then raise exception 'Assigned coach required';end if;
 if nullif(payload->>'competency_id','') is not null and not exists(select 1 from role_competencies where id=(payload->>'competency_id')::uuid and role_id=c.target_role_id and organization_id=c.organization_id and deleted_at is null) then raise exception 'Target-role competency required';end if;
 if nullif(payload->>'coaching_goal_id','') is not null and not exists(select 1 from coaching_goals where id=(payload->>'coaching_goal_id')::uuid and engagement_id=eid and visibility<>'coach_private') then raise exception 'Shared goal in this engagement required';end if;
 for v in select unnest(array['development_record_id','project_assignment_id','training_selection_id','mentor_assignment_id']) loop
 if nullif(payload->>v,'') is not null and not exists(select 1 from jsonb_array_elements(development_internal.sources(cid)) s where s->>'id'=payload->>v and s->>'data_type'=case v when 'development_record_id' then 'development_plan' when 'project_assignment_id' then 'project' when 'training_selection_id' then 'training' else 'mentor_plan' end) then raise exception 'Authorized candidate activity required';end if;end loop;
 if (payload->>'evidence_date')::date>current_date then raise exception 'Evidence cannot be future dated';end if;
 v:=case when coaching_is_coach(eid) then 'coach_confirmed' else 'self_reported' end;weight:=(cfg.evidence_weights->>v)::int;
 insert into development_evidence(organization_id,candidate_id,development_need_id,competency_id,coaching_engagement_id,coaching_goal_id,project_assignment_id,training_selection_id,mentor_assignment_id,development_record_id,evidence_type,title,description,evidence_date,source_user_id,visibility,verification_status,verified_by,verified_at,scoring_version,evidence_weight,request_key)
 values(c.organization_id,cid,nid,nullif(payload->>'competency_id','')::uuid,eid,nullif(payload->>'coaching_goal_id','')::uuid,nullif(payload->>'project_assignment_id','')::uuid,nullif(payload->>'training_selection_id','')::uuid,nullif(payload->>'mentor_assignment_id','')::uuid,nullif(payload->>'development_record_id','')::uuid,payload->>'evidence_type',nullif(trim(payload->>'title'),''),nullif(trim(payload->>'description'),''),(payload->>'evidence_date')::date,auth.uid(),case when eid is not null then 'coach_client' else 'private' end,v,case when v='coach_confirmed' then auth.uid() end,case when v='coach_confirmed' then now() end,cfg.evidence_scoring_version,weight,(payload->>'request_key')::uuid) returning id into result;
 elsif operation in ('evidence_share','evidence_verify') then
 select * into ev from development_evidence where id=item for update;if ev.id is null or not development_internal.evidence_read(ev) then raise exception 'Evidence unavailable';end if;cid:=ev.candidate_id;
 if operation='evidence_share' then
 if ev.coaching_engagement_id is not null then
 if not coaching_is_client(ev.coaching_engagement_id) or not coaching_has_consent(ev.coaching_engagement_id,'organization_reporting') then raise exception 'Client approval and organization-reporting consent required';end if;
 elsif ev.source_user_id<>auth.uid() then raise exception 'Evidence owner approval required';end if;
 if payload->>'visibility' not in ('organization','readiness_review','coach_client','private') or (ev.coaching_engagement_id is not null and payload->>'visibility'='private') or (ev.coaching_engagement_id is null and payload->>'visibility'='coach_client') then raise exception 'Invalid sharing scope';end if;
 update development_evidence set visibility=payload->>'visibility',readiness_approved_by=case when payload->>'visibility'='readiness_review' then auth.uid() end,readiness_approved_at=case when payload->>'visibility'='readiness_review' then now() end where id=item;
 else
 if ev.source_user_id=auth.uid() then raise exception 'Independent confirmation required';end if;
 v:=case when development_internal.admin(cid) then 'manager_confirmed' when development_internal.mentor(cid) then 'mentor_confirmed' when coaching_is_coach(ev.coaching_engagement_id) then 'coach_confirmed' end;
 if v is null then raise exception 'Authorized verifier required';end if;
 update development_evidence set verification_status=v,verified_by=auth.uid(),verified_at=now(),scoring_version=cfg.evidence_scoring_version,evidence_weight=(cfg.evidence_weights->>v)::int where id=item;
 end if;result:=item;
 elsif operation='progress' then
 if nid is null or not development_internal.need_read(nid) or not(development_internal.member(cid) or coaching_is_coach(eid)) then raise exception 'Development review access required';end if;
 if exists(select 1 from jsonb_array_elements_text(coalesce(payload->'evidence_ids','[]')) x where not exists(select 1 from development_evidence proof where proof.id=x::uuid and proof.candidate_id=cid and development_internal.evidence_read(proof))) then raise exception 'Authorized evidence required';end if;
 insert into development_progress_reviews(organization_id,candidate_id,engagement_id,development_need_id,competency_id,review_type,baseline_level,current_level,progress_status,evidence_summary,evidence_ids,visibility,reviewed_by) values(c.organization_id,cid,eid,nid,n.competency_id,payload->>'review_type',n.baseline_level,nullif(payload->>'current_level','')::numeric,payload->>'progress_status',payload->>'evidence_summary',array(select value::uuid from jsonb_array_elements_text(coalesce(payload->'evidence_ids','[]'))),case when eid is not null then 'coach_client' else 'organization' end,auth.uid()) returning id into result;
 elsif operation='readiness' then
 if not development_internal.admin(cid) or c.target_role_id is null then raise exception 'Authorized organization leader and target role required';end if;
 if length(trim(coalesce(payload->>'reason','')))<5 or payload->>'match_status' is null or payload->>'match_status' not in ('match','not_yet','not_recommended') then raise exception 'Human decision and reason required';end if;
 if exists(select 1 from jsonb_array_elements_text(coalesce(payload->'evidence_ids','[]')) x where not exists(select 1 from development_evidence proof where proof.id=x::uuid and proof.candidate_id=cid and proof.visibility='readiness_review' and proof.readiness_approved_at is not null and development_internal.evidence_read(proof))) then raise exception 'Only authorized readiness evidence can support this decision';end if;
 perform 1 from candidates where id=cid for update;
 select * into oldmatch from candidate_role_matches where candidate_id=cid and role_id=c.target_role_id and organization_id=c.organization_id order by created_at desc,id desc limit 1;
 insert into candidate_role_matches(organization_id,candidate_id,role_id,match_status,readiness_score,decision_notes,recorded_by_profile_id) values(c.organization_id,cid,c.target_role_id,payload->>'match_status',nullif(payload->>'readiness_score','')::numeric,payload->>'reason',(select id from profiles where auth_user_id=auth.uid())) returning id into sid;
 insert into readiness_history(organization_id,candidate_id,target_role_id,previous_match_id,new_match_id,previous_readiness,new_readiness,reason,supporting_evidence_ids,changed_by) values(c.organization_id,cid,c.target_role_id,oldmatch.id,sid,oldmatch.readiness_score,nullif(payload->>'readiness_score','')::numeric,payload->>'reason',array(select value::uuid from jsonb_array_elements_text(coalesce(payload->'evidence_ids','[]'))),auth.uid()) returning id into result;
 elsif operation in ('outcome_share','progress_share') then
 if not coaching_is_client(eid) then raise exception 'Only the client may approve sharing';end if;
 if payload->>'visibility' is null or payload->>'visibility' not in ('coach_client','organization','readiness_review') then raise exception 'Invalid visibility';end if;
 if payload->>'visibility'<>'coach_client' and not coaching_has_consent(eid,'organization_reporting') then raise exception 'Organization reporting consent required';end if;
 if operation='outcome_share' then update coaching_outcome_measures set visibility=payload->>'visibility' where id=item and engagement_id=eid returning id into result;
 else update development_progress_reviews set visibility=payload->>'visibility' where id=item and engagement_id=eid returning id into result;end if;
 if result is null then raise exception 'Record does not belong to this engagement';end if;
 elsif operation='outcome' then
 for v in select unnest(array['baseline_value','target_value','final_value']) loop if lower(coalesce(payload->>v,'')) in ('nan','infinity','-infinity','inf','-inf') then raise exception 'Outcome values must be finite numbers';end if;end loop;
 if eid is null or not(coaching_is_coach(eid) or coaching_is_client(eid)) then raise exception 'Coaching participant required';end if;
 if nullif(payload->>'evidence_id','') is not null then select * into ev from development_evidence where id=(payload->>'evidence_id')::uuid;if ev.coaching_engagement_id is distinct from eid or not development_internal.evidence_read(ev) then raise exception 'Evidence must belong to this engagement';end if;end if;
 insert into coaching_outcome_measures(engagement_id,development_need_id,competency_id,measure_type,baseline_value,target_value,final_value,baseline_text,target_text,final_text,measurement_source,evidence_id,visibility,measured_by) values(eid,nid,n.competency_id,payload->>'measure_type',nullif(payload->>'baseline_value','')::numeric,nullif(payload->>'target_value','')::numeric,nullif(payload->>'final_value','')::numeric,payload->>'baseline_text',payload->>'target_text',payload->>'final_text',nullif(trim(payload->>'measurement_source'),''),ev.id,'coach_client',auth.uid()) returning id into result;
 else raise exception 'Unsupported development operation';end if;
 perform development_internal.audit(operation,cid,result,jsonb_build_object('human_decision',payload->>'status','visibility',payload->>'visibility','version',cfg.version));return result;end $$;
create function public.development_intelligence_read(candidate uuid default null,engagement uuid default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare c candidates; e coaching_engagements; cfg development_intelligence_versions; src jsonb; evidence jsonb; needs jsonb; team boolean; result jsonb; review_at timestamptz; sources_count integer; quality integer; row record;begin
 if not coaching_identity_enabled() then raise exception 'Not authorized';end if;
 select * into cfg from development_intelligence_versions order by created_at desc,id desc limit 1;
 if candidate is null and engagement is null then
 return jsonb_build_object('candidates',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',full_name,'role_id',target_role_id,'role',(select title from roles where id=candidates.target_role_id))),'[]') from candidates where deleted_at is null and development_internal.member(id)),'configuration',to_jsonb(cfg),'rules',(select coalesce(jsonb_agg(to_jsonb(r)),'[]') from development_method_rules r where organization_id is null or coaching_admin(organization_id)),'coaches',case when coaching_platform_admin() then (select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',display_name)),'[]') from coach_profiles) else '[]'::jsonb end,'experience',case when coaching_platform_admin() then (select coalesce(jsonb_agg(to_jsonb(x)),'[]') from coach_development_experience x) else '[]'::jsonb end);
 end if;
 if engagement is not null then select * into e from coaching_engagements where id=engagement;if candidate is not null and candidate is distinct from e.candidate_id then raise exception 'Candidate mismatch';end if;candidate:=e.candidate_id;end if;
 select * into c from candidates where id=candidate and deleted_at is null;
 team:=development_internal.member(candidate);
 if c.id is null or not(team or (engagement is not null and coaching_is_coach(engagement))) then raise exception 'Candidate development access required';end if;
 src:=case when engagement is not null and not team then coaching_development(engagement) else development_internal.sources(candidate) end;
 select coalesce(jsonb_agg(to_jsonb(n)),'[]') into needs from leadership_development_needs n where n.candidate_id=candidate and development_internal.need_read(n.id) and (team or development_internal.shared(engagement,'development_need',n.id));
 select coalesce(jsonb_agg(to_jsonb(x) order by evidence_date desc,created_at desc),'[]') into evidence from development_evidence x where candidate_id=candidate and development_internal.evidence_read(x) and (team or coaching_engagement_id=engagement);
 select max(changed_at) into review_at from readiness_history where candidate_id=candidate and target_role_id=c.target_role_id;
 select count(distinct x.source_user_id),coalesce(sum(x.evidence_weight),0) into sources_count,quality from development_evidence x where candidate_id=candidate and visibility='readiness_review' and readiness_approved_at is not null and evidence_date>=current_date-cfg.recency_days and development_internal.evidence_read(x) and (team or coaching_engagement_id=engagement);
 result:=jsonb_build_object('candidate',jsonb_build_object('id',c.id,'name',c.full_name,'target_role_id',case when team or development_internal.shared(engagement,'target_role',c.target_role_id) then c.target_role_id end,'target_role',case when team or development_internal.shared(engagement,'target_role',c.target_role_id) then (select title from roles where id=c.target_role_id) end),'admin',development_internal.admin(candidate),'self',development_internal.self(candidate),'mentor',development_internal.mentor(candidate),'participant',coaching_is_client(engagement) or coaching_is_coach(engagement),'coaching_active',coaching_enabled(c.organization_id),'configuration',to_jsonb(cfg),'sources',src,'needs',needs,'evidence',evidence,
 'owners',case when team then (select coalesce(jsonb_agg(jsonb_build_object('id',auth_user_id,'name',full_name)),'[]') from profiles where organization_id=c.organization_id and deleted_at is null and auth_user_id is not null) else '[]'::jsonb end,
 'recommendations',(select coalesce(jsonb_agg(to_jsonb(r)),'[]') from development_recommendations r where candidate_id=candidate and development_need_id in (select (x->>'id')::uuid from jsonb_array_elements(needs) x)),
 'plans',case when team then (select coalesce(jsonb_agg(to_jsonb(p)),'[]') from development_plan_steps p where candidate_id=candidate and development_internal.need_read(development_need_id)) else '[]'::jsonb end,
 'focus',(select coalesce(jsonb_agg(to_jsonb(f)),'[]') from coaching_focus_areas f where f.engagement_id=engagement and (coaching_is_client(engagement) or coaching_is_coach(engagement)) and development_internal.shared(engagement,'development_need',development_need_id)),
 'goals',(select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'title',g.title,'status',g.status,'focus_area_id',g.focus_area_id,'visibility',g.visibility)),'[]') from coaching_goals g join coaching_engagements ce on ce.id=g.engagement_id where ce.candidate_id=candidate and (engagement is null or ce.id=engagement) and g.visibility<>'coach_private' and (coaching_is_client(ce.id) or coaching_is_coach(ce.id) or (team and g.visibility='organization_shared' and coaching_has_consent(ce.id,'organization_reporting')))),
 'reviews',(select coalesce(jsonb_agg(to_jsonb(r)),'[]') from development_progress_reviews r where candidate_id=candidate and development_internal.need_read(development_need_id) and ((r.engagement_id is null and team) or (r.engagement_id=engagement and (coaching_is_client(engagement) or coaching_is_coach(engagement))) or (team and r.visibility in ('organization','readiness_review') and coaching_has_consent(r.engagement_id,'organization_reporting')))),
 'readiness_history',case when team then (select coalesce(jsonb_agg(to_jsonb(h) order by changed_at desc),'[]') from readiness_history h where candidate_id=candidate) else '[]'::jsonb end,
 'current_readiness',case when team then (select jsonb_build_object('id',id,'match_status',match_status,'readiness_score',readiness_score,'recorded_at',created_at) from candidate_role_matches where candidate_id=candidate and role_id=c.target_role_id and organization_id=c.organization_id order by created_at desc,id desc limit 1) else null end,
 'outcomes',(select coalesce(jsonb_agg(to_jsonb(o)),'[]') from coaching_outcome_measures o join coaching_engagements ce on ce.id=o.engagement_id where ce.candidate_id=candidate and ((o.engagement_id=engagement and (coaching_is_client(engagement) or coaching_is_coach(engagement))) or (team and o.visibility in ('organization','readiness_review') and coaching_has_consent(o.engagement_id,'organization_reporting')))),
 'engagements',(select coalesce(jsonb_agg(jsonb_build_object('id',ce.id,'title',ce.title,'status',ce.status,'start_date',ce.start_date,'planned_end_date',ce.planned_end_date)),'[]') from coaching_engagements ce where ce.candidate_id=candidate and (team or coaching_is_coach(ce.id))),
 'evidence_confidence',case when sources_count>=cfg.minimum_independent_sources and quality>=6 then 'Strong evidence' when sources_count>=cfg.minimum_independent_sources then 'Moderate evidence' else 'Low evidence' end,
 'system_recommendation',case when exists(select 1 from jsonb_array_elements(evidence) x where x->>'visibility'='readiness_review' and (x->>'evidence_weight')::int>=2 and greatest((x->>'created_at')::timestamptz,(x->>'readiness_approved_at')::timestamptz,(x->>'verified_at')::timestamptz)>coalesce(review_at,'-infinity'::timestamptz)) then 'New development evidence is available. A human readiness review is recommended.' else 'Additional evidence is needed before considering a readiness change.' end);
 if team then
 if result->>'system_recommendation' like '%human readiness review%' then insert into notifications(recipient_user_id,event_type,title,href,dedupe_key) values(auth.uid(),'readiness_review_recommended','New evidence is available for a human readiness review','/candidates/'||candidate||'/readiness-review','readiness_review:'||candidate||':'||coalesce(review_at::text,'first')) on conflict do nothing;end if;
 if exists(select 1 from coaching_engagements ce where ce.candidate_id=candidate and ce.status='active' and ce.start_date+cfg.review_days<=current_date and not exists(select 1 from development_progress_reviews pr where pr.engagement_id=ce.id and pr.reviewed_at>=now()-make_interval(days=>cfg.review_days) and (coaching_is_client(ce.id) or (pr.visibility in ('organization','readiness_review') and coaching_has_consent(ce.id,'organization_reporting'))))) then insert into notifications(recipient_user_id,event_type,title,href,dedupe_key) values(auth.uid(),'coaching_progress_review_due','Review development progress at the configured interval','/candidates/'||candidate||'/development-intelligence','progress_review:'||candidate||':'||current_date) on conflict do nothing;end if;
 for row in select n.id,n.status from leadership_development_needs n where candidate_id=candidate and n.status in ('identified','accepted','active') and development_internal.need_read(n.id) and not exists(select 1 from development_plan_steps where development_need_id=n.id and status in ('planned','active')) loop
 insert into notifications(recipient_user_id,event_type,title,href,dedupe_key) values(auth.uid(),'development_plan_needed','Development need has no active plan','/candidates/'||candidate||'/development-intelligence','development_plan_needed:'||row.id) on conflict do nothing;end loop;
 if exists(select 1 from development_plan_steps where candidate_id=candidate and status in ('planned','active') and review_date<=current_date) then insert into notifications(recipient_user_id,event_type,title,href,dedupe_key) values(auth.uid(),'development_review_due','Development progress review is due','/candidates/'||candidate||'/development-intelligence','development_review_due:'||candidate||':'||current_date) on conflict do nothing;end if;
 end if;
 return result;end $$;
-- Version 2 reuses Sprint 2 eligibility, capacity, invitation and matching infrastructure.
alter function public.coaching_run_matching(uuid) rename to coaching_run_matching_sprint2;
revoke all on function public.coaching_run_matching_sprint2(uuid) from public,anon,authenticated;
create function public.coaching_run_matching(rid uuid) returns uuid language plpgsql security definer set search_path=public as $$
declare r coach_requests; n leadership_development_needs; cfg development_intelligence_versions; run uuid; m coaching_match_results; factors jsonb; reason jsonb; unmet jsonb; key text; val text; fraction numeric; total numeric; role_name text;begin
 run:=coaching_run_matching_sprint2(rid);
 select * into r from coach_requests where id=rid;
 if r.development_need_id is null then return run;end if;
 select * into n from leadership_development_needs where id=r.development_need_id;
 if n.candidate_id is distinct from r.candidate_id or not development_internal.admin(n.candidate_id) or not development_internal.source_visible(n) then raise exception 'Development context is no longer available';end if;
 select * into cfg from development_intelligence_versions order by created_at desc,id desc limit 1;select title into role_name from roles where id=r.target_role_id;
 for m in select * from coaching_match_results where run_id=run loop
 factors:='{}';reason:=m.match_reasons;unmet:=m.unmet_preferences;total:=0;
 for key,val in select * from jsonb_each_text(cfg.matching_weights) loop
 if key='development_need' then fraction:=case when 'coaching'=any(n.recommended_response) and exists(select 1 from coach_development_experience where coach_id=m.coach_id and need_type=n.need_type) then 1 else 0 end;
 elsif key='target_role' then fraction:=case when exists(select 1 from coach_development_experience where coach_id=m.coach_id and lower(trim(target_role_title))=lower(trim(role_name))) then 1 else 0 end;
 else fraction:=coalesce((m.factor_scores->key->>'fraction')::numeric,0);end if;
 factors:=factors||jsonb_build_object(key,jsonb_build_object('weight',val::numeric,'fraction',fraction,'points',val::numeric*fraction));total:=total+val::numeric*fraction;
 if key in ('development_need','target_role') then if fraction>0 then reason:=reason||to_jsonb(case key when 'development_need' then 'Verified experience aligned to development need type' else 'Verified experience with the target role title' end);else unmet:=unmet||to_jsonb(key||': no verified experience recorded');end if;end if;
 end loop;
 update coaching_match_results set match_score=total,factor_scores=factors,match_reasons=reason,unmet_preferences=unmet,matching_version='v2-development' where id=m.id;
 end loop;
 perform development_internal.audit('matching_v2',n.candidate_id,rid,jsonb_build_object('run_id',run,'matching_version','v2-development','rules_version',cfg.version,'historical_outcomes_used',false));return run;end $$;
-- Prevent a draft's linked need from silently moving to a different leader during editing.
alter function public.coaching_mutate(text,jsonb) rename to coaching_mutate_sprint3;
revoke all on function public.coaching_mutate_sprint3(text,jsonb) from public,anon,authenticated;
create function public.coaching_mutate(operation text,payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare result uuid; r coach_requests;begin
 result:=coaching_mutate_sprint3(operation,payload);
 if operation='request_save' then select * into r from coach_requests where id=result;if r.development_need_id is not null and not exists(select 1 from leadership_development_needs where id=r.development_need_id and candidate_id=r.candidate_id and target_role_id is not distinct from r.target_role_id) then raise exception 'This request is linked to another development context. Start a new request for a different leader or role.';end if;end if;
 return result;end $$;
revoke all on all functions in schema development_internal from public,anon,authenticated;
revoke all on function development_intelligence_read(uuid,uuid),development_intelligence_mutate(text,jsonb),development_intelligence_analyze(uuid),coaching_run_matching(uuid),coaching_mutate(text,jsonb) from public,anon,authenticated;
grant execute on function development_intelligence_read(uuid,uuid),development_intelligence_mutate(text,jsonb),development_intelligence_analyze(uuid),coaching_run_matching(uuid),coaching_mutate(text,jsonb) to authenticated;
create function public.development_intelligence_outcomes() returns jsonb language plpgsql security definer set search_path=public as $$
declare org uuid; coach uuid; c record; rows jsonb:='[]'; heat jsonb:='[]'; src jsonb; rc jsonb; score jsonb; label text;begin
 if not coaching_identity_enabled() then raise exception 'Not authorized';end if;
 select organization_id into org from profiles where auth_user_id=auth.uid() and role in ('system_admin','hospital_admin') and deleted_at is null;
 select id into coach from coach_profiles where user_id=auth.uid() and profile_status='approved';
 if org is null and coach is null then raise exception 'Organization administrator or coach required';end if;
 if org is not null then
 for c in select * from candidates where organization_id=org and deleted_at is null loop
 src:=development_internal.sources(c.id);
 rows:=rows||jsonb_build_object('id',c.id,'name',c.full_name,'role',(select title from roles where id=c.target_role_id),'role_id',c.target_role_id,'needs',(select count(*) from leadership_development_needs n where candidate_id=c.id and status in ('identified','accepted','active') and development_internal.source_visible(n)),'coaching_opportunities',(select count(*) from leadership_development_needs n where candidate_id=c.id and status in ('identified','accepted','active') and 'coaching'=any(recommended_response) and development_internal.source_visible(n)),'shared_evidence',(select count(*) from development_evidence x where candidate_id=c.id and visibility in ('organization','readiness_review') and development_internal.evidence_read(x)),'readiness_reviews',(select count(*) from readiness_history where candidate_id=c.id),'plans',(select count(*) from development_plan_steps where candidate_id=c.id and status in ('planned','active')));
 for rc in select value from jsonb_array_elements(src) where value->>'data_type'='competencies' loop
 select x into score from jsonb_array_elements(src) x where x->>'competency_id'=rc->>'id' and x->>'current_level' is not null and (x->>'data_type'<>'development_plan' or x->>'occurred_at' is not null) order by (x->>'occurred_at')::timestamptz desc nulls last limit 1;
 label:=case when score is null then 'Not assessed' when (score->>'current_level')::numeric>=(rc->>'target_level')::numeric then 'Competency demonstrated' when exists(select 1 from development_plan_steps p join leadership_development_needs n on n.id=p.development_need_id where p.candidate_id=c.id and n.competency_id=(rc->>'id')::uuid and p.status in ('planned','active')) then 'Developing' else 'Development gap' end;
 heat:=heat||jsonb_build_object('candidate_id',c.id,'candidate',c.full_name,'role_id',c.target_role_id,'competency_id',rc->>'id','competency',rc->>'title','status',label);
 end loop;end loop;
 end if;
 return jsonb_build_object('candidates',rows,'heatmap',heat,'metrics',jsonb_build_object(
 'Active coaching engagements',(select count(*) from coaching_engagements where status='active' and (case when org is not null then organization_id=org else coach_id=coach end)),
 'Completed engagements',(select count(*) from coaching_engagements where status='completed' and (case when org is not null then organization_id=org else coach_id=coach end)),
 'Shared goals achieved',(select count(*) from coaching_goals g join coaching_engagements e on e.id=g.engagement_id where g.status='achieved' and case when org is not null then e.organization_id=org and g.visibility='organization_shared' and coaching_has_consent(e.id,'organization_reporting') else e.coach_id=coach and g.visibility<>'coach_private' end),
 'Shared development milestones',(select count(*) from development_evidence x where x.evidence_type='coach_shared_milestone' and case when org is not null then x.organization_id=org and x.visibility in ('organization','readiness_review') and development_internal.evidence_read(x) else x.coaching_engagement_id in(select id from coaching_engagements where coach_id=coach) and development_internal.evidence_read(x) end)),
 'association_label','Development activity associated with readiness change. Coaching is one contributor; this does not establish causation.',
 'learning_dataset',case when org is null then '[]'::jsonb else (select coalesce(jsonb_agg(jsonb_build_object('development_need_id',n.id,'candidate_id',n.candidate_id,'role_id',n.target_role_id,'competency_id',n.competency_id,'methods',n.recommended_response,'coaching_engagement_id',e.id,'coach_id',e.coach_id,'start_date',e.start_date,'planned_end_date',e.planned_end_date,'completed_sessions',(select count(*) from coaching_sessions where engagement_id=e.id and status='completed'),'shared_evidence_ids',(select coalesce(jsonb_agg(x.id),'[]') from development_evidence x where x.development_need_id=n.id and visibility='readiness_review' and development_internal.evidence_read(x)),'readiness_history_ids',(select coalesce(jsonb_agg(h.id),'[]') from readiness_history h where h.candidate_id=n.candidate_id and h.target_role_id=n.target_role_id))),'[]') from leadership_development_needs n join coach_requests rq on rq.development_need_id=n.id left join coaching_engagements e on e.coach_request_id=rq.id where n.organization_id=org and development_internal.source_visible(n)) end,'outcomes_used_for_matching',false);
end $$;
revoke all on function development_intelligence_outcomes() from public,anon,authenticated;
grant execute on function development_intelligence_outcomes() to authenticated;
create index development_needs_candidate on leadership_development_needs(candidate_id,target_role_id,status);
create index development_evidence_candidate on development_evidence(candidate_id,visibility,evidence_date);
create index development_evidence_engagement on development_evidence(coaching_engagement_id);
create index development_plans_need on development_plan_steps(development_need_id,status);
create index development_reviews_candidate on development_progress_reviews(candidate_id,reviewed_at);
create index development_readiness_candidate on readiness_history(candidate_id,target_role_id,changed_at);
commit;
